"""Structured visual media intelligence for Tech Connector.

This module provides a deterministic, local baseline for image/video review.
It reads real image pixels when possible and is explicit about uncertainty
instead of returning semantic claims that were not measured.
"""

from __future__ import annotations

import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tif", ".tiff"}
VIDEO_EXTENSIONS = {".mp4", ".mov", ".avi", ".mkv", ".webm", ".m4v"}
VISUAL_MEDIA_EXTENSIONS = IMAGE_EXTENSIONS | VIDEO_EXTENSIONS
_MEDIA_AUTO_INSTALL_ATTEMPTED = False
_SEGMENTATION_AUTO_INSTALL_ATTEMPTED = False


@dataclass
class VisualIngestionResult:
    """Structured visual context extracted from an attached image or video."""

    image_id: str
    summary: str
    scene_graph: dict[str, Any] = field(default_factory=dict)
    composition: dict[str, Any] = field(default_factory=dict)
    lighting: dict[str, Any] = field(default_factory=dict)
    shadows: dict[str, Any] = field(default_factory=dict)
    materials: list[dict[str, Any]] = field(default_factory=list)
    color_palette: list[str] = field(default_factory=list)
    camera_spec: dict[str, Any] = field(default_factory=dict)
    cinematography: dict[str, Any] = field(default_factory=dict)
    rendering_spec: dict[str, Any] = field(default_factory=dict)
    production_context: dict[str, Any] = field(default_factory=dict)
    regions: list[dict[str, Any]] = field(default_factory=list)
    art_ontology_matches: dict[str, Any] = field(default_factory=dict)
    possible_tasks: list[str] = field(default_factory=list)
    uncertainties: list[str] = field(default_factory=list)
    confidence: float = 0.45
    media_type: str = "image"
    evidence: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "image_id": self.image_id,
            "summary": self.summary,
            "scene_graph": self.scene_graph,
            "composition": self.composition,
            "lighting": self.lighting,
            "shadows": self.shadows,
            "materials": self.materials,
            "color_palette": self.color_palette,
            "camera_spec": self.camera_spec,
            "cinematography": self.cinematography,
            "rendering_spec": self.rendering_spec,
            "production_context": self.production_context,
            "regions": self.regions,
            "art_ontology_matches": self.art_ontology_matches,
            "possible_tasks": self.possible_tasks,
            "uncertainties": self.uncertainties,
            "confidence": self.confidence,
            "media_type": self.media_type,
            "evidence": self.evidence,
        }


@dataclass
class ImageEditResult:
    """Files generated by a local image edit or derived-map operation."""

    source_path: str
    operation: str
    files_created: list[str] = field(default_factory=list)
    artifacts: list[dict[str, Any]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source_path": self.source_path,
            "operation": self.operation,
            "files_created": self.files_created,
            "artifacts": self.artifacts,
            "warnings": self.warnings,
        }


ART_ONTOLOGY: dict[str, dict[str, Any]] = {
    "flat lighting": {
        "concepts": [
            "insufficient value separation",
            "weak key-to-fill ratio",
            "limited directional lighting",
            "poor subject-background separation",
        ],
        "tool_terms": {
            "unreal": [
                "Reduce Skylight intensity",
                "Increase DirectionalLight key intensity",
                "Add RectLight / PointLight rim light",
                "Adjust PostProcessVolume Exposure min/max EV100",
            ],
            "maya": [
                "Adjust Arnold key-to-fill light ratio",
                "Add a rim light with cooler temperature",
                "Enable raytraced shadows on the main light",
            ],
        },
    },
    "shadow looks floaty": {
        "concepts": [
            "weak contact shadow",
            "excessive shadow bias",
            "ambient occlusion missing",
            "object-ground separation",
        ],
        "tool_terms": {
            "unreal": [
                "Increase Contact Shadow Length",
                "Use Virtual Shadow Maps if appropriate",
                "Adjust distance-field ambient occlusion",
                "Reduce shadow slope bias carefully",
            ],
            "maya": [
                "Inspect Arnold light radius and shadow softness",
                "Enable or inspect ambient occlusion AOV",
                "Check render shadow bias settings",
            ],
        },
    },
    "silhouette unreadable": {
        "concepts": [
            "poor shape language",
            "background intersection",
            "insufficient rim lighting separation",
            "busy background noise",
        ],
        "tool_terms": {
            "unreal": [
                "Add rim or kick light behind the character",
                "Use depth of field or value separation on the background",
                "Darken or simplify background material values",
            ],
            "maya": [
                "Adjust camera focal length and background separation",
                "Add a cool backlight for silhouette separation",
            ],
        },
    },
    "lens focal length": {
        "concepts": ["perspective distortion", "lens compression", "field of view"],
        "tool_terms": {
            "unreal": [
                "Set CineCameraComponent focal length",
                "Set aperture only after composition is locked",
            ],
            "maya": [
                "Set camera focal length attribute",
                "Enable depth of field only when it supports the shot",
            ],
        },
    },
}


CAMERA_SETTING_GUIDE: dict[str, dict[str, Any]] = {
    "lens_focal_length": {
        "triggers": ("lens", "focal", "focal length", "wide angle", "telephoto", "zoom", "fov", "field of view"),
        "why": "Focal length and FOV control perspective exaggeration, compression, and how much scene context is visible.",
        "user_checks": [
            "Choose wide lenses for environment context, medium lenses for natural character work, and longer lenses for compression or portrait-style framing.",
            "Lock composition before tuning depth of field, because lens changes alter framing and perceived depth.",
        ],
        "dcc_controls": {
            "unreal": ["CineCameraActor > Current Focal Length", "Filmback Sensor Width/Height", "CameraComponent Field Of View"],
            "maya": ["cameraShape.focalLength", "cameraShape.horizontalFilmAperture", "cameraShape.verticalFilmAperture"],
            "blender": ["Camera > Lens > Focal Length", "Camera > Sensor Fit", "Camera > Field of View"],
        },
    },
    "aperture_depth_of_field": {
        "triggers": ("aperture", "f-stop", "fstop", "depth of field", "dof", "bokeh", "focus distance", "rack focus"),
        "why": "Aperture and focus distance control subject separation, blur strength, and scene readability.",
        "user_checks": [
            "Set focus distance on the subject or tracked point before lowering f-stop.",
            "Use shallow depth of field only after confirming the important silhouette and action remain readable.",
        ],
        "dcc_controls": {
            "unreal": ["CineCameraComponent > Current Aperture", "Focus Settings > Manual Focus Distance", "Draw Debug Focus Plane"],
            "maya": ["cameraShape.depthOfField", "cameraShape.focusDistance", "cameraShape.fStop"],
            "blender": ["Camera > Depth of Field", "Focus Object/Distance", "F-Stop"],
        },
    },
    "exposure_shutter_iso": {
        "triggers": ("exposure", "iso", "shutter", "motion blur", "overexposed", "underexposed", "clipping", "highlight"),
        "why": "Exposure and shutter settings affect value range, clipped highlights, crushed shadows, and motion readability.",
        "user_checks": [
            "Check highlight clipping and shadow crushing before applying a creative grade.",
            "For tracking or mocap source, prefer stable exposure and limited motion blur over cinematic blur.",
        ],
        "dcc_controls": {
            "unreal": ["Post Process > Exposure Compensation", "CineCameraActor > Shutter Speed/ISO where available", "Movie Render Queue > Motion Blur"],
            "maya": ["Arnold camera exposure controls", "Render Settings > Motion Blur", "Color Management/View Transform"],
            "blender": ["Render > Motion Blur", "Color Management > Exposure", "Camera/Scene exposure settings"],
        },
    },
    "framing_aspect_resolution": {
        "triggers": ("framing", "composition", "aspect", "resolution", "safe frame", "overscan", "rule of thirds"),
        "why": "Framing, aspect, and output resolution define what the viewer can inspect and what gets cropped in delivery.",
        "user_checks": [
            "Set output aspect and resolution before final camera placement.",
            "Enable safe frame or film gate overlays when matching plates, UI captures, or editorial references.",
        ],
        "dcc_controls": {
            "unreal": ["Camera Preview", "Filmback preset", "Output Resolution/Movie Render Queue"],
            "maya": ["Resolution Gate", "Film Gate", "Render Settings > Image Size"],
            "blender": ["Camera Passepartout", "Output Properties > Resolution", "Safe Areas"],
        },
    },
    "clipping_camera_rig": {
        "triggers": ("near clip", "far clip", "clipping", "camera rig", "camera shake", "stabilize", "stabilization", "jitter"),
        "why": "Clip planes, rig hierarchy, and stabilization determine whether the camera is usable in tight scenes and moving shots.",
        "user_checks": [
            "Set near clip low enough for close props without causing depth precision artifacts.",
            "For video or tracked shots, check whether camera shake is intentional, stabilizable, or harmful to tracking.",
        ],
        "dcc_controls": {
            "unreal": ["CameraComponent > Near Clip Plane where exposed", "Spring Arm collision/probe settings", "Sequencer camera shake tracks"],
            "maya": ["cameraShape.nearClipPlane", "cameraShape.farClipPlane", "Camera rig/group constraints"],
            "blender": ["Camera > Clipping Start/End", "Constraints", "Motion tracking stabilization"],
        },
    },
    "matchmove_tracking": {
        "triggers": ("matchmove", "match move", "camera solve", "camera track", "tracking solve", "plate", "undistort", "lens distortion"),
        "why": "Matchmove quality depends on stable lens assumptions, visible track features, distortion handling, and known scene scale.",
        "user_checks": [
            "Record or estimate focal length, sensor size, frame rate, and lens distortion before solving.",
            "Track high-contrast features across the full frame and validate the solve with a ground or grid object.",
        ],
        "dcc_controls": {
            "unreal": ["Sequencer camera import", "Camera Cuts track", "Lens distortion/calibration workflow"],
            "maya": ["Camera Sequencer", "Image Plane", "cameraShape focal/aperture settings"],
            "blender": ["Movie Clip Editor > Tracking", "Camera Solver", "Lens Distortion"],
        },
    },
}


def collect_visual_media_paths(context: Any) -> list[str]:
    """Collect image/video paths from RequestContext fields and attachment text."""
    paths: list[str] = []
    for value in getattr(context, "attached_images", ()) or ():
        _append_visual_path(paths, value)

    extras = getattr(context, "extras", {}) or {}
    for key in ("attached_images", "attached_videos", "attached_files", "visual_media_paths"):
        for value in extras.get(key) or ():
            _append_visual_path(paths, value)

    text = str(getattr(context, "text", "") or "")
    for match in re.finditer(
        r"(?im)^\s*(?:File|Image|Video):\s*(.+?\.(?:png|jpe?g|gif|webp|bmp|tiff?|mp4|mov|avi|mkv|webm|m4v))\s*$",
        text,
    ):
        _append_visual_path(paths, match.group(1).strip())
    for match in re.finditer(
        r"(?i)([A-Za-z]:[^\n\r<>|?*\"]+?\.(?:png|jpe?g|gif|webp|bmp|tiff?|mp4|mov|avi|mkv|webm|m4v))",
        text,
    ):
        _append_visual_path(paths, match.group(1).strip())

    unique: list[str] = []
    seen: set[str] = set()
    for raw in paths:
        key = raw.replace("\\", "/").lower()
        if key not in seen:
            seen.add(key)
            unique.append(raw)
    return unique


def is_visual_media_path(path: str) -> bool:
    return Path(str(path)).suffix.lower() in VISUAL_MEDIA_EXTENSIONS


def is_image_edit_request(prompt_text: str) -> bool:
    """Return True when the user asks to create/edit derived imagery."""
    lower = str(prompt_text or "").lower()
    if not any(term in lower for term in ("create", "generate", "make", "convert", "extract", "edit", "derive", "build")):
        return False
    return any(
        term in lower
        for term in (
            "normal map", "depth map", "height map", "bump map", "roughness map",
            "ao map", "ambient occlusion", "cavity map", "edge map", "mask",
            "alpha map", "luma mask", "grayscale", "palette", "texture map",
            "crop", "resize", "background", "remove background", "transparent",
            "semantic cutout", "object cutout", "person cutout", "subject cutout",
            "channel pack", "orm", "rma", "format", "jpg", "jpeg", "webp",
            "color correct", "contrast", "brightness", "lut", "seamless",
            "tile", "contact sheet", "before after", "before/after",
        )
    )


def requested_image_edit_operations(prompt_text: str) -> list[str]:
    """Map prompt text to local image edit operations."""
    lower = str(prompt_text or "").lower()
    operations: list[str] = []
    if "normal" in lower:
        operations.append("normal_map")
    if "depth" in lower:
        operations.append("depth_map")
    if "height" in lower or "bump" in lower:
        operations.append("height_map")
    if "roughness" in lower:
        operations.append("roughness_map")
    if "ao" in lower or "ambient occlusion" in lower:
        operations.append("ao_map")
    if "cavity" in lower:
        operations.append("cavity_map")
    if "edge" in lower:
        operations.append("edge_map")
    if "alpha" in lower or "mask" in lower or "luma mask" in lower:
        operations.append("luma_mask")
    if "grayscale" in lower:
        operations.append("grayscale")
    if "palette" in lower:
        operations.append("palette_swatch")
    if "crop" in lower:
        operations.append("center_crop")
    if "resize" in lower or re.search(r"\b\d{2,5}\s*x\s*\d{2,5}\b", lower):
        operations.append("resize")
    wants_semantic_cutout = (
        "semantic" in lower
        or "object cutout" in lower
        or "person cutout" in lower
        or "subject cutout" in lower
        or "segmentation" in lower
    )
    if wants_semantic_cutout and ("background" in lower or "cutout" in lower or "transparent" in lower):
        operations.append("semantic_cutout")
    elif "background" in lower or "transparent" in lower:
        operations.append("background_mask")
    if "channel pack" in lower or re.search(r"\b(?:orm|rma)\b", lower):
        operations.append("channel_pack_orm")
    if "format" in lower or any(ext in lower for ext in ("jpg", "jpeg", "webp")):
        operations.append("format_convert")
    if "color correct" in lower or "brightness" in lower or "contrast" in lower or "lut" in lower:
        operations.append("color_correct")
    if "seamless" in lower or "tile" in lower:
        operations.append("seamless_tile")
    if "contact sheet" in lower:
        operations.append("contact_sheet")
    if "before after" in lower or "before/after" in lower or "comparison" in lower:
        operations.append("before_after")
    if not operations and is_image_edit_request(prompt_text):
        operations = ["depth_map", "normal_map", "edge_map"]
    return _unique_text(operations)


def generate_image_edit_artifacts(
    source_path: str,
    prompt_text: str = "",
    output_dir: str | Path = "",
) -> ImageEditResult:
    """Generate local derived image maps from an attached still image."""
    source = Path(str(source_path or "")).expanduser()
    operations = requested_image_edit_operations(prompt_text)
    result = ImageEditResult(source_path=str(source), operation=",".join(operations))
    if source.suffix.lower() not in IMAGE_EXTENSIONS:
        result.warnings.append("Derived image edits currently require a still image input.")
        return result

    try:
        from PIL import Image, ImageChops, ImageEnhance, ImageFilter, ImageOps
    except Exception as exc:
        result.warnings.append(f"Pillow is unavailable: {exc}")
        return result

    try:
        with Image.open(source) as opened:
            image = opened.convert("RGB")
    except Exception as exc:
        result.warnings.append(f"Could not decode source image: {exc}")
        return result

    target_dir = _resolve_image_edit_output_dir(source, output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    base = re.sub(r"[^A-Za-z0-9_.-]+", "_", source.stem).strip("._") or "image"
    luma = ImageOps.grayscale(image)
    luma_equalized = ImageOps.autocontrast(luma)

    for operation in operations:
        output_suffix = _operation_output_suffix(operation, prompt_text)
        output = target_dir / f"{base}_{operation}{output_suffix}"
        if operation == "normal_map":
            _normal_map_from_height(luma_equalized).save(output)
            description = "Tangent-style normal map estimated from luminance gradients."
        elif operation == "depth_map":
            ImageOps.autocontrast(luma).save(output)
            description = "Depth/value map estimated from image luminance."
        elif operation == "height_map":
            luma_equalized.save(output)
            description = "Height/bump source estimated from autocontrasted luminance."
        elif operation == "roughness_map":
            ImageOps.invert(ImageOps.autocontrast(luma)).save(output)
            description = "Roughness-style map estimated from inverted luminance."
        elif operation == "ao_map":
            shadow = ImageOps.invert(ImageOps.autocontrast(luma.filter(ImageFilter.GaussianBlur(3))))
            shadow.save(output)
            description = "AO-style broad shadow mask estimated from blurred luminance."
        elif operation == "cavity_map":
            edges = luma.filter(ImageFilter.FIND_EDGES)
            ImageOps.autocontrast(edges).save(output)
            description = "Cavity/edge detail map estimated from local luminance changes."
        elif operation == "edge_map":
            ImageOps.autocontrast(luma.filter(ImageFilter.FIND_EDGES)).save(output)
            description = "High-contrast edge map."
        elif operation == "luma_mask":
            mask = luma.point(lambda value: 255 if value >= 128 else 0)
            mask.save(output)
            description = "Binary alpha/luma mask using a midpoint threshold."
        elif operation == "grayscale":
            luma.save(output)
            description = "Plain grayscale luminance image."
        elif operation == "palette_swatch":
            _palette_swatch_image(_extract_palette(image)).save(output)
            description = "Palette swatch strip from measured dominant colors."
        elif operation == "center_crop":
            _center_crop_image(image, prompt_text).save(output)
            description = "Centered crop generated from the source image."
        elif operation == "resize":
            _resize_image(image, prompt_text).save(output)
            description = "Resized image generated from requested or default dimensions."
        elif operation == "background_mask":
            _background_removed_preview(image).save(output)
            description = "Transparent preview using border-color/luma based background masking."
        elif operation == "semantic_cutout":
            cutout, warning = _semantic_cutout_image(image)
            cutout.save(output)
            description = "Semantic/model-backed cutout when rembg is available; deterministic mask fallback otherwise."
            if warning:
                result.warnings.append(warning)
        elif operation == "channel_pack_orm":
            _channel_pack_orm(image, luma).save(output)
            description = "ORM-style packed texture: R=AO estimate, G=roughness estimate, B=metallic placeholder."
        elif operation == "format_convert":
            converted = image
            if output.suffix.lower() in {".jpg", ".jpeg"}:
                converted = image.convert("RGB")
            converted.save(output)
            description = f"Format-converted image ({output.suffix.lower().lstrip('.')})."
        elif operation == "color_correct":
            _color_correct_image(image, prompt_text).save(output)
            description = "Basic color correction using requested/default brightness, contrast, and saturation adjustments."
        elif operation == "seamless_tile":
            _seamless_tile_preview(image).save(output)
            description = "Seamless-tile preview using offset-and-blend edge wrapping."
        elif operation == "contact_sheet":
            _contact_sheet([image], [source.name]).save(output)
            description = "Contact sheet for attached/generated image review."
        elif operation == "before_after":
            _before_after_image(image, _color_correct_image(image, prompt_text)).save(output)
            description = "Before/after comparison preview."
        else:
            result.warnings.append(f"Unsupported image edit operation: {operation}")
            continue
        result.files_created.append(str(output))
        result.artifacts.append(
            {
                "type": operation,
                "path": str(output),
                "description": description,
                "source_path": str(source),
            }
        )

    return result


def analyze_image_art_context(image_id_or_path: str, prompt_text: str = "") -> VisualIngestionResult:
    """Analyze an attached image or video using measured local evidence."""
    path = Path(str(image_id_or_path or "")).expanduser()
    suffix = path.suffix.lower()
    if suffix in VIDEO_EXTENSIONS:
        return analyze_video_context(str(path), prompt_text)
    if suffix not in IMAGE_EXTENSIONS:
        return _unsupported_media_result(str(image_id_or_path), "unknown")

    try:
        from PIL import Image, ImageStat
    except Exception as exc:
        return _unsupported_media_result(str(path), "image", f"Pillow is unavailable: {exc}")

    try:
        with Image.open(path) as opened:
            frame_count = int(getattr(opened, "n_frames", 1) or 1)
            image = opened.convert("RGB")
    except Exception as exc:
        return _unsupported_media_result(str(path), "image", f"Could not decode image: {exc}")

    thumb = image.copy()
    thumb.thumbnail((256, 256))
    width, height = image.size
    stat = ImageStat.Stat(thumb.convert("L"))
    mean_luma = float(stat.mean[0])
    contrast = float(stat.stddev[0])
    palette = _extract_palette(thumb)
    brightest_region = _brightest_region(thumb)
    dark_ratio = _threshold_ratio(thumb, below=48)
    bright_ratio = _threshold_ratio(thumb, above=208)
    edge_density = _edge_density(thumb)
    aspect = width / max(1, height)
    ontology_matches, possible_tasks = _ontology_prompt_matches(prompt_text)
    possible_tasks.extend(
        task for task in _camera_intent_tasks(prompt_text, "image") if task not in possible_tasks
    )

    if not possible_tasks:
        possible_tasks = _suggest_tasks(mean_luma, contrast, dark_ratio, edge_density)

    composition = {
        "rule_of_thirds": "Not semantically inferred; use visual review for subject placement.",
        "silhouette_readability": _silhouette_readability(contrast, edge_density),
        "depth_layering": ["Not semantically inferred from local pixel analysis"],
        "focal_point": f"Brightest measured region: {brightest_region}",
        "eye_flow": "Not semantically inferred without a vision model.",
        "aspect_ratio": round(aspect, 3),
        "resolution": f"{width}x{height}",
    }
    lighting = {
        "key_light": {
            "direction": f"Estimated from brightest value region: {brightest_region}",
            "quality": _contrast_label(contrast),
            "color": f"Dominant swatch {palette[0] if palette else 'unknown'}",
            "intensity": _brightness_label(mean_luma),
        },
        "fill_light": {"direction": "Not directly inferred", "quality": "Unknown", "color": "Unknown"},
        "rim_light": {"present": "Unknown from baseline pixel analysis", "direction": "Unknown"},
        "ambient": f"Mean luma {mean_luma:.1f}/255; bright pixel ratio {bright_ratio:.1%}",
    }
    shadows = {
        "cast_shadow_direction": "Not directly inferred from a single still image.",
        "contact_shadows": "Requires semantic/object grounding.",
        "penumbra_softness": _contrast_label(contrast),
        "ambient_occlusion": f"Dark pixel ratio {dark_ratio:.1%}",
        "artifacts_detected": [],
    }
    camera = {
        "estimated_focal_length": "Unknown; cannot be measured reliably from pixels alone.",
        "estimated_aperture": "Unknown; cannot be measured reliably from pixels alone.",
        "bokeh_style": "Unknown",
        "dutch_angle": "Unknown",
        "sensor_size": "Unknown",
    }
    rendering = {
        "estimated_engine": "Unknown; no engine-specific detector is active.",
        "features_detected": [],
        "production_type": "Still image" if frame_count <= 1 else "Animated image",
    }
    evidence = {
        "path": str(path),
        "exists": path.exists(),
        "suffix": suffix,
        "width": width,
        "height": height,
        "frame_count": frame_count,
        "mean_luma": round(mean_luma, 2),
        "contrast_stddev": round(contrast, 2),
        "dark_pixel_ratio": round(dark_ratio, 4),
        "bright_pixel_ratio": round(bright_ratio, 4),
        "edge_density": round(edge_density, 4),
    }
    camera["settings_profile"] = _camera_settings_profile(prompt_text, "image", evidence)

    summary = (
        f"Measured {width}x{height} image ({suffix.lstrip('.')}) with "
        f"{_brightness_label(mean_luma).lower()} overall value, "
        f"{_contrast_label(contrast).lower()} contrast, and palette {', '.join(palette[:4])}."
    )
    uncertainties = [
        "No semantic vision model is active, so object identity, exact DCC, material type, focal length, and contact-shadow quality are not asserted.",
        "Lighting direction is estimated from value distribution, not from a physical scene solve.",
    ]
    if frame_count > 1:
        uncertainties.append("Animated image analysis uses the first decoded frame for pixel metrics.")

    return VisualIngestionResult(
        image_id=str(path),
        summary=summary,
        scene_graph={"objects": [], "note": "Object detection is not available in the local baseline."},
        composition=composition,
        lighting=lighting,
        shadows=shadows,
        materials=[
            {
                "name": "Unknown material regions",
                "type": "Not semantically inferred",
                "roughness": "Unknown",
                "metallic": "Unknown",
            }
        ],
        color_palette=palette,
        camera_spec=camera,
        cinematography={"shot_type": "Unknown", "camera_height": "Unknown"},
        rendering_spec=rendering,
        production_context={"source": "attached_media", "path": str(path)},
        art_ontology_matches=ontology_matches,
        possible_tasks=possible_tasks,
        uncertainties=uncertainties,
        confidence=0.48,
        media_type="image",
        evidence=evidence,
    )


def analyze_video_context(video_path: str, prompt_text: str = "") -> VisualIngestionResult:
    """Analyze a video attachment by sampling frames when a decoder is available."""
    path = Path(str(video_path or "")).expanduser()
    suffix = path.suffix.lower()
    exists = path.exists()
    size_bytes = path.stat().st_size if exists and path.is_file() else 0
    ontology_matches, possible_tasks = _ontology_prompt_matches(prompt_text)
    video_intent_tasks = _video_intent_tasks(prompt_text)
    possible_tasks.extend(task for task in video_intent_tasks if task not in possible_tasks)
    possible_tasks.extend(
        task for task in _camera_intent_tasks(prompt_text, "video") if task not in possible_tasks
    )

    sampled_frames, decoder_note = _extract_video_sample_frames(path)
    frame_results = [
        analyze_image_art_context(str(frame_path), prompt_text)
        for frame_path in sampled_frames
        if frame_path.exists()
    ]
    if frame_results:
        mean_lumas = [
            float(result.evidence.get("mean_luma", 0))
            for result in frame_results
            if result.evidence
        ]
        contrasts = [
            float(result.evidence.get("contrast_stddev", 0))
            for result in frame_results
            if result.evidence
        ]
        palette = _dedupe_palette(
            color
            for result in frame_results
            for color in result.color_palette
        )
        avg_luma = sum(mean_lumas) / max(1, len(mean_lumas))
        avg_contrast = sum(contrasts) / max(1, len(contrasts))
        luma_span = max(mean_lumas) - min(mean_lumas) if mean_lumas else 0.0
        if not possible_tasks:
            possible_tasks = _suggest_video_tasks(avg_luma, avg_contrast, luma_span)
        evidence = {
            "path": str(path),
            "exists": exists,
            "suffix": suffix,
            "size_bytes": size_bytes,
            "decoder": decoder_note,
            "sampled_frame_count": len(frame_results),
            "sampled_frames": [str(frame_path) for frame_path in sampled_frames],
            "average_mean_luma": round(avg_luma, 2),
            "average_contrast_stddev": round(avg_contrast, 2),
            "frame_luma_span": round(luma_span, 2),
        }
        camera = {
            "estimated_focal_length": "Unknown; cannot be measured reliably from sampled pixels alone.",
            "estimated_aperture": "Unknown; cannot be measured reliably from sampled pixels alone.",
            "motion": "Sampled frames available; optical-flow/motion tracking is not implemented.",
            "settings_profile": _camera_settings_profile(prompt_text, "video", evidence),
        }
        return VisualIngestionResult(
            image_id=str(path),
            summary=(
                f"Sampled {len(frame_results)} frame(s) from {path.name}; "
                f"average value is {_brightness_label(avg_luma).lower()}, "
                f"average contrast is {_contrast_label(avg_contrast).lower()}, "
                f"and frame-to-frame value change is {luma_span:.1f}/255."
            ),
            scene_graph={"objects": [], "note": "Object detection is not available in the local baseline."},
            composition={
                "temporal_readability": _temporal_readability(avg_contrast, luma_span),
                "sampled_frames": len(frame_results),
                "representative_frame_resolution": frame_results[0].composition.get("resolution", "unknown"),
            },
            lighting={
                "key_light": {
                    "direction": "Estimated per sampled frame from brightest value regions.",
                    "quality": _contrast_label(avg_contrast),
                    "color": f"Dominant sampled swatch {palette[0] if palette else 'unknown'}",
                    "intensity": _brightness_label(avg_luma),
                },
                "fill_light": {"direction": "Not directly inferred", "quality": "Unknown", "color": "Unknown"},
                "rim_light": {"present": "Unknown from baseline pixel analysis", "direction": "Unknown"},
                "ambient": f"Average sampled luma {avg_luma:.1f}/255",
            },
            shadows={
                "cast_shadow_direction": "Not directly inferred from sampled frames.",
                "contact_shadows": "Requires semantic/object grounding.",
                "penumbra_softness": _contrast_label(avg_contrast),
                "ambient_occlusion": "Estimated only through dark-value ratios in sampled frames.",
                "artifacts_detected": [],
            },
            materials=[],
            color_palette=palette,
            camera_spec=camera,
            cinematography={"shot_type": "Unknown", "temporal_analysis": "Sampled frame value analysis"},
            rendering_spec={"estimated_engine": "Unknown", "features_detected": [], "production_type": "Video"},
            production_context={"source": "attached_video", "path": str(path), "size_bytes": size_bytes},
            art_ontology_matches=ontology_matches,
            possible_tasks=possible_tasks,
            uncertainties=[
                "Video analysis is based on sampled frames, not full-frame semantic tracking.",
                "Object identity, exact DCC, material type, focal length, and contact-shadow quality are not asserted.",
                decoder_note,
            ],
            confidence=0.4,
            media_type="video",
            evidence=evidence,
        )

    if not possible_tasks:
        possible_tasks = [
            "Install or configure a video decoder such as ffmpeg, imageio, or OpenCV so frames can be sampled.",
            "Attach representative still frames for immediate lighting, composition, or material critique.",
            "Review motion readability, camera stability, exposure consistency, and compression artifacts manually.",
        ]

    summary = (
        f"Video attachment detected ({suffix.lstrip('.') or 'unknown'}, {_format_bytes(size_bytes)}). "
        "Local frame decoding is not available in this baseline, so no frame-level visual claims were made."
    )
    evidence = {
        "path": str(path),
        "exists": exists,
        "suffix": suffix,
        "size_bytes": size_bytes,
        "decoder": decoder_note,
        "sampled_frame_count": 0,
    }
    return VisualIngestionResult(
        image_id=str(path),
        summary=summary,
        scene_graph={"objects": [], "note": "Video frame/object detection is not available locally."},
        composition={"temporal_readability": "Requires decoded frame sampling."},
        lighting={
            "key_light": {"direction": "Unknown", "quality": "Unknown", "color": "Unknown"},
            "fill_light": {"direction": "Unknown", "quality": "Unknown", "color": "Unknown"},
            "rim_light": {"present": "Unknown", "direction": "Unknown"},
            "ambient": "Unknown",
        },
        shadows={"contact_shadows": "Unknown", "artifacts_detected": []},
        materials=[],
        color_palette=[],
        camera_spec={
            "estimated_focal_length": "Unknown",
            "estimated_aperture": "Unknown",
            "motion": "Requires frame decoding or video metadata extraction.",
            "settings_profile": _camera_settings_profile(prompt_text, "video", evidence),
        },
        cinematography={"shot_type": "Unknown", "temporal_analysis": "Not decoded"},
        rendering_spec={"estimated_engine": "Unknown", "features_detected": [], "production_type": "Video"},
        production_context={"source": "attached_video", "path": str(path), "size_bytes": size_bytes},
        art_ontology_matches=ontology_matches,
        possible_tasks=possible_tasks,
        uncertainties=[
            decoder_note,
            "No sampled frames were available, so frame-level visual claims were not made.",
        ],
        confidence=0.22,
        media_type="video",
        evidence=evidence,
    )


def compare_visual_renders(ref_image_id: str, current_render_id: str) -> dict[str, Any]:
    """Compare two images using simple palette/value evidence when decodable."""
    ref = analyze_image_art_context(ref_image_id)
    cur = analyze_image_art_context(current_render_id)
    if ref.media_type != "image" or cur.media_type != "image":
        return {
            "reference_id": ref_image_id,
            "current_render_id": current_render_id,
            "ok": False,
            "reason": "Both inputs must be decodable images for local comparison.",
        }
    ref_e = ref.evidence
    cur_e = cur.evidence
    luma_delta = abs(float(ref_e.get("mean_luma", 0)) - float(cur_e.get("mean_luma", 0)))
    contrast_delta = abs(float(ref_e.get("contrast_stddev", 0)) - float(cur_e.get("contrast_stddev", 0)))
    palette_overlap = len(set(ref.color_palette[:5]) & set(cur.color_palette[:5])) / max(1, len(set(ref.color_palette[:5])))
    return {
        "reference_id": ref_image_id,
        "current_render_id": current_render_id,
        "ok": True,
        "value_structure_match": _score_from_delta(luma_delta, 128),
        "contrast_match": _score_from_delta(contrast_delta, 80),
        "palette_match": round(palette_overlap, 3),
        "differences": [
            {
                "category": "value",
                "description": f"Mean luma differs by {luma_delta:.1f}/255.",
                "suggested_dcc_action": "Adjust exposure or key/fill balance if this diverges from the reference.",
            },
            {
                "category": "contrast",
                "description": f"Contrast stddev differs by {contrast_delta:.1f}.",
                "suggested_dcc_action": "Tune fill, ambient light, or post-process contrast.",
            },
        ],
    }


def inspect_visual_region(
    image_id: str,
    bbox: tuple[float, float, float, float],
    label: str = "selected_region",
) -> dict[str, Any]:
    """Analyze a selected image region using measured color/value stats."""
    try:
        from PIL import Image, ImageStat

        with Image.open(image_id) as opened:
            image = opened.convert("RGB")
        width, height = image.size
        x1, y1, x2, y2 = bbox
        crop_box = (
            max(0, min(width, int(x1 * width))),
            max(0, min(height, int(y1 * height))),
            max(0, min(width, int(x2 * width))),
            max(0, min(height, int(y2 * height))),
        )
        crop = image.crop(crop_box)
        stat = ImageStat.Stat(crop.convert("L"))
        palette = _extract_palette(crop)
        mean_luma = float(stat.mean[0]) if stat.mean else 0.0
        contrast = float(stat.stddev[0]) if stat.stddev else 0.0
        analysis = {
            "dominant_colors": palette,
            "mean_luma": round(mean_luma, 2),
            "contrast_stddev": round(contrast, 2),
            "recommended_fix": _region_recommendation(mean_luma, contrast),
        }
    except Exception as exc:
        analysis = {"error": str(exc), "recommended_fix": "Could not decode selected region."}

    return {
        "image_id": image_id,
        "region_id": f"region_{int(bbox[0] * 100)}_{int(bbox[1] * 100)}",
        "bbox": list(bbox),
        "label": label,
        "region_analysis": analysis,
    }


def generate_visual_difference_heatmap(ref_image_id: str, render_image_id: str) -> dict[str, Any]:
    """Return local difference metrics; no rendered heatmap image is generated."""
    comparison = compare_visual_renders(ref_image_id, render_image_id)
    return {
        "reference_id": ref_image_id,
        "render_id": render_image_id,
        "diff_metrics": comparison,
        "heatmap_regions": [],
        "note": "Local baseline reports numeric differences only; heatmap raster generation is not implemented.",
    }


def extract_color_swatches_and_palette(image_id: str) -> dict[str, Any]:
    result = analyze_image_art_context(image_id)
    return {
        "image_id": image_id,
        "palette_swatches": [
            {"hex": color, "name": "Measured swatch", "ratio": "sampled", "type": "Image color"}
            for color in result.color_palette
        ],
        "material_curve_ready": False,
        "confidence": result.confidence,
    }


def match_reference_camera_rig(image_id: str, active_dcc: str = "unreal") -> dict[str, Any]:
    result = analyze_image_art_context(image_id)
    return {
        "image_id": image_id,
        "target_dcc": active_dcc,
        "matched_camera_spec": result.camera_spec,
        "dcc_command": "",
        "requires_manual_review": True,
        "reason": "Camera lens cannot be reliably solved from baseline pixel analysis.",
    }


def generate_3point_studio_light_rig(image_id: str, active_dcc: str = "unreal") -> dict[str, Any]:
    result = analyze_image_art_context(image_id)
    return {
        "image_id": image_id,
        "target_dcc": active_dcc,
        "lights": [],
        "dcc_command": "",
        "requires_manual_review": True,
        "measured_lighting": result.lighting,
    }


def audit_texel_density_and_stretching(image_id: str) -> dict[str, Any]:
    result = analyze_image_art_context(image_id)
    return {
        "image_id": image_id,
        "texel_density_target": "Unknown from image alone",
        "anomalies": [],
        "recommendation": "Use UV layout or DCC mesh data for texel-density and stretching audit.",
        "evidence": result.evidence,
    }


def evaluate_pose_silhouette_readability(image_id: str) -> dict[str, Any]:
    result = analyze_image_art_context(image_id)
    return {
        "image_id": image_id,
        "silhouette_score": result.evidence.get("edge_density", 0),
        "thumbnail_readability_128px": result.composition.get("silhouette_readability", "Unknown"),
        "key_features_visible": [],
        "potential_tangents": [],
        "requires_semantic_review": True,
    }


def compare_render_batch_against_concept(
    concept_art_id: str,
    render_image_ids: list[str],
) -> dict[str, Any]:
    comparisons = [compare_visual_renders(concept_art_id, render_id) for render_id in render_image_ids]
    return {
        "concept_art_id": concept_art_id,
        "total_renders_compared": len(render_image_ids),
        "comparisons": comparisons,
        "best_match_render": _best_match(render_image_ids, comparisons),
    }


def _append_visual_path(paths: list[str], value: Any) -> None:
    path = str(value or "").strip().strip("\"'")
    if path and is_visual_media_path(path):
        paths.append(path)


def _extract_video_sample_frames(path: Path, sample_count: int = 3) -> tuple[list[Path], str]:
    if not path.exists() or not path.is_file():
        return [], "Video file is missing or not readable."

    cv2_frames, cv2_note = _extract_video_frames_with_cv2(path, sample_count)
    if cv2_frames:
        return cv2_frames, cv2_note

    imageio_frames, imageio_note = _extract_video_frames_with_imageio(path, sample_count)
    if imageio_frames:
        return imageio_frames, imageio_note

    ffmpeg_frames, ffmpeg_note = _extract_video_frames_with_ffmpeg(path, sample_count)
    if ffmpeg_frames:
        return ffmpeg_frames, ffmpeg_note

    notes = [cv2_note, imageio_note, ffmpeg_note]
    return [], "No video frame decoder succeeded. " + " ".join(note for note in notes if note)


def _extract_video_frames_with_cv2(path: Path, sample_count: int) -> tuple[list[Path], str]:
    try:
        import cv2  # type: ignore
    except Exception:
        return [], "OpenCV is not installed."

    capture = cv2.VideoCapture(str(path))
    try:
        if not capture.isOpened():
            return [], "OpenCV could not open the video."
        frame_total = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
        if frame_total <= 0:
            positions = [0]
        else:
            positions = _sample_positions(frame_total, sample_count)
        output_dir = Path(tempfile.mkdtemp(prefix="tech_connector_video_frames_"))
        frames: list[Path] = []
        for index, frame_number in enumerate(positions):
            capture.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
            ok, frame = capture.read()
            if not ok:
                continue
            output_path = output_dir / f"frame_{index:02d}.png"
            cv2.imwrite(str(output_path), frame)
            frames.append(output_path)
        return frames, f"Sampled {len(frames)} frame(s) with OpenCV."
    finally:
        capture.release()


def _extract_video_frames_with_imageio(path: Path, sample_count: int) -> tuple[list[Path], str]:
    try:
        import imageio.v3 as iio  # type: ignore
        from PIL import Image
    except Exception:
        install_note = _ensure_media_python_dependencies()
        try:
            import imageio.v3 as iio  # type: ignore
            from PIL import Image
        except Exception as exc:
            return [], f"imageio is not installed or could not import after auto-install. {install_note} Import error: {exc}"

    output_dir = Path(tempfile.mkdtemp(prefix="tech_connector_video_frames_"))
    frames: list[Path] = []
    try:
        decoded_frames = []
        for frame in iio.imiter(path):
            decoded_frames.append(frame)
            if len(decoded_frames) >= 90:
                break
        if not decoded_frames:
            return [], "imageio decoded zero frames."
        positions = _sample_positions(len(decoded_frames), sample_count)
        for index, frame_number in enumerate(positions):
            frame = decoded_frames[frame_number]
            output_path = output_dir / f"frame_{index:02d}.png"
            Image.fromarray(frame).save(output_path)
            frames.append(output_path)
    except Exception as exc:
        return [], f"imageio could not sample frames: {exc}"
    return frames, f"Sampled {len(frames)} frame(s) with imageio."


def _extract_video_frames_with_ffmpeg(path: Path, sample_count: int) -> tuple[list[Path], str]:
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        try:
            import imageio_ffmpeg  # type: ignore

            ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
        except Exception:
            ffmpeg = ""
    if not ffmpeg:
        return [], "ffmpeg is not installed or not on PATH."

    output_dir = Path(tempfile.mkdtemp(prefix="tech_connector_video_frames_"))
    output_pattern = output_dir / "frame_%02d.png"
    command = [
        ffmpeg,
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        str(path),
        "-vf",
        f"thumbnail,scale=320:-1",
        "-frames:v",
        str(sample_count),
        str(output_pattern),
    ]
    try:
        subprocess.run(command, check=True, capture_output=True, text=True, timeout=30)
    except Exception as exc:
        return [], f"ffmpeg could not sample frames: {exc}"
    frames = sorted(output_dir.glob("frame_*.png"))
    return frames, f"Sampled {len(frames)} frame(s) with ffmpeg."


def _ensure_media_python_dependencies() -> str:
    """Install lightweight media decoder dependencies into the active Python."""
    global _MEDIA_AUTO_INSTALL_ATTEMPTED
    if _MEDIA_AUTO_INSTALL_ATTEMPTED:
        return "Auto-install was already attempted in this process."
    _MEDIA_AUTO_INSTALL_ATTEMPTED = True

    import os

    if os.environ.get("TECH_CONNECTOR_DISABLE_MEDIA_AUTO_INSTALL"):
        return "Auto-install disabled by TECH_CONNECTOR_DISABLE_MEDIA_AUTO_INSTALL."

    requirements = Path(__file__).resolve().parents[1] / "requirements" / "media.txt"
    if not requirements.exists():
        return f"Media requirements file not found: {requirements}"

    command = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "-r",
        str(requirements),
    ]
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=180,
        )
    except Exception as exc:
        return f"Auto-install failed to start: {exc}"

    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "").strip().replace("\n", " ")[:500]
        return f"Auto-install failed with exit code {completed.returncode}: {detail}"
    return f"Installed media dependencies into active Python: {sys.executable}"


def _ensure_segmentation_dependencies() -> str:
    """Install optional semantic cutout dependencies into the active Python."""
    global _SEGMENTATION_AUTO_INSTALL_ATTEMPTED
    if _SEGMENTATION_AUTO_INSTALL_ATTEMPTED:
        return "Segmentation auto-install was already attempted in this process."
    _SEGMENTATION_AUTO_INSTALL_ATTEMPTED = True

    import os

    if os.environ.get("TECH_CONNECTOR_DISABLE_SEGMENTATION_AUTO_INSTALL"):
        return "Auto-install disabled by TECH_CONNECTOR_DISABLE_SEGMENTATION_AUTO_INSTALL."

    requirements = Path(__file__).resolve().parents[1] / "requirements" / "segmentation.txt"
    if not requirements.exists():
        return f"Segmentation requirements file not found: {requirements}"

    command = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "-r",
        str(requirements),
    ]
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=300,
        )
    except Exception as exc:
        return f"Segmentation auto-install failed to start: {exc}"

    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "").strip().replace("\n", " ")[:500]
        return f"Segmentation auto-install failed with exit code {completed.returncode}: {detail}"
    return f"Installed segmentation dependencies into active Python: {sys.executable}"


def _sample_positions(frame_total: int, sample_count: int) -> list[int]:
    if frame_total <= 1:
        return [0]
    if sample_count <= 1:
        return [frame_total // 2]
    return [
        max(0, min(frame_total - 1, int(round(i * (frame_total - 1) / (sample_count - 1)))))
        for i in range(sample_count)
    ]


def _dedupe_palette(colors: Iterable[str], limit: int = 6) -> list[str]:
    unique: list[str] = []
    seen: set[str] = set()
    for color in colors:
        key = str(color).upper()
        if key in seen:
            continue
        seen.add(key)
        unique.append(key)
        if len(unique) >= limit:
            break
    return unique


def _resolve_image_edit_output_dir(source: Path, output_dir: str | Path = "") -> Path:
    if output_dir:
        return Path(output_dir)
    try:
        from tech_connector.models.constants import temp_output_path

        return temp_output_path(f"{source.stem}_maps", subdir="image_edits")
    except Exception:
        return source.parent / "tech_connector_image_edits"


def _normal_map_from_height(height_image: Any, strength: float = 2.5) -> Any:
    try:
        import numpy as np
        from PIL import Image

        height = np.asarray(height_image.convert("L"), dtype=np.float32) / 255.0
        gy, gx = np.gradient(height)
        nx = -gx * strength
        ny = -gy * strength
        nz = np.ones_like(height)
        length = np.sqrt(nx * nx + ny * ny + nz * nz)
        normal = np.dstack(
            (
                (nx / length * 0.5 + 0.5) * 255.0,
                (ny / length * 0.5 + 0.5) * 255.0,
                (nz / length * 0.5 + 0.5) * 255.0,
            )
        ).clip(0, 255).astype(np.uint8)
        return Image.fromarray(normal)
    except Exception:
        return _normal_map_from_height_without_numpy(height_image, strength)


def _normal_map_from_height_without_numpy(height_image: Any, strength: float = 2.5) -> Any:
    from PIL import Image

    height = height_image.convert("L")
    width, height_px = height.size
    pixels = height.load()
    output = Image.new("RGB", (width, height_px), (128, 128, 255))
    out = output.load()
    for y in range(height_px):
        for x in range(width):
            left = pixels[max(0, x - 1), y] / 255.0
            right = pixels[min(width - 1, x + 1), y] / 255.0
            up = pixels[x, max(0, y - 1)] / 255.0
            down = pixels[x, min(height_px - 1, y + 1)] / 255.0
            nx = -(right - left) * strength
            ny = -(down - up) * strength
            nz = 1.0
            length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
            out[x, y] = (
                int((nx / length * 0.5 + 0.5) * 255),
                int((ny / length * 0.5 + 0.5) * 255),
                int((nz / length * 0.5 + 0.5) * 255),
            )
    return output


def _palette_swatch_image(colors: list[str]) -> Any:
    from PIL import Image, ImageColor

    swatches = colors or ["#000000"]
    width = max(1, len(swatches)) * 64
    image = Image.new("RGB", (width, 64), "#000000")
    for index, color in enumerate(swatches):
        try:
            rgb = ImageColor.getrgb(color)
        except Exception:
            rgb = (0, 0, 0)
        for x in range(index * 64, (index + 1) * 64):
            for y in range(64):
                image.putpixel((x, y), rgb)
    return image


def _operation_output_suffix(operation: str, prompt_text: str = "") -> str:
    lower = str(prompt_text or "").lower()
    if operation == "format_convert":
        if "webp" in lower:
            return ".webp"
        if "jpg" in lower or "jpeg" in lower:
            return ".jpg"
    if operation == "background_mask":
        return ".png"
    return ".png"


def _requested_dimensions(prompt_text: str, default: tuple[int, int]) -> tuple[int, int]:
    match = re.search(r"\b(\d{2,5})\s*x\s*(\d{2,5})\b", str(prompt_text or ""), re.I)
    if not match:
        return default
    width = max(1, min(8192, int(match.group(1))))
    height = max(1, min(8192, int(match.group(2))))
    return width, height


def _center_crop_image(image: Any, prompt_text: str = "") -> Any:
    width, height = image.size
    target_w, target_h = _requested_dimensions(prompt_text, (min(width, height), min(width, height)))
    target_ratio = target_w / max(1, target_h)
    current_ratio = width / max(1, height)
    if current_ratio > target_ratio:
        crop_w = int(height * target_ratio)
        crop_h = height
    else:
        crop_w = width
        crop_h = int(width / target_ratio)
    left = max(0, (width - crop_w) // 2)
    top = max(0, (height - crop_h) // 2)
    cropped = image.crop((left, top, left + crop_w, top + crop_h))
    return cropped.resize((target_w, target_h)) if (target_w, target_h) != cropped.size else cropped


def _resize_image(image: Any, prompt_text: str = "") -> Any:
    width, height = image.size
    target = _requested_dimensions(prompt_text, (width, height))
    return image.resize(target)


def _background_removed_preview(image: Any) -> Any:
    from PIL import ImageChops, ImageFilter, ImageOps

    rgb = image.convert("RGB")
    width, height = rgb.size
    samples = [
        rgb.getpixel((0, 0)),
        rgb.getpixel((max(0, width - 1), 0)),
        rgb.getpixel((0, max(0, height - 1))),
        rgb.getpixel((max(0, width - 1), max(0, height - 1))),
    ]
    bg = tuple(int(sum(pixel[channel] for pixel in samples) / len(samples)) for channel in range(3))
    bg_image = rgb.copy()
    bg_image.paste(bg, (0, 0, width, height))
    diff = ImageChops.difference(rgb, bg_image).convert("L")
    alpha = ImageOps.autocontrast(diff).point(lambda value: 0 if value < 28 else 255)
    alpha = alpha.filter(ImageFilter.MedianFilter(3))
    rgba = rgb.convert("RGBA")
    rgba.putalpha(alpha)
    return rgba


def _prepare_segmentation_model_cache() -> str:
    """Point model downloads at a writable cache before rembg/pooch runs."""
    if os.environ.get("U2NET_HOME"):
        return ""

    candidate_roots: list[Path] = []
    configured = os.environ.get("TECH_CONNECTOR_MODEL_CACHE")
    if configured:
        candidate_roots.append(Path(configured))

    local_app_data = os.environ.get("LOCALAPPDATA")
    if local_app_data:
        candidate_roots.append(Path(local_app_data) / "TechConnector" / "models")

    xdg_cache = os.environ.get("XDG_CACHE_HOME")
    if xdg_cache:
        candidate_roots.append(Path(xdg_cache) / "tech_connector" / "models")

    candidate_roots.append(Path(tempfile.gettempdir()) / "TechConnector" / "models")
    candidate_roots.append(Path(__file__).resolve().parents[1] / ".media_models")

    for root in candidate_roots:
        try:
            target = root.expanduser() / "u2net"
            target.mkdir(parents=True, exist_ok=True)
            os.environ["U2NET_HOME"] = str(target)
            return ""
        except Exception:
            continue

    return "Could not prepare a writable segmentation model cache."


def _semantic_cutout_image(image: Any) -> tuple[Any, str]:
    """Return a model-backed cutout when rembg is available, otherwise fallback."""
    cache_note = _prepare_segmentation_model_cache()
    try:
        from rembg import remove  # type: ignore
    except Exception:
        install_note = _ensure_segmentation_dependencies()
        try:
            from rembg import remove  # type: ignore
        except Exception as exc:
            return (
                _background_removed_preview(image),
                (
                    "Semantic cutout backend is unavailable; used deterministic "
                    f"background mask fallback. {cache_note} {install_note} Import error: {exc}"
                ),
            )

    try:
        cutout = remove(image.convert("RGBA"))
        if hasattr(cutout, "convert"):
            return cutout.convert("RGBA"), ""
        return image.convert("RGBA"), "Semantic cutout backend returned an unsupported image object."
    except Exception as exc:
        return (
            _background_removed_preview(image),
            f"Semantic cutout failed at runtime; used deterministic background mask fallback. {cache_note} {exc}",
        )


def _channel_pack_orm(image: Any, luma: Any) -> Any:
    from PIL import Image, ImageFilter, ImageOps

    ao = ImageOps.invert(ImageOps.autocontrast(luma.filter(ImageFilter.GaussianBlur(3))))
    roughness = ImageOps.invert(ImageOps.autocontrast(luma))
    metallic = Image.new("L", image.size, 0)
    return Image.merge("RGB", (ao, roughness, metallic))


def _color_correct_image(image: Any, prompt_text: str = "") -> Any:
    from PIL import ImageEnhance, ImageOps

    lower = str(prompt_text or "").lower()
    corrected = image.convert("RGB")
    corrected = ImageOps.autocontrast(corrected)
    contrast = 1.15 if "contrast" in lower or "color correct" in lower or "lut" in lower else 1.0
    brightness = 1.08 if "bright" in lower else 1.0
    saturation = 1.12 if "color" in lower or "lut" in lower else 1.0
    corrected = ImageEnhance.Contrast(corrected).enhance(contrast)
    corrected = ImageEnhance.Brightness(corrected).enhance(brightness)
    corrected = ImageEnhance.Color(corrected).enhance(saturation)
    return corrected


def _seamless_tile_preview(image: Any) -> Any:
    from PIL import Image, ImageChops, ImageFilter

    rgb = image.convert("RGB")
    width, height = rgb.size
    offset = ImageChops.offset(rgb, width // 2, height // 2)
    softened = offset.filter(ImageFilter.GaussianBlur(2))
    return Image.blend(offset, softened, 0.35)


def _contact_sheet(images: list[Any], labels: list[str] | None = None) -> Any:
    from PIL import Image, ImageDraw

    labels = labels or ["" for _ in images]
    thumbs = []
    for image in images:
        thumb = image.convert("RGB").copy()
        thumb.thumbnail((160, 120))
        thumbs.append(thumb)
    if not thumbs:
        return Image.new("RGB", (320, 180), "#101010")
    width = 180 * len(thumbs)
    sheet = Image.new("RGB", (width, 160), "#101010")
    draw = ImageDraw.Draw(sheet)
    for index, thumb in enumerate(thumbs):
        x = index * 180 + 10
        sheet.paste(thumb, (x, 10))
        draw.text((x, 135), labels[index][:24], fill="#FFFFFF")
    return sheet


def _before_after_image(before: Any, after: Any) -> Any:
    from PIL import Image, ImageDraw

    left = before.convert("RGB").copy()
    right = after.convert("RGB").copy()
    left.thumbnail((320, 240))
    right.thumbnail((320, 240))
    width = left.width + right.width + 24
    height = max(left.height, right.height) + 32
    canvas = Image.new("RGB", (width, height), "#101010")
    canvas.paste(left, (8, 8))
    canvas.paste(right, (left.width + 16, 8))
    draw = ImageDraw.Draw(canvas)
    draw.text((8, height - 20), "Before", fill="#FFFFFF")
    draw.text((left.width + 16, height - 20), "After", fill="#FFFFFF")
    return canvas


def _unique_text(items: Iterable[str]) -> list[str]:
    unique: list[str] = []
    seen: set[str] = set()
    for item in items:
        key = item.casefold()
        if key in seen:
            continue
        seen.add(key)
        unique.append(item)
    return unique


def _extract_palette(image: Any, count: int = 5) -> list[str]:
    quantized = image.convert("RGB").quantize(colors=count, method=2)
    palette = quantized.getpalette() or []
    colors = quantized.getcolors(maxcolors=256) or []
    colors.sort(reverse=True)
    swatches: list[str] = []
    for _pixels, index in colors[:count]:
        offset = int(index) * 3
        if offset + 2 < len(palette):
            swatches.append("#%02X%02X%02X" % tuple(palette[offset : offset + 3]))
    return swatches


def _brightest_region(image: Any) -> str:
    gray = image.convert("L")
    width, height = gray.size
    regions = {
        "upper-left": (0, 0, width // 2, height // 2),
        "upper-right": (width // 2, 0, width, height // 2),
        "lower-left": (0, height // 2, width // 2, height),
        "lower-right": (width // 2, height // 2, width, height),
        "center": (width // 4, height // 4, width * 3 // 4, height * 3 // 4),
    }
    try:
        from PIL import ImageStat

        scores = {
            name: float(ImageStat.Stat(gray.crop(box)).mean[0])
            for name, box in regions.items()
            if box[2] > box[0] and box[3] > box[1]
        }
    except Exception:
        return "unknown"
    return max(scores, key=scores.get) if scores else "unknown"


def _threshold_ratio(image: Any, below: int | None = None, above: int | None = None) -> float:
    gray = image.convert("L")
    pixel_reader = getattr(gray, "get_flattened_data", None) or gray.getdata
    pixels = list(pixel_reader())
    if not pixels:
        return 0.0
    if below is not None:
        return sum(1 for value in pixels if value < below) / len(pixels)
    if above is not None:
        return sum(1 for value in pixels if value > above) / len(pixels)
    return 0.0


def _edge_density(image: Any) -> float:
    gray = image.convert("L")
    width, height = gray.size
    if width < 2 or height < 2:
        return 0.0
    pixels = gray.load()
    total = 0
    edges = 0
    for y in range(height - 1):
        for x in range(width - 1):
            dx = abs(int(pixels[x, y]) - int(pixels[x + 1, y]))
            dy = abs(int(pixels[x, y]) - int(pixels[x, y + 1]))
            if math.hypot(dx, dy) > 32:
                edges += 1
            total += 1
    return edges / max(1, total)


def _ontology_prompt_matches(prompt_text: str) -> tuple[dict[str, Any], list[str]]:
    lower_prompt = str(prompt_text or "").lower()
    matches = {}
    tasks = []
    for term, data in ART_ONTOLOGY.items():
        if term in lower_prompt or any(concept in lower_prompt for concept in data["concepts"]):
            matches[term] = data
            tasks.append(f"Review DCC settings related to '{term}'")
    return matches, tasks


def _camera_prompt_matches(prompt_text: str) -> dict[str, dict[str, Any]]:
    lower_prompt = str(prompt_text or "").lower()
    matches: dict[str, dict[str, Any]] = {}
    for key, data in CAMERA_SETTING_GUIDE.items():
        if any(trigger in lower_prompt for trigger in data.get("triggers", ())):
            matches[key] = data

    if "camera" in lower_prompt and not matches:
        for key in ("lens_focal_length", "framing_aspect_resolution", "exposure_shutter_iso"):
            matches[key] = CAMERA_SETTING_GUIDE[key]
    return matches


def _camera_settings_profile(prompt_text: str, media_type: str, evidence: dict[str, Any]) -> dict[str, Any]:
    matches = _camera_prompt_matches(prompt_text)
    if not matches:
        return {
            "requested": False,
            "note": "No explicit camera-settings request detected.",
            "matched_features": [],
            "settings_guidance": [],
            "dcc_controls": {},
            "validation_checks": [],
        }

    settings_guidance: list[dict[str, Any]] = []
    dcc_controls: dict[str, list[str]] = {}
    validation_checks: list[str] = []
    for key, data in matches.items():
        settings_guidance.append(
            {
                "feature": key,
                "why": data.get("why", ""),
                "checks": list(data.get("user_checks", ())),
            }
        )
        for dcc, controls in (data.get("dcc_controls") or {}).items():
            dcc_controls.setdefault(dcc, [])
            for control in controls:
                if control not in dcc_controls[dcc]:
                    dcc_controls[dcc].append(control)
        validation_checks.extend(check for check in data.get("user_checks", ()) if check not in validation_checks)

    if media_type == "video":
        validation_checks.extend(
            check
            for check in (
                "Scrub sampled frames for camera drift, handheld jitter, rolling shutter, and motion blur before tracking or mocap.",
                "Confirm frame rate and shutter/motion-blur assumptions before exporting to Unreal, Maya, Blender, or an editor.",
            )
            if check not in validation_checks
        )
    else:
        validation_checks.append("Use a camera overlay or safe frame to verify crop, subject placement, and final delivery aspect.")

    resolution = evidence.get("width") and evidence.get("height")
    measured_note = (
        f"Measured source resolution is {evidence.get('width')}x{evidence.get('height')}."
        if resolution
        else "Source resolution is not available from this media path."
    )

    return {
        "requested": True,
        "note": (
            "Camera settings cannot be solved exactly from pixels alone; this profile maps the prompt "
            "to practical controls and validation checks."
        ),
        "matched_features": list(matches.keys()),
        "settings_guidance": settings_guidance,
        "dcc_controls": dcc_controls,
        "validation_checks": validation_checks,
        "measured_context": measured_note,
    }


def _camera_intent_tasks(prompt_text: str, media_type: str) -> list[str]:
    profile = _camera_settings_profile(prompt_text, media_type, {})
    if not profile.get("requested"):
        return []
    tasks = [
        "Camera flow: lock output aspect/resolution, choose lens/FOV, set camera placement, then tune focus/exposure after composition is readable.",
        "Record the chosen camera settings so the shot can be reproduced or matched later.",
    ]
    for feature in profile.get("matched_features", []):
        label = feature.replace("_", " ")
        tasks.append(f"Review camera controls for {label}.")
    if media_type == "video":
        tasks.append("For video, check camera stability, shutter blur, frame rate, and exposure consistency before tracking or editing.")
    return _unique_text(tasks)


def _suggest_tasks(mean_luma: float, contrast: float, dark_ratio: float, edge_density: float) -> list[str]:
    tasks = ["Compare the measured palette and value range against the art target."]
    if mean_luma < 72:
        tasks.append("Check exposure and fill light; the image measures quite dark overall.")
    elif mean_luma > 190:
        tasks.append("Check exposure and highlight clipping; the image measures very bright overall.")
    if contrast < 32:
        tasks.append("Review value separation; measured contrast is low.")
    if dark_ratio > 0.35:
        tasks.append("Inspect crushed shadows and contact-shadow readability.")
    if edge_density < 0.02:
        tasks.append("Check silhouette readability at thumbnail size.")
    return tasks


def _suggest_video_tasks(avg_luma: float, avg_contrast: float, luma_span: float) -> list[str]:
    tasks = ["Review sampled frames for exposure consistency, motion readability, and composition drift."]
    if avg_luma < 72:
        tasks.append("Check whether the clip is underexposed across sampled frames.")
    elif avg_luma > 190:
        tasks.append("Check whether highlights are clipping across sampled frames.")
    if avg_contrast < 32:
        tasks.append("Review value separation; sampled frames measure low contrast.")
    if luma_span > 80:
        tasks.append("Inspect flicker or major exposure shifts between sampled frames.")
    return tasks


def _video_intent_tasks(prompt_text: str) -> list[str]:
    lower = str(prompt_text or "").lower()
    tasks: list[str] = []
    if "metahuman" in lower:
        tasks.extend(
            [
                "MetaHuman flow: confirm the clip is usable source footage, then create or select a MetaHuman Identity before solving performance data.",
                "Check face visibility, lighting stability, frame rate, and occlusions before sending the clip into MetaHuman Animator.",
                "After solve, bake to a Level Sequence or Control Rig pass and review mouth/eye drift against the sampled frames.",
            ]
        )
    if any(term in lower for term in ("mocap", "motion capture", "facial capture", "body capture")):
        tasks.extend(
            [
                "Mocap flow: classify whether this is facial, body, or mixed capture before choosing the solver.",
                "Check the clip for dropped frames, motion blur, framing changes, and landmark visibility before tracking.",
                "Plan a cleanup pass for solve drift, foot/face sliding, retarget scale, and final animation bake.",
            ]
        )
    if any(term in lower for term in ("tracking", "track", "tracker", "solve")):
        tasks.extend(
            [
                "Tracking flow: pick high-contrast landmarks or regions and verify they remain visible across sampled frames.",
                "Check for occlusions, cuts, heavy blur, or exposure shifts that can break point/planar tracking.",
                "Run a short test solve on a trimmed range before committing to the full clip.",
            ]
        )
    if any(term in lower for term in ("edit", "editing", "cut", "trim", "sequence", "timeline")):
        tasks.extend(
            [
                "Editing flow: identify start/end handles, bad frames, cuts, and whether the clip needs transcoding before DCC ingestion.",
                "Check exposure and color consistency across sampled frames before applying creative edits.",
                "Export an edit decision or trimmed source clip while preserving original frame rate for tracking/mocap workflows.",
            ]
        )
    return _unique_text(tasks)


def _temporal_readability(avg_contrast: float, luma_span: float) -> str:
    if avg_contrast < 32:
        return "Low sampled contrast may reduce motion and silhouette readability."
    if luma_span > 80:
        return "Large sampled value shifts may indicate flicker, cuts, or exposure instability."
    return "Sampled frame values are relatively stable; semantic motion review is still required."


def _silhouette_readability(contrast: float, edge_density: float) -> str:
    if contrast >= 56 and edge_density >= 0.04:
        return "Measured value contrast and edge density suggest readable silhouettes."
    if contrast < 32:
        return "Low measured contrast may reduce silhouette readability."
    return "Mixed; requires semantic review of the subject and background."


def _brightness_label(mean_luma: float) -> str:
    if mean_luma < 72:
        return "Dark"
    if mean_luma > 190:
        return "Bright"
    return "Mid-value"


def _contrast_label(contrast: float) -> str:
    if contrast < 28:
        return "Low contrast"
    if contrast > 72:
        return "High contrast"
    return "Moderate contrast"


def _region_recommendation(mean_luma: float, contrast: float) -> str:
    if mean_luma < 48:
        return "Region is very dark; inspect exposure, fill, or shadow crushing."
    if mean_luma > 220:
        return "Region is very bright; inspect highlight clipping or emissive intensity."
    if contrast < 20:
        return "Region has low contrast; check material/value separation."
    return "Region values are measurable; use semantic review for object-specific fixes."


def _score_from_delta(delta: float, max_delta: float) -> float:
    return round(max(0.0, min(1.0, 1.0 - (delta / max(1.0, max_delta)))), 3)


def _format_bytes(size_bytes: int) -> str:
    if size_bytes <= 0:
        return "unknown size"
    units = ["B", "KB", "MB", "GB"]
    value = float(size_bytes)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{size_bytes} B"


def _best_match(render_ids: list[str], comparisons: Iterable[dict[str, Any]]) -> str:
    best_id = ""
    best_score = -1.0
    for render_id, comparison in zip(render_ids, comparisons):
        if not comparison.get("ok"):
            continue
        score = (
            float(comparison.get("value_structure_match", 0))
            + float(comparison.get("contrast_match", 0))
            + float(comparison.get("palette_match", 0))
        ) / 3
        if score > best_score:
            best_id = render_id
            best_score = score
    return best_id


def _unsupported_media_result(media_ref: str, media_type: str, reason: str = "") -> VisualIngestionResult:
    return VisualIngestionResult(
        image_id=str(media_ref),
        summary=f"Could not analyze {media_type} media. {reason}".strip(),
        lighting={
            "key_light": {"direction": "Unknown", "quality": "Unknown", "color": "Unknown"},
            "fill_light": {"direction": "Unknown", "quality": "Unknown", "color": "Unknown"},
            "rim_light": {"present": "Unknown", "direction": "Unknown"},
        },
        shadows={"artifacts_detected": []},
        camera_spec={"estimated_focal_length": "Unknown", "estimated_aperture": "Unknown"},
        rendering_spec={"estimated_engine": "Unknown", "features_detected": []},
        production_context={"source": "unsupported_media", "path": str(media_ref)},
        possible_tasks=["Attach a supported image or video file for analysis."],
        uncertainties=[reason or "Unsupported or missing media."],
        confidence=0.0,
        media_type=media_type,
        evidence={"path": str(media_ref), "exists": Path(str(media_ref)).exists()},
    )
