# coding=utf-8
"""Gameplay Proof Contract Service for Tech Connector.

Redefines "done" for gameplay feature requests.

A feature is only complete when:
  1. Structural correctness  – compilation, reference resolution, no dead code.
  2. Runtime execution       – trigger fires, execution path is reached.
  3. Gameplay behavior       – state changes match the declared THEN-claims.
  4. Integration correctness – connected systems receive/respond correctly.
  5. Failure/edge handling   – invalid conditions fail safely.
  6. Evidence-backed proof   – every THEN-claim has an observable assertion.

Compilation alone satisfies milestone 1 only.

The central output of this service is a :class:`GameplayProofContract`
containing machine-checkable ``ProofClaim`` objects expressed as::

    WHEN  <trigger>
    AND   <precondition> (zero or more)
    THEN  <observable assertion>   → pass/fail/pending

Downstream services (planner, goal_gap_planning_service, progress service)
should consume the proof contract so that partial or unverified claims block
marking a task "done".
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from typing import Any


# ---------------------------------------------------------------------------
# Evidence levels - mirrors the 6-milestone ladder in the design doc.
# ---------------------------------------------------------------------------

EVIDENCE_LEVEL_LABELS = {
    1: "static_validation",          # Compiles, references resolve, no dead code
    2: "construction_validation",    # Instantiation, initialization, delegates bound
    3: "runtime_path_validation",    # Trigger fires, execution path reached, cleanup runs
    4: "gameplay_outcome_validation",# Observable state: HP changed, actor moved, UI updated
    5: "negative_edge_validation",   # Null ref, repeat activation, insufficient resource
    6: "regression_validation",      # Adjacent systems unbroken, no input/anim conflicts
}


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class ProofClaim:
    """One machine-checkable assertion.

    Instances are generated by :func:`extract_proof_claims_from_prompt`.

    Attributes
    ----------
    claim_id:
        Stable short identifier, e.g. ``"movement_mode_flying"``.
    when_trigger:
        The activating event or player input (e.g. ``"IA_Climb is pressed"``).
    preconditions:
        Zero or more AND-conditions that must be true before activation.
    then_assertion:
        The observable outcome that must be verified (e.g.
        ``"CharacterMovementComponent.MovementMode == MOVE_Flying"``).
    evidence_level:
        Minimum milestone (1–6) required to satisfy this claim.
    validation_method:
        How to gather evidence: ``"pil_log"``, ``"state_query"``,
        ``"automation_test"``, ``"screenshot"``, ``"runtime_assertion"``, etc.
    failure_modes:
        Known false-positive conditions that would make the feature *appear*
        to work while actually being disconnected or incomplete.
    status:
        ``"pending"`` / ``"passed"`` / ``"failed"`` / ``"untestable"``.
    evidence_observed:
        Human-readable log of what was actually observed during validation.
    """

    claim_id: str
    when_trigger: str
    preconditions: list[str] = field(default_factory=list)
    then_assertion: str = ""
    evidence_level: int = 3
    validation_method: str = "runtime_assertion"
    failure_modes: list[str] = field(default_factory=list)
    status: str = "pending"
    evidence_observed: str = ""
    evidence_origin: str = "model_inference"
    observation_spec: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def render_claim(self) -> str:
        """Render as a human-readable WHEN/AND/THEN block."""
        lines = [f"WHEN  {self.when_trigger}"]
        for cond in self.preconditions:
            lines.append(f"AND   {cond}")
        lines.append(f"THEN  {self.then_assertion}")
        lines.append(f"  evidence_level : {self.evidence_level} ({EVIDENCE_LEVEL_LABELS.get(self.evidence_level, '?')})")
        lines.append(f"  validate_via   : {self.validation_method}")
        lines.append(f"  status         : {self.status}")
        if self.evidence_observed:
            lines.append(f"  observed       : {self.evidence_observed}")
        if self.failure_modes:
            lines.append(f"  false-positives: {'; '.join(self.failure_modes)}")
        return "\n".join(lines)


@dataclass
class GameplayContract:
    """Behavioral contract derived deterministically from the prompt.

    This is the definition of done for the feature.

    Attributes
    ----------
    feature_name:
        Short label for the feature.
    trigger:
        What activates the feature (input, event, notify, state transition).
    preconditions:
        State that must be true before activation is accepted.
    runtime_behavior:
        What must happen while the feature is active.
    state_changes:
        Variables, components, tags, attributes, transforms that must change.
    player_visible_result:
        What the player sees, hears, or controls.
    completion_or_cancellation:
        What ends the feature and what state is restored.
    invalid_conditions:
        Inputs that should be rejected, and expected fail-safe behavior.
    integration_criteria:
        Which existing systems must receive or respond to the result.
    """

    feature_name: str
    trigger: str = ""
    preconditions: list[str] = field(default_factory=list)
    runtime_behavior: list[str] = field(default_factory=list)
    state_changes: list[str] = field(default_factory=list)
    player_visible_result: str = ""
    completion_or_cancellation: str = ""
    invalid_conditions: list[str] = field(default_factory=list)
    integration_criteria: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def render_contract(self) -> str:
        lines = [f"## Gameplay Contract: {self.feature_name}"]
        lines.append(f"**Trigger**: {self.trigger or '(not yet resolved)'}")
        if self.preconditions:
            lines.append("**Preconditions**:")
            for p in self.preconditions:
                lines.append(f"  - {p}")
        if self.runtime_behavior:
            lines.append("**Runtime Behavior**:")
            for b in self.runtime_behavior:
                lines.append(f"  - {b}")
        if self.state_changes:
            lines.append("**State Changes**:")
            for s in self.state_changes:
                lines.append(f"  - {s}")
        if self.player_visible_result:
            lines.append(f"**Player-Visible Result**: {self.player_visible_result}")
        if self.completion_or_cancellation:
            lines.append(f"**Completion/Cancellation**: {self.completion_or_cancellation}")
        if self.invalid_conditions:
            lines.append("**Invalid Conditions (must fail-safe)**:")
            for c in self.invalid_conditions:
                lines.append(f"  - {c}")
        if self.integration_criteria:
            lines.append("**Integration Criteria**:")
            for i in self.integration_criteria:
                lines.append(f"  - {i}")
        return "\n".join(lines)


@dataclass
class GameplayProofContract:
    """Full proof contract for a gameplay feature implementation request.

    Produced by :func:`build_gameplay_proof_contract` and consumed by
    downstream planners and progress services to determine whether the
    feature is truly done.

    Attributes
    ----------
    feature_name:
        Human-readable name of the feature being implemented.
    gameplay_contract:
        Behavioral specification (trigger, preconditions, state changes, …).
    proof_claims:
        Machine-checkable WHEN/AND/THEN assertions.  Every claim must be
        ``"passed"`` for the feature to be marked done.
    validation_ladder:
        Ordered list of the 6 milestone levels with their completion status.
    is_done:
        True only when all proof_claims are ``"passed"`` and all six
        milestone levels have at least one satisfied claim.
    compilation_is_not_done:
        Always True – reminds downstream code that compilation alone does
        not satisfy this contract.
    missing_evidence:
        Claims that remain ``"pending"`` or ``"failed"`` at the time of
        inspection.
    self_repair_notes:
        Accumulated notes from the self-repair loop.
    """

    feature_name: str
    gameplay_contract: GameplayContract = field(default_factory=lambda: GameplayContract(""))
    proof_claims: list[ProofClaim] = field(default_factory=list)
    validation_ladder: list[dict[str, Any]] = field(default_factory=list)
    compilation_is_not_done: bool = True
    self_repair_notes: list[str] = field(default_factory=list)

    @property
    def is_done(self) -> bool:
        """True only when every proof claim has been passed."""
        return bool(self.proof_claims) and all(
            c.status == "passed" for c in self.proof_claims
        )

    @property
    def missing_evidence(self) -> list[ProofClaim]:
        return [c for c in self.proof_claims if c.status != "passed"]

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["is_done"] = self.is_done
        d["missing_evidence_ids"] = [c.claim_id for c in self.missing_evidence]
        d["framework"] = "gameplay_proof_contract_v1"
        return d

    def render_proof_block(self) -> str:
        """Render the complete proof contract as human-readable text."""
        lines = [
            "=" * 72,
            f"GAMEPLAY PROOF CONTRACT: {self.feature_name}",
            f"Done: {self.is_done}  |  "
            f"Compilation = milestone 1 only, NOT done",
            "=" * 72,
        ]
        lines.append(self.gameplay_contract.render_contract())
        lines.append("")
        lines.append("## Proof Claims")
        for claim in self.proof_claims:
            lines.append("")
            lines.append(claim.render_claim())
        if self.missing_evidence:
            lines.append("")
            lines.append(
                f"## ⚠  OUTSTANDING ({len(self.missing_evidence)} claims not yet passed)"
            )
            for c in self.missing_evidence:
                lines.append(f"  [{c.status.upper()}] {c.claim_id}: {c.then_assertion}")
        lines.append("=" * 72)
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Deterministic extractors
# ---------------------------------------------------------------------------

_KEY_PATTERN = re.compile(r"['\"]([A-Za-z0-9_]+)['\"]|key\s+'([A-Za-z0-9]+)'|InputKey\s+(\w+)", re.IGNORECASE)
_ASSET_PATTERN = re.compile(r"/Game/[A-Za-z0-9_/]+", re.IGNORECASE)
_MOVE_MODE_PATTERN = re.compile(r"MOVE_([A-Za-z]+)", re.IGNORECASE)
_STAMINA_PATTERN = re.compile(r"stamina|energy|mana|resource", re.IGNORECASE)
_ANIM_CLIP_PATTERN = re.compile(r"\b(anim(?:ation)?|montage|clip|sequence|slot)\b", re.IGNORECASE)
_GAS_PATTERN = re.compile(r"\b(gameplay\s*ability|GAS|GA_|GE_|GameplayEffect|AbilitySystemComponent)\b", re.IGNORECASE)
_TRACE_PATTERN = re.compile(r"\b(capsule|sphere|line|box)\s*trace\b", re.IGNORECASE)
_COMPILE_CLAIM_WORDS = re.compile(r"\b(compile|save|save\s+loaded|EditorAssetLibrary\.save)\b", re.IGNORECASE)
_RETARGET_PATTERN = re.compile(r"\b(retarget|retargeting|IK\s*retarget)\b", re.IGNORECASE)
_GRAVITY_PATTERN = re.compile(r"\b(gravity\s*scale|GravityScale)\b", re.IGNORECASE)
_DAMAGE_PATTERN = re.compile(r"\b(damage|health|hp|hit\s*points)\b", re.IGNORECASE)
_UI_PATTERN = re.compile(r"\b(?:UMG|widget|HUD|UI|WBP_[A-Za-z0-9_]*|UserWidget)\b", re.IGNORECASE)
_PCG_PATTERN = re.compile(r"\b(PCG|procedural\s+content|foliage\s+spawner)\b", re.IGNORECASE)
_MAYA_RIG_PATTERN = re.compile(r"\b(HIK|FK|IK|control\s+rig|joint|rig)\b", re.IGNORECASE)
_MM_PATTERN = re.compile(r"\b(motion\s*matching|PoseSearch|PSD_)\b", re.IGNORECASE)
_INVULN_PATTERN = re.compile(r"invulner|invincib|iframe|i-frame", re.IGNORECASE)
_NETWORK_PATTERN = re.compile(r"\b(replicate|server|client|authority|multiplay)\b", re.IGNORECASE)


def _extract_keys(text: str) -> list[str]:
    keys = []
    for m in _KEY_PATTERN.finditer(text):
        k = m.group(1) or m.group(2) or m.group(3)
        if k:
            keys.append(k.upper())
    return list(dict.fromkeys(keys))


def _extract_assets(text: str) -> list[str]:
    return list(dict.fromkeys(_ASSET_PATTERN.findall(text)))


def _extract_move_modes(text: str) -> list[str]:
    return list(dict.fromkeys(f"MOVE_{m.group(1)}" for m in _MOVE_MODE_PATTERN.finditer(text)))


def _slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")[:60]


# ---------------------------------------------------------------------------
# Claim factories - each returns one ProofClaim or None
# ---------------------------------------------------------------------------

def _claim_key_trigger(key: str, lower: str) -> ProofClaim:
    move_modes = _extract_move_modes(lower)
    then_parts = [f"Input action for key '{key}' is received by BP_LesterPhoenix or the relevant character Blueprint"]
    if move_modes:
        then_parts.append(f"CharacterMovementComponent.MovementMode changes to {move_modes[0]}")
    then_str = "; AND ".join(then_parts)
    return ProofClaim(
        claim_id=f"key_{key.lower()}_fires_and_transitions",
        when_trigger=f"Player presses key '{key}' in PIE",
        preconditions=[
            "Character Blueprint is possessed by Player 0",
            "Enhanced Input mapping context is active",
        ],
        then_assertion=then_str,
        evidence_level=3,
        validation_method="pie_log_or_gameplay_debugger",
        failure_modes=[
            "Input mapping context not added to PlayerController at runtime",
            "AutoPossessPlayer not set → character never receives input",
            "Enhanced Input action not assigned to the mapping context asset",
        ],
    )


def _claim_movement_mode(mode: str, lower: str) -> ProofClaim:
    gravity = "GravityScale == 0.0" if _GRAVITY_PATTERN.search(lower) else None
    then_str = f"CharacterMovementComponent.MovementMode == {mode}"
    if gravity:
        then_str += f"; AND {gravity}"
    return ProofClaim(
        claim_id=_slugify(f"movement_mode_{mode}"),
        when_trigger="Traversal ability activates",
        preconditions=["Ability activation preconditions met (trace hit, stamina available, etc.)"],
        then_assertion=then_str,
        evidence_level=4,
        validation_method="state_query_via_gameplay_debugger_or_print_string",
        failure_modes=[
            "MovementMode set during BeginPlay rather than on ability activation event",
            "SetMovementMode node connected but exec pin never reached at runtime",
        ],
    )


def _claim_stamina(lower: str) -> ProofClaim:
    drain_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:stamina|energy)(?:/sec|per\s+second)?", lower)
    drain_rate = drain_match.group(0) if drain_match else "declared rate"
    return ProofClaim(
        claim_id="stamina_drains_and_cancels",
        when_trigger="Traversal ability is active",
        preconditions=["StaminaAttribute > 0 at activation"],
        then_assertion=(
            f"StaminaAttribute decreases at {drain_rate}; "
            "when StaminaAttribute reaches 0 the ability is automatically cancelled "
            "and CharacterMovementComponent.MovementMode restores to MOVE_Walking"
        ),
        evidence_level=4,
        validation_method="gameplay_debugger_attribute_view_or_automation_test",
        failure_modes=[
            "GameplayEffect applied but no periodic execution configured → stamina never drains",
            "Ability cancelled manually but GE not removed → stamina keeps draining after detach",
            "Local attribute modified but not authoritative on server in networked context",
        ],
    )


def _claim_trace(lower: str) -> ProofClaim:
    distance_match = re.search(r"(\d+(?:\.\d+)?)\s*cm", lower)
    dist = f"{distance_match.group(1)} cm" if distance_match else "declared distance"
    return ProofClaim(
        claim_id="trace_hits_intended_surface",
        when_trigger="Traversal ability activation is attempted",
        preconditions=["Character is within trace range of a WorldStatic/WorldDynamic surface"],
        then_assertion=(
            f"Capsule/Line trace starts at GetActorLocation() (not zero-vector) "
            f"and extends {dist} along GetActorForwardVector(); "
            "a hit result is returned; ability proceeds only on confirmed hit"
        ),
        evidence_level=3,
        validation_method="draw_debug_capsule_enabled_in_pie_or_print_hit_result",
        failure_modes=[
            "Trace Start/End pins left at default (0,0,0) → trace always misses",
            "Channel not set to WorldStatic/WorldDynamic → hits nothing in typical levels",
            "Trace result used but Branch(bHit) exec pin not wired → succeeds regardless of result",
        ],
    )


def _claim_animgraph_output_pose(lower: str) -> ProofClaim:
    slots = re.findall(r"Slot\s+'([^']+)'|slot\s+\"([^\"]+)\"", lower, re.IGNORECASE)
    slot_names = [s[0] or s[1] for s in slots]
    slot_str = f"through slot(s) {slot_names}" if slot_names else "through the declared slot"
    return ProofClaim(
        claim_id="animgraph_pose_reaches_output_pose",
        when_trigger="Character is active in PIE",
        preconditions=["AnimBlueprint assigned to SkeletalMeshComponent of the target character"],
        then_assertion=(
            f"State Machine pose pin is connected {slot_str} and reaches "
            "AnimGraph Output Pose node; character does NOT render in T-pose in PIE"
        ),
        evidence_level=4,
        validation_method="pie_visual_observation_and_animgraph_live_debug",
        failure_modes=[
            "Slot node placed in AnimGraph but pose pin not wired to Output Pose → T-pose",
            "AnimBlueprint compiled but not assigned to character's SkeletalMeshComponent",
            "Motion Matching or BlendSpace node disconnected after slot",
        ],
    )


def _claim_skeleton_compatibility(assets: list[str], lower: str) -> ProofClaim:
    target_skel = "SKM_Manny" if "manny" in lower else "target skeleton"
    return ProofClaim(
        claim_id="animation_skeleton_compatible",
        when_trigger="Animation sequences are imported or assigned",
        preconditions=[f"Target skeleton is {target_skel}"],
        then_assertion=(
            f"Every animation sequence resolves its skeleton path; "
            f"skeleton matches {target_skel}; retargeting is completed before assignment; "
            "character animates correctly without bone distortion"
        ),
        evidence_level=2,
        validation_method="skeleton_compatibility_service_audit_plus_pie_visual",
        failure_modes=[
            "AnimSequence imported with Mixamo skeleton → bone names mismatch → distortion in PIE",
            "Retarget job created but not executed → original skeleton remains",
            "AnimSequence path recorded before retarget finishes → stale reference used",
        ],
    )


def _claim_gas_ability(lower: str, original_prompt: str = "") -> ProofClaim:
    src = original_prompt or lower
    ga_match = re.search(r"GA_[A-Za-z0-9_]+", src)
    ga_name = ga_match.group(0) if ga_match else "the Gameplay Ability"
    return ProofClaim(
        claim_id=_slugify(f"gas_ability_{ga_name}_activates"),
        when_trigger=f"{ga_name} is granted and input is pressed",
        preconditions=[
            "AbilitySystemComponent is present and initialized on the character",
            f"{ga_name} is granted to the AbilitySystemComponent at BeginPlay or via GAS grant",
        ],
        then_assertion=(
            f"{ga_name}.ActivateAbility() is called; "
            "ability tag is applied; "
            "ability commits cost (if any); "
            "ability reaches its intended gameplay logic branch"
        ),
        evidence_level=3,
        validation_method="gameplay_debugger_ability_tab_or_log_activation_accepted",
        failure_modes=[
            "Ability granted but input binding not mapped to AbilitySpec → activation never fires",
            "AbilitySystemComponent present on CDO but not initialized in BeginPlay → null ref",
            "Ability tag missing → cooldown/blocking tags incorrectly prevent activation",
        ],
    )


def _claim_hik_rig(lower: str) -> ProofClaim:
    return ProofClaim(
        claim_id="hik_controls_drive_skeleton",
        when_trigger="FK/IK controls are manipulated in Maya viewport",
        preconditions=["HIK character definition is active", "Control rig is bound to skeleton"],
        then_assertion=(
            "Joint hierarchy moves in response to FK/IK control handles; "
            "FK_IK_Blend attribute interpolates between FK and IK pose; "
            "mesh skinning weights remain unmodified"
        ),
        evidence_level=4,
        validation_method="maya_viewport_observation_and_channel_box_verification",
        failure_modes=[
            "HIK mapped but joint names don't match convention → auto-map fails silently",
            "SDK driven keys created but not connected to blend attribute → blend has no effect",
            "Control curves exist in scene but are not parented under character hierarchy",
        ],
    )


def _claim_invulnerability(lower: str) -> ProofClaim:
    duration_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:s(?:ec(?:ond)?s?)?)", lower)
    duration = f"{duration_match.group(1)}s" if duration_match else "declared duration"
    return ProofClaim(
        claim_id="invulnerability_tag_applied_and_removed",
        when_trigger="Dodge/roll ability activates",
        preconditions=["Character is in a state where dodge is permitted"],
        then_assertion=(
            f"Gameplay tag 'State.Invulnerable' (or equivalent) is added to character; "
            f"tag persists for {duration}; "
            "tag is removed after duration expires or ability cancels; "
            "damage events during active tag deal 0 damage"
        ),
        evidence_level=4,
        validation_method="gameplay_debugger_tags_tab_and_damage_test",
        failure_modes=[
            "Tag added at ability start but removal timer not set → permanent invulnerability",
            "Tag set on local client only → server still applies damage in multiplayer",
            "Damage system does not query the tag → tag applied but has no gameplay effect",
        ],
    )


def _claim_compile_is_not_done() -> ProofClaim:
    return ProofClaim(
        claim_id="compilation_milestone_1_only",
        when_trigger="BlueprintEditorLibrary.compile_blueprint() returns without error",
        preconditions=[],
        then_assertion=(
            "Structural correctness (milestone 1) is satisfied. "
            "Runtime execution, gameplay behavior, integration, failure handling, "
            "and evidence-backed proof (milestones 2–6) are NOT satisfied by compilation. "
            "All remaining claims must still be verified."
        ),
        evidence_level=1,
        validation_method="static_compile_check",
        failure_modes=[
            "Treating compile success as feature complete",
            "Skipping PIE or runtime validation after clean compile",
        ],
        status="pending",
    )


def _claim_network_authority(lower: str) -> ProofClaim:
    return ProofClaim(
        claim_id="authoritative_state_on_server",
        when_trigger="Gameplay state changes (attribute, MovementMode, tag) during ability",
        preconditions=["Game is running in Listen Server or Dedicated Server mode"],
        then_assertion=(
            "Authoritative state mutation occurs on server; "
            "client receives replicated state; "
            "no local-only variable mutations that diverge server/client"
        ),
        evidence_level=5,
        validation_method="multiplayer_pie_two_clients_or_replication_log",
        failure_modes=[
            "MovementMode set directly on client → rubber-bands on server correction",
            "Stamina attribute modified locally but not through GAS AttributeSet → desyncs",
        ],
    )


def _generic_vertical_slice_claims(prompt: str) -> list[ProofClaim]:
    from tech_connector.services.unreal.evidence_driven_feature_synthesis_service import (
        derive_prompt_requirement_contract,
    )

    requirement = derive_prompt_requirement_contract(prompt)
    explicit = dict(requirement.get("explicit") or {})
    activation = str(explicit.get("activation") or "the intended public gameplay trigger")
    inputs = list(explicit.get("inputs") or [])
    timing = list(explicit.get("timing") or [])
    timing_text = str(timing[0].get("source_text") or "the declared threshold") if timing else "the declared threshold"
    input_text = " or ".join(inputs) if inputs else "the declared input"
    requested_artifacts = list(explicit.get("requested_artifacts") or [])
    claims = [
        ProofClaim(
            claim_id="feature_constructs_and_initializes",
            when_trigger="The affected gameplay owner is instantiated in the test world",
            preconditions=["The production character/controller/GameMode path is used"],
            then_assertion="Required components, references, input mappings, and state bindings initialize on the correct runtime instance with no relevant errors",
            evidence_level=2,
            validation_method="unreal_functional_test_state_snapshot",
            failure_modes=["Asset exists but is not assigned", "Input context exists but is not active", "State is stored on the wrong instance"],
            observation_spec={"status": "binding_required", "measurements": ["owner_instance", "required_references", "active_input_context", "new_runtime_errors"]},
        ),
        ProofClaim(
            claim_id="intended_public_trigger_reaches_active_state",
            when_trigger=activation,
            preconditions=[f"{input_text} remains active for {timing_text}"],
            then_assertion="The public gameplay path receives the trigger and the authoritative feature state enters its active state only after all declared guards pass",
            evidence_level=3,
            validation_method="unreal_functional_test_public_interface_and_state_snapshot",
            failure_modes=["Internal helper called directly while input path is disconnected", "Timer starts but is not cancelled on release", "State changes before threshold"],
            observation_spec={"status": "binding_required", "measurements": ["public_trigger_received", "guard_result", "state_before", "state_after", "activation_timestamp"]},
        ),
        ProofClaim(
            claim_id="requested_gameplay_outcome_is_observed",
            when_trigger="The feature is in its authoritative active state",
            preconditions=["The target/world conditions from the prompt remain valid"],
            then_assertion="The requested player-visible gameplay behavior occurs continuously and is driven by authoritative state rather than a debug-only side effect",
            evidence_level=4,
            validation_method="runtime_state_transform_and_player_visible_capture",
            failure_modes=["Execution pin fires but actor does not move or react", "Debug string appears while gameplay state remains unchanged", "Animation plays without gameplay integration"],
            observation_spec={"status": "binding_required", "measurements": ["authoritative_state", "actor_or_system_outcome", "presentation_state", "time_series_samples"]},
        ),
        ProofClaim(
            claim_id="invalid_and_boundary_activation_fail_safely",
            when_trigger=f"The public trigger is attempted without a valid target or before {timing_text}",
            preconditions=[],
            then_assertion="Activation is rejected or cancelled, baseline state is restored, and no persistent timer, delegate, movement, animation, or spawned-state leak remains",
            evidence_level=5,
            validation_method="unreal_functional_test_negative_and_boundary_cases",
            failure_modes=["Early release still activates", "Target loss leaves feature active", "Cancellation leaves modified movement or animation state"],
            observation_spec={"status": "binding_required", "measurements": ["activation_rejected", "baseline_restored", "leaked_runtime_state", "new_runtime_errors"]},
        ),
        ProofClaim(
            claim_id="adjacent_gameplay_regressions_are_absent",
            when_trigger="The feature test completes and adjacent gameplay inputs are exercised",
            preconditions=["Existing character and animation systems are loaded"],
            then_assertion="Existing locomotion, input, animation composition, ownership, and cleanup remain functional with no new relevant warnings or errors",
            evidence_level=6,
            validation_method="unreal_regression_suite_and_log_diff",
            failure_modes=["New AnimBP replaces existing combat/locomotion", "Input binding conflicts", "Duplicate delegates or timers persist"],
            observation_spec={"status": "binding_required", "measurements": ["adjacent_scenarios", "input_conflicts", "anim_composition", "log_diff", "cleanup"]},
        ),
    ]
    if "Animation Blueprint" in requested_artifacts or _ANIM_CLIP_PATTERN.search(prompt):
        claims.insert(
            3,
            ProofClaim(
                claim_id="animation_presentation_is_contextually_valid",
                when_trigger="The authoritative feature state becomes active",
                preconditions=["The target mesh uses the intended AnimInstance", "Every role asset passed compatibility and contextual preview"],
                then_assertion="The intended animation state/slot/layer becomes relevant, reaches Output Pose, plays on the target mesh, and visually matches the active gameplay behavior",
                evidence_level=4,
                validation_method="anim_instance_state_query_pose_relevancy_and_context_capture",
                failure_modes=["AnimGraph compiles but branch is never relevant", "Clip is skeleton-compatible but semantically wrong", "New AnimBP disconnects existing pose composition"],
                observation_spec={"status": "binding_required", "measurements": ["anim_instance_class", "active_state_or_montage", "pose_relevancy", "asset_identity", "context_capture"]},
            ),
        )
    return claims


def _claim_umg_binds_real_state(lower: str) -> ProofClaim:
    widget_match = re.search(r"WBP_[A-Za-z0-9_]+", lower)
    widget = widget_match.group(0) if widget_match else "the UMG widget"
    return ProofClaim(
        claim_id="umg_binds_live_gameplay_state",
        when_trigger="Widget is displayed during PIE",
        preconditions=[f"{widget} is added to viewport"],
        then_assertion=(
            f"{widget} reads values from the authoritative gameplay state (not hardcoded preview values); "
            "values update when underlying state changes"
        ),
        evidence_level=4,
        validation_method="pie_observation_change_state_and_verify_widget_updates",
        failure_modes=[
            "Widget bound to a preview float variable instead of the real attribute",
            "Binding function never called because Event Construct missing",
        ],
    )


def _claim_pcg_affects_level(lower: str) -> ProofClaim:
    return ProofClaim(
        claim_id="pcg_graph_populates_level",
        when_trigger="PCG graph is executed (auto or manual) on the target level",
        preconditions=["PCG component is placed in level", "WorldStatic geometry exists for surface sampler"],
        then_assertion=(
            "Foliage/spawned instances appear in the viewport; "
            "density or instance count changes when PCG parameters are modified; "
            "no null-reference or missing-asset errors in output log"
        ),
        evidence_level=4,
        validation_method="editor_viewport_observation_and_pcg_output_log",
        failure_modes=[
            "PCG graph created but not attached to any PCG Component actor in the level",
            "Surface sampler finds no WorldStatic hits → empty output with no error",
            "Projection node misconfigured → instances float above or clip below geometry",
        ],
    )


# ---------------------------------------------------------------------------
# Main builder
# ---------------------------------------------------------------------------

def extract_proof_claims_from_prompt(prompt: str) -> list[ProofClaim]:
    """Deterministically extract machine-checkable proof claims from a prompt.

    Does NOT call any LLM.  Uses pattern matching on the prompt text to
    identify which gameplay systems are involved and builds one or more
    ``ProofClaim`` objects for each detected system.
    """
    lower = (prompt or "").lower()
    claims: list[ProofClaim] = []

    # Always add the compilation-is-not-done sentinel
    claims.append(_claim_compile_is_not_done())

    # Key/Input bindings
    for key in _extract_keys(lower):
        claims.append(_claim_key_trigger(key, lower))

    # Movement mode transitions
    for mode in _extract_move_modes(lower):
        claims.append(_claim_movement_mode(mode, lower))

    # Stamina / resource drain
    if _STAMINA_PATTERN.search(lower):
        claims.append(_claim_stamina(lower))

    # Capsule/Line traces
    if _TRACE_PATTERN.search(lower):
        claims.append(_claim_trace(lower))

    # AnimGraph / Output Pose
    if _ANIM_CLIP_PATTERN.search(lower):
        claims.append(_claim_animgraph_output_pose(lower))

    # Skeleton compatibility
    if _RETARGET_PATTERN.search(lower) or "mixamo" in lower or "fbx" in lower:
        assets = _extract_assets(lower)
        claims.append(_claim_skeleton_compatibility(assets, lower))

    # GAS / Gameplay Abilities
    if _GAS_PATTERN.search(prompt):  # use original prompt (preserves case for GA_/GE_)
        claims.append(_claim_gas_ability(lower, original_prompt=prompt))

    # Maya HIK rigging
    if _MAYA_RIG_PATTERN.search(lower) and "maya" in lower:
        claims.append(_claim_hik_rig(lower))

    # Invulnerability / iframes (search original prompt for mixed case)
    if _INVULN_PATTERN.search(prompt):
        claims.append(_claim_invulnerability(lower))

    # UMG / Widget state binding (search original prompt for mixed case)
    if _UI_PATTERN.search(prompt):
        claims.append(_claim_umg_binds_real_state(lower))

    # PCG / Foliage
    if _PCG_PATTERN.search(prompt):
        claims.append(_claim_pcg_affects_level(lower))

    # Network/replication
    if _NETWORK_PATTERN.search(lower):
        claims.append(_claim_network_authority(lower))

    existing_ids = {claim.claim_id for claim in claims}
    for claim in _generic_vertical_slice_claims(prompt):
        if claim.claim_id not in existing_ids:
            claims.append(claim)
            existing_ids.add(claim.claim_id)

    # Deduplicate by claim_id (keep first)
    seen: set[str] = set()
    unique: list[ProofClaim] = []
    for c in claims:
        if c.claim_id not in seen:
            seen.add(c.claim_id)
            unique.append(c)
    return unique


def _build_gameplay_contract_from_prompt(prompt: str) -> GameplayContract:
    from tech_connector.services.unreal.evidence_driven_feature_synthesis_service import (
        derive_prompt_requirement_contract,
    )

    lower = (prompt or "").lower()
    keys = _extract_keys(lower)
    modes = _extract_move_modes(lower)
    assets = _extract_assets(prompt)
    requirement = derive_prompt_requirement_contract(prompt)
    explicit = dict(requirement.get("explicit") or {})
    prompt_inputs = list(explicit.get("inputs") or [])
    timing = list(explicit.get("timing") or [])

    # Feature name
    feature_name = "Unknown Feature"
    if "climbing" in lower or "climb" in lower:
        feature_name = "Wall Climbing"
    elif "grapple" in lower or "grappling" in lower:
        feature_name = "Grappling Hook"
    elif "dodge" in lower or "roll" in lower:
        feature_name = "Combat Dodge Roll"
    elif "rig" in lower and "maya" in lower:
        feature_name = "Maya Character Rig"
    elif "foliage" in lower or "pcg" in lower:
        feature_name = "Procedural Foliage PCG"
    elif "motion matching" in lower:
        feature_name = "Motion Matching Combat"
    elif "stamina" in lower:
        feature_name = "Stamina System"

    trigger_key = keys[0] if keys else None
    trigger = str(explicit.get("activation") or "") or (
        f"Player presses key '{trigger_key}' through the active input mapping"
        if trigger_key else
        "The intended public gameplay event resolved during architecture planning"
    )

    preconditions = ["Character is possessed and alive"]
    if _STAMINA_PATTERN.search(lower):
        preconditions.append("StaminaAttribute > 0")
    if _TRACE_PATTERN.search(lower):
        preconditions.append("A compatible surface is within trace range")
    if _GAS_PATTERN.search(prompt):
        preconditions.append("Gameplay Ability is granted to AbilitySystemComponent")
    if any(value in lower for value in ("wall", "surface", "target", "obstacle")):
        preconditions.append("A compatible world target is detected and remains valid")

    runtime_behavior = []
    if _TRACE_PATTERN.search(lower):
        runtime_behavior.append("Capsule/Line trace runs from actor location along forward vector")
    if modes:
        runtime_behavior.append(f"CharacterMovementComponent.MovementMode is set to {modes[0]}")
    if _GRAVITY_PATTERN.search(lower):
        runtime_behavior.append("GravityScale is set to 0.0")
    if _STAMINA_PATTERN.search(lower):
        runtime_behavior.append("Stamina drains at declared rate per second via Gameplay Effect")
    if _ANIM_CLIP_PATTERN.search(lower):
        runtime_behavior.append("Animation state machine transitions to the appropriate state")
    if prompt_inputs:
        runtime_behavior.append("Input state is measured from " + " or ".join(prompt_inputs))
    if timing:
        runtime_behavior.append("Activation guard enforces " + str(timing[0].get("source_text") or "the declared threshold"))
    runtime_behavior.append("Authoritative feature state has explicit enter, update, exit, cancel, and recovery paths")

    state_changes = []
    if modes:
        state_changes.append(f"MovementMode = {modes[0]}")
    if _GRAVITY_PATTERN.search(lower):
        state_changes.append("GravityScale = 0.0")
    if _GAS_PATTERN.search(prompt):
        state_changes.append("Gameplay ability tag applied to character")
    if _STAMINA_PATTERN.search(lower):
        state_changes.append("StaminaAttribute decremented by GameplayEffect")
    if _INVULN_PATTERN.search(prompt):
        state_changes.append("Invulnerability Gameplay Tag added for duration")
    if _RETARGET_PATTERN.search(lower) or "mixamo" in lower or "fbx" in lower:
        state_changes.append("AnimSequence skeleton reference updated to target skeleton")
    if _PCG_PATTERN.search(prompt):
        state_changes.append("PCG Component spawned instances placed in level")
    if _UI_PATTERN.search(prompt):
        state_changes.append("UMG widget binding updated to reflect live attribute value")
    if not state_changes:
        state_changes.append("Resolved authoritative feature state changes from inactive to active and back to baseline")

    player_visible = "Character responds to input with the expected movement/animation transition"
    if "climbing" in lower:
        player_visible = "Character physically moves along wall surface in the climbing animation"
    elif "dodge" in lower:
        player_visible = "Character rolls in the input direction; invulnerable during roll"

    cancellation_terms = ["a required target becomes invalid", "a blocking state is entered"]
    if prompt_inputs:
        cancellation_terms.insert(0, "the player releases the required input")
    if _STAMINA_PATTERN.search(lower):
        cancellation_terms.append("the requested resource is depleted")
    cancellation = "Feature exits when " + ", ".join(cancellation_terms) + "; all modified state is restored"
    if modes:
        cancellation += f"; MovementMode returns to MOVE_Walking; GravityScale restored"

    invalid_conditions = [
        "No surface within trace range → ability activation rejected, no state change",
        "Insufficient stamina → activation blocked",
        "AbilitySystemComponent not initialized → null-safe failure, log error",
        "Animation clip missing → ability still functions, log warning",
        "Input pressed during blocking ability state → ignored",
    ]

    invalid_conditions = [
        "Required target or world condition unavailable -> activation rejected with no persistent state change",
        "Input attempted during a blocking state -> ignored or queued according to the resolved ownership policy",
        "Required runtime reference unavailable -> null-safe failure with a structured diagnostic",
    ]
    if timing:
        invalid_conditions.append("Input released before the declared threshold -> timer cancelled and activation rejected")
    if _STAMINA_PATTERN.search(lower):
        invalid_conditions.append("Insufficient requested resource -> activation blocked")
    if _ANIM_CLIP_PATTERN.search(lower) or "abp" in lower:
        invalid_conditions.append("Required animation role missing or contextually invalid -> feature cannot be reported complete")

    integration = []
    if assets:
        integration.append(f"Assets modified: {', '.join(assets[:4])}")
    if _GAS_PATTERN.search(prompt):
        integration.append("AbilitySystemComponent receives and tracks ability state")
    if _UI_PATTERN.search(lower):
        integration.append("UMG widget updates from live gameplay state")
    if _NETWORK_PATTERN.search(lower):
        integration.append("Server holds authoritative state; clients receive replicated values")

    return GameplayContract(
        feature_name=feature_name,
        trigger=trigger,
        preconditions=preconditions,
        runtime_behavior=runtime_behavior,
        state_changes=state_changes,
        player_visible_result=player_visible,
        completion_or_cancellation=cancellation,
        invalid_conditions=invalid_conditions,
        integration_criteria=integration,
    )


def _build_validation_ladder(claims: list[ProofClaim]) -> list[dict[str, Any]]:
    """Produce the 6-milestone ladder with counts of claims per level."""
    ladder = []
    for level, label in EVIDENCE_LEVEL_LABELS.items():
        level_claims = [c for c in claims if c.evidence_level == level]
        passed = [c for c in level_claims if c.status == "passed"]
        ladder.append({
            "milestone": level,
            "label": label,
            "claim_count": len(level_claims),
            "passed_count": len(passed),
            "complete": len(level_claims) > 0 and len(passed) == len(level_claims),
            "claim_ids": [c.claim_id for c in level_claims],
        })
    return ladder


def build_gameplay_proof_contract(
    prompt: str,
    *,
    feature_name: str = "",
) -> GameplayProofContract:
    """Build a fully structured, machine-checkable :class:`GameplayProofContract`.

    Parameters
    ----------
    prompt:
        The raw user prompt text.
    feature_name:
        Optional override for the feature name label.

    Returns
    -------
    GameplayProofContract
        Ready to be consumed by the planner, progress service, and
        evidence gatherers. ``is_done`` will be ``False`` until all
        ``ProofClaim`` objects are marked ``"passed"`` by the
        validation pipeline.
    """
    gameplay_contract = _build_gameplay_contract_from_prompt(prompt)
    if feature_name:
        gameplay_contract.feature_name = feature_name
    claims = extract_proof_claims_from_prompt(prompt)
    ladder = _build_validation_ladder(claims)

    return GameplayProofContract(
        feature_name=feature_name or gameplay_contract.feature_name,
        gameplay_contract=gameplay_contract,
        proof_claims=claims,
        validation_ladder=ladder,
        compilation_is_not_done=True,
        self_repair_notes=[],
    )


def record_claim_evidence(
    contract: GameplayProofContract,
    claim_id: str,
    observed: str,
    passed: bool,
    origin: str = "model_inference",
) -> None:
    """Record runtime evidence against a specific proof claim in-place.

    Parameters
    ----------
    contract:
        The :class:`GameplayProofContract` to update.
    claim_id:
        The ``claim_id`` of the :class:`ProofClaim` to update.
    observed:
        Human-readable description of what was observed.
    passed:
        Whether the observation satisfies the claim's ``then_assertion``.
    origin:
        The source of the evidence. Must be a trusted origin to satisfy runtime claims.
    """
    for claim in contract.proof_claims:
        if claim.claim_id == claim_id:
            claim.evidence_observed = observed
            claim.evidence_origin = origin
            
            # Trust rules:
            is_valid_pass = False
            if passed:
                if origin in ("unreal_runtime", "unreal_automation", "unreal_functional_test"):
                    is_valid_pass = True
                elif origin == "static_analysis" and claim.evidence_level == 1:
                    is_valid_pass = True
                elif origin == "human_observation":
                    is_valid_pass = True
                    
            claim.status = "passed" if is_valid_pass else "failed"
            return
    # Not found – append a new claim
    contract.proof_claims.append(
        ProofClaim(
            claim_id=claim_id,
            when_trigger="(from runtime evidence recording)",
            then_assertion="(not pre-declared)",
            evidence_observed=observed,
            evidence_origin=origin,
            status="passed" if (passed and origin in ("unreal_runtime", "unreal_automation", "unreal_functional_test")) else "failed",
        )
    )


def render_done_definition() -> str:
    """Return the canonical definition-of-done as a renderable string."""
    return (
        "## Definition of Done (Gameplay Proof Contract Standard)\n\n"
        "The task is complete ONLY when:\n"
        "1. The implementation compiles (structural correctness).\n"
        "2. The feature can be activated through its intended gameplay path.\n"
        "3. The expected runtime state changes occur (MovementMode, tags, attributes, etc.).\n"
        "4. The player-visible or system-visible gameplay outcome is observed in PIE.\n"
        "5. Important invalid/cancellation paths fail safely and restore valid state.\n"
        "6. Relevant regressions (input conflicts, animation state, replication) are checked.\n"
        "7. Evidence is provided for each proof claim.\n\n"
        "> Compilation alone satisfies milestone 1 only.\n"
        "> Never claim a feature works based solely on compilation, asset creation,\n"
        "> graph connectivity, or theoretical correctness."
    )
