"""Compatibility facade for decomposed project edit workflow services."""
from __future__ import annotations

import ast
import copy
import importlib
import importlib.util
import itertools
import json
import re
import tempfile
import time
from collections.abc import Mapping
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Callable

from tech_connector.models.constants import TOOLS_ROOT
from tech_connector.services.llm_router_service import (
    LLMProviderRoute,
    generate_llm_response,
    resolve_llm_provider_route,
)
from tech_connector.services.project_edit_agent_service import (
    ProjectEditApplyResult,
    ProjectEditPlan,
    ProjectEditPromptStage,
    apply_project_edit_agent_response,
    apply_project_edit_generated_symbol_repair,
    build_project_edit_agent_request,
    assemble_project_edit_generated_chunks,
    build_project_edit_artifact_chunk_stages,
    build_project_edit_artifact_file_stages,
    build_project_edit_artifact_manifest_stage,
    build_project_edit_chunk_plan_stage,
    build_deterministic_project_edit_chunk_plan,
    build_user_visible_implementation_plan,
    build_project_edit_function_repair_contract,
    build_project_edit_function_repair_plan_stage,
    build_project_edit_function_repair_stage,
    build_project_edit_class_repair_stage,
    build_project_edit_class_set_repair_stage,
    build_project_edit_integration_contract_stage,
    build_project_edit_missing_symbol_stage,
    build_project_edit_multi_file_candidate,
    parse_project_edit_chunk_plan,
    parse_project_edit_generated_chunk,
    extract_project_edit_artifact_requirements,
    complete_project_edit_integration_contract_response,
    ensure_project_edit_requested_docstrings,
    enforce_project_edit_requested_test_contracts,
    format_project_edit_generated_python,
    model_for_project_edit_stage,
    apply_project_edit_missing_symbol,
    apply_project_edit_generated_class_repair,
    apply_project_edit_generated_class_set_repair,
    parse_project_edit_artifact_manifest,
    parse_project_edit_function_repair_plan,
    parse_project_edit_generated_file,
    preview_project_edit_agent_response,
    project_edit_validation_failure_signature,
    remove_project_edit_unused_imports,
    repair_project_edit_duplicate_dependency_symbols,
    resolve_project_edit_cross_file_symbols,
    resolve_project_edit_standard_library_symbols,
)


StatusCallback = Callable[[str], None]

from tech_connector.services.project_edit_workflow_part_01 import (
    ProjectEditWorkflowResult,
    WORKFLOW_CHECKPOINT_VALIDATOR_VERSION,
    _available_qt_binding,
    _candidate_checkpoint_fingerprint,
    _checkpoint_hash,
    _clear_workflow_checkpoint,
    _enforce_manifest_symbol_owners,
    _ensure_new_qt_ui_main_show,
    _ensure_qt_test_application,
    _explicit_prompt_symbol_owners,
    _federated_symbol_evidence_context,
    _generated_symbol_fingerprints,
    _hoist_generated_test_project_imports,
    _indexed_requested_base_owner_context,
    _indexed_requested_base_owner_records,
    _normalize_generated_qt_binding,
    _normalize_generated_qt_tests,
    _normalize_qt_entry_application_ownership,
    _qualified_reference_member_symbols,
    _remove_foreign_manifest_symbols,
    _remove_generated_self_imports,
    _remove_shadowed_and_duplicate_generated_imports,
    _remove_unrequested_failure_tests,
    _repair_invalid_patch_targets,
    _repair_proven_import_surface,
    _repair_screen_overlay_capture_order,
    _repair_unrequested_frozen_dataclass,
    _repair_verified_qt_runtime_api,
    _resolve_generated_qt_symbols,
    _stable_validation_finding,
    _untouched_repair_regressions,
    _validation_finding_map,
    _verified_external_boundary_targets,
    _workflow_checkpoint_path,
)

from tech_connector.services.project_edit_workflow_part_02 import (
    _callable_repair_targets,
    _ensure_generated_generic_type_parameters,
    _lift_generated_main_block,
    _normalize_generated_files,
    _normalize_generated_python_source_quality,
    _repair_local_callable_definition_order,
    _repair_missing_positive_predicate_fixture,
    _repair_missing_stable_order_self_test_proof,
    _repair_observed_literal_test_expectations,
    _repair_requested_python_contract_surface,
    _repair_standardized_local_quality_issues,
)

from tech_connector.services.project_edit_workflow_part_03 import (
    _explicit_cross_file_delegation_spec,
    _repair_authoritative_unreal_call_signatures,
    _repair_asset_operation_pipeline_contract,
    _repair_command_result_envelope_contract,
    _repair_cross_thread_callback_routing,
    _repair_entry_point_owner_reference,
    _repair_ephemeral_missing_host_import,
    _repair_explicit_cross_file_delegation,
    _repair_explicit_cross_file_delegation_harness,
    _repair_explicit_path_policy_semantics,
    _repair_priority_job_queue_contract,
    _repair_host_result_contracts,
    _repair_image_cache_contract,
    _repair_include_state_checkbox_consumption,
    _repair_integer_progress_contracts,
    _repair_local_qt_signal_scaffolding,
    _repair_misplaced_ui_attribute_reconstruction,
    _repair_missing_cross_file_imports,
    _repair_nested_worker_operation_protocol,
    _repair_official_unreal_editor_property_names,
    _repair_official_unreal_enum_members,
    _repair_qt_worker_progress_injection,
    _repair_unreachable_delegated_launcher,
    _repair_unreferenced_private_helpers,
    _repair_unresolved_signal_connections,
    _repair_unretained_worker_dispatch,
    _repair_verified_qt_worker_integration,
    _repair_worker_constructor_progress_routing,
)

from tech_connector.services.project_edit_workflow_part_04 import (
    _dedupe_constructor_signal_connections,
    _repair_ephemeral_host_and_status_assertions,
    _repair_ephemeral_progress_recorders,
    _repair_ephemeral_unused_fixture_assignments,
    _repair_inferred_collection_type_hints,
    _repair_initial_progress_boundary,
    _repair_mapping_record_attribute_access,
    _repair_missing_path_state,
    _repair_omitted_selective_states,
    _repair_qt_result_consumer_contract,
    _repair_qt_worker_lifecycle_ownership,
    _repair_selective_record_append,
    _repair_unreachable_qt_handler_routing,
    _repair_worker_terminal_release,
)

from tech_connector.services.project_edit_workflow_part_05 import (
    _behavior_harness_production_targets,
    _module_timeout_repair_targets,
    _repair_contract_proven_mapping_assignment_keys,
    _repair_dropped_partial_iterable_result,
    _repair_ephemeral_consumer_patch_targets,
    _repair_ephemeral_expected_exception_types,
    _repair_ephemeral_invalid_combo_choices,
    _repair_ephemeral_runtime_fixture_contracts,
    _repair_ephemeral_semantic_progress_proofs,
    _repair_exactly_one_host_result_contracts,
    _repair_explicit_bool_rejections,
    _repair_input_validation_before_host_side_effects,
    _repair_nested_non_reentrant_locks,
    _repair_normalized_literal_mapping_keys,
    _repair_orphaned_result_expectations,
    _repair_qt_progress_surface_contracts,
    _repair_unrequested_exception_message_assertion,
    _runtime_deepest_frame_is_test,
    _runtime_test_production_repair_targets,
)

from tech_connector.services.project_edit_workflow_part_06 import (
    _EPHEMERAL_HOST_RUNTIME_MODULES,
    _approved_behavior_contract_rows,
    _augment_callable_targets_from_validation_causes,
    _build_ephemeral_behavior_harness_stage,
    _build_final_requirement_review_stage,
    _ephemeral_behavior_bindings,
    _ephemeral_harness_behavior_contract_errors,
    _expanded_ephemeral_behavior_rows,
    _final_requirement_review_batches,
    _merge_ephemeral_harness_sources,
    _monotonic_repair_rejections,
    _parse_ephemeral_behavior_harness,
    _repair_ephemeral_numeric_callable_fixtures,
    _repair_locked_dependency_method_ownership,
    _repair_locked_undeclared_public_methods,
    _repair_phase_validation_errors,
    _repair_required_worker_finished_cleanup,
    _repair_unapproved_ephemeral_rejections,
    _repair_unbound_host_test_binding,
    _repair_undefined_test_mock_bindings,
    _repair_unused_test_bindings,
    _runtime_behavior_contract_targets,
    _runtime_expected_error_test_targets,
    _runtime_failing_test_targets,
    _runtime_failure_target_batches,
    _ui_wiring_owner_repair_target,
)

from tech_connector.services.project_edit_workflow_part_07 import (
    _apply_ephemeral_harness_repairs,
    _build_ephemeral_harness_audit_stage,
    _clean_final_review_requirement_ids,
    _describe_top_level_symbols,
    _ensure_ephemeral_behavior_bindings,
    _ephemeral_harness_call_graph_errors,
    _focused_repair_quality_errors,
    _generated_files_for_requirements,
    _manifest_symbol_name,
    _parse_ephemeral_harness_audit,
    _parse_final_requirement_review,
    _production_evidence_candidate_is_admissible,
    _repair_ephemeral_harness_call_graph,
    _repair_ephemeral_indirect_owner_invocations,
    _requested_immutable_record_errors,
    _requested_public_constructor_errors,
    _requirement_owner_paths,
    _requirement_source_hash,
    _semantic_requirement_ledger,
    _source_defines_symbol,
)

from tech_connector.services.project_edit_workflow_part_08 import (
    _REPAIR_FAILURE_HISTORY,
    _apply_syntax_region_repair,
    _behavioral_owner_repair_targets,
    _build_behavioral_owner_resolution_stage,
    _build_runtime_snapshot_repair_stage,
    _build_syntax_region_repair_stage,
    _callable_failure_evidence,
    _compact_callable_repair_model,
    _compact_validation_error_summary,
    _contract_error_is_owned_by_other_callable,
    _focused_repair_model,
    _generation_task_model,
    _normalize_manifest_contract,
    _parse_behavioral_owner_resolution,
    _parse_runtime_snapshot_repair_analysis,
    _production_callables_exercised_by_tests,
    _query_stage,
    _repair_called_approved_property,
    _repair_insufficient_fake_clock_advance,
    _repair_stale_boolean_existence_assertion,
    _repair_stale_longest_prefix_expectation,
    _repair_uninvoked_mock_callback,
    _runtime_assertion_causal_owner_targets,
    _strong_task_model,
)

from tech_connector.services.project_edit_workflow_part_09 import (
    _callable_behavior_fingerprint,
    _causal_repair_escalation_model,
    _causal_repair_reasoning_model,
    _checkpoint_payload_is_reusable,
    _checkpoint_provenance,
    _enrich_manifest_with_explicit_declarations,
    _explicit_dotted_module_requests,
    _explicit_path_requested_file_manifest,
    _fallback_requested_file_manifest,
    _load_workflow_checkpoint,
    _load_workflow_checkpoint_state,
    _preserve_callable_docstring,
    _repair_contract_proven_order_operations,
    _repair_cross_collection_removal_polarity,
    _repair_verification_defensive_copy_proof,
    _requirement_ledger_needs_semantic_review,
    _resolve_structurally_sectioned_module_requirements,
    _save_workflow_checkpoint,
    _small_owner_reasoning_model,
)

from tech_connector.services.project_edit_workflow_part_10 import (
    run_multi_file_project_edit_workflow,
)
