"""Public game-runtime API while legacy DCC import paths remain compatible."""

from tech_connector.game_engine.runtime.engine_runtime_experience_service import (
    build_engine_runtime_experience_plan,
    runtime_goal_options,
    runtime_target_options,
)
from tech_connector.game_engine.runtime.tc_engine_api import ConfiguredRuntime, TCEngineAPI, engine
from tech_connector.game_engine.runtime.tc_live_game_sync_service import (
    build_playtest_iteration_plan,
    live_game_sessions,
    publish_tcscene_save,
    register_live_game_session,
    unregister_live_game_session,
)
from tech_connector.game_engine.runtime.tc_simulation_runtime_service import (
    RuntimeFramePacket,
    RuntimeHealthSnapshot,
    SimulationRuntimeInstance,
)
from tech_connector.game_engine.runtime.tc_engine_readiness_service import (
    EngineReadinessGate,
    EngineReadinessReport,
    audit_engine_readiness,
    qualify_runtime_determinism,
)
from tech_connector.game_engine.runtime.tc_exotic_simulation_service import (
    EXOTIC_SIMULATION_PRESETS,
    ExoticSimulationPreset,
    create_exotic_simulation,
    exotic_authoring_schema,
    exotic_simulation_preset_names,
    simulation_diagnostics,
)
from tech_connector.game_engine.runtime.tc_plasma_pic_service import ElectrostaticPicGrid
from tech_connector.game_engine.runtime.tc_magnetic_grid_service import MagnetodynamicGrid
from tech_connector.game_engine.runtime.tc_cloth_authoring_service import (
    CLOTH_QUALITY_PROFILES,
    ClothPropertyMaps,
    ClothQualityProfile,
    apply_cloth_property_maps,
    cloth_authoring_schema,
    cloth_diagnostics,
    cloth_export_contract,
    configure_cloth_quality,
    configure_cloth_collision_layers,
    create_cloth_seams,
    enable_dihedral_bending,
)
from tech_connector.game_engine.runtime.tc_procedural_animation_service import (
    GroundContact,
    GroundIKSettings,
    LimbIKResult,
    ProceduralAnimationFrame,
    ProceduralAnimationRuntime,
    solve_two_bone_ik,
)
from tech_connector.game_engine.runtime.tc_vehicle_dynamics_service import (
    VehicleControlInput,
    VehicleDynamicsFrame,
    VehicleDynamicsRuntime,
    VehicleRigSettings,
    WheelDynamicsResult,
    WheelRigSettings,
)
from tech_connector.game_engine.runtime.tc_simulation_gpu_pic_service import GpuPicGridState
from tech_connector.game_engine.runtime.tc_simulation_gpu_magnetic_service import GpuMagneticGridState
from tech_connector.game_engine.runtime.tc_simulation_compute_provider_service import (
    ArrayComputeProvider,
    ComputeProviderStatus,
    PersistentComputeBuffer,
    compute_provider,
    compute_provider_statuses,
    discover_compute_providers,
    register_compute_provider,
)
from tech_connector.game_engine.runtime.tc_simulation_native_backend_service import (
    NativeParticleBuffers,
    native_backend_support,
    native_particle_view,
    synchronize_native_particles,
)
from tech_connector.game_engine.runtime.tc_simulation_native_constraints_service import NativeConstraintBuffers
from tech_connector.game_engine.runtime.tc_simulation_gpu_backend_service import (
    GpuParticleBuffers,
    execute_gpu_compute,
    gpu_backend_support,
    gpu_particle_view,
)
from tech_connector.game_engine.runtime.tc_simulation_render_bridge_service import (
    RenderBufferView,
    SimulationRenderStream,
    build_simulation_render_stream,
    qualify_simulation_render_stream,
)
from tech_connector.game_engine.runtime.tc_multiphysics_coupling_service import (
    MultiphysicsCouplingPlan,
    MultiphysicsCouplingStage,
    compile_multiphysics_coupling,
)
from tech_connector.game_engine.runtime.tc_simulation_gpu_constraints_service import GpuConstraintBuffers
from tech_connector.game_engine.runtime.tc_simulation_native_volume_service import (
    NativeSparseVolumeBuffers,
    synchronize_native_sparse_volumes,
)
from tech_connector.game_engine.runtime.tc_simulation_gpu_volume_service import (
    GpuSparseVolumeBuffers,
    synchronize_gpu_sparse_volumes,
)
from tech_connector.game_engine.runtime.tc_fx_data_channel_service import (
    FxChannelField,
    FxDataChannel,
    FxDataChannelBinding,
    FxDataChannelConsumer,
    FxDataChannelSchema,
    FxGraphConnection,
    FxGraphNode,
    FxGraphPort,
    FxSubgraphDefinition,
    impact_data_channel,
)
from tech_connector.game_engine.runtime.procedural_runtime_service import (
    ProceduralGenerationSource,
    ProceduralRuntimeProfile,
    partition_procedural_result,
    schedule_procedural_runtime,
)
from tech_connector.game_engine.runtime.character_brain_service import (
    CharacterAction,
    CharacterDecisionReceipt,
    CharacterLODDecision,
    ModelActionProposal,
    apply_narrative_beat,
    choose_character_action,
    choose_character_lod,
    execute_character_action,
    select_narrative_beat,
)
from tech_connector.game_engine.runtime.world_intelligence_runtime_service import (
    AuthorityReceipt,
    BehaviorDecisionReceipt,
    CrowdAgentIntent,
    CrowdSteeringReceipt,
    DialogueDecisionReceipt,
    NavigationReceipt,
    PerceivedStimulus,
    PerceptionReceipt,
    SmartObjectReservation,
    SmartObjectReservationManager,
    apply_perception_receipt,
    authorize_world_mutation,
    choose_dialogue_act,
    evaluate_behavior_graph,
    find_navigation_path,
    sense_stimuli,
    simulate_group_tick,
    solve_crowd_steering,
)
from tech_connector.game_engine.runtime.world_intelligence_command_service import (
    WorldIntelligenceRuntimeState,
    execute_gameplay_experience_command,
    execute_world_intelligence_command,
)
from tech_connector.game_engine.runtime.graph_execution_service import (
    GraphExecutionContext,
    GraphExecutionError,
    GraphExecutionLimits,
    GraphExecutionReceipt,
    GraphNodeTrace,
    GraphOperationRegistry,
    create_default_graph_operation_registry,
    execute_graph_manifest,
)
from tech_connector.game_engine.runtime.graph_instance_service import (
    GraphRuntimeInstance,
    GraphTickReceipt,
)
from tech_connector.game_engine.runtime.graph_debugger_service import (
    GraphDebugSession,
    GraphDebugSessionManager,
    GraphDebugSnapshot,
    default_graph_debug_session_manager,
)
from tech_connector.game_engine.runtime.tc_ocean_surface_service import (
    OceanSample, OceanSurface, OceanWake, OceanWave, create_ocean_surface,
)

from .world_streaming_runtime_service import (
    StreamingCellState, StreamingFrameReceipt, StreamingSource, WorldStreamingRuntime,
)

__all__ = [
    "OceanSample",
    "OceanSurface",
    "OceanWake",
    "OceanWave",
    "StreamingCellState",
    "StreamingFrameReceipt",
    "StreamingSource",
    "WorldStreamingRuntime",
    "CharacterAction",
    "CharacterDecisionReceipt",
    "CharacterLODDecision",
    "ConfiguredRuntime",
    "GraphExecutionContext",
    "GraphExecutionError",
    "GraphExecutionLimits",
    "GraphExecutionReceipt",
    "GraphNodeTrace",
    "GraphOperationRegistry",
    "GraphRuntimeInstance",
    "GraphTickReceipt",
    "GraphDebugSession",
    "GraphDebugSessionManager",
    "GraphDebugSnapshot",
    "default_graph_debug_session_manager",
    "RuntimeFramePacket",
    "RuntimeHealthSnapshot",
    "EngineReadinessGate",
    "EngineReadinessReport",
    "EXOTIC_SIMULATION_PRESETS",
    "ExoticSimulationPreset",
    "ElectrostaticPicGrid",
    "GpuPicGridState",
    "GpuMagneticGridState",
    "GroundContact",
    "GroundIKSettings",
    "MagnetodynamicGrid",
    "CLOTH_QUALITY_PROFILES",
    "ClothPropertyMaps",
    "ClothQualityProfile",
    "SimulationRuntimeInstance",
    "ArrayComputeProvider",
    "ComputeProviderStatus",
    "PersistentComputeBuffer",
    "NativeParticleBuffers",
    "NativeConstraintBuffers",
    "GpuParticleBuffers",
    "RenderBufferView",
    "SimulationRenderStream",
    "MultiphysicsCouplingPlan",
    "MultiphysicsCouplingStage",
    "LimbIKResult",
    "ProceduralAnimationFrame",
    "ProceduralAnimationRuntime",
    "GpuConstraintBuffers",
    "GpuSparseVolumeBuffers",
    "NativeSparseVolumeBuffers",
    "FxChannelField",
    "FxDataChannel",
    "FxDataChannelBinding",
    "FxDataChannelConsumer",
    "FxDataChannelSchema",
    "FxGraphConnection",
    "FxGraphNode",
    "FxGraphPort",
    "FxSubgraphDefinition",
    "ProceduralGenerationSource",
    "ProceduralRuntimeProfile",
    "ModelActionProposal",
    "AuthorityReceipt",
    "BehaviorDecisionReceipt",
    "CrowdAgentIntent",
    "CrowdSteeringReceipt",
    "DialogueDecisionReceipt",
    "NavigationReceipt",
    "PerceivedStimulus",
    "PerceptionReceipt",
    "SmartObjectReservation",
    "SmartObjectReservationManager",
    "WorldIntelligenceRuntimeState",
    "VehicleControlInput",
    "VehicleDynamicsFrame",
    "VehicleDynamicsRuntime",
    "VehicleRigSettings",
    "WheelDynamicsResult",
    "WheelRigSettings",
    "TCEngineAPI",
    "build_engine_runtime_experience_plan",
    "audit_engine_readiness",
    "apply_narrative_beat",
    "apply_cloth_property_maps",
    "apply_perception_receipt",
    "authorize_world_mutation",
    "build_playtest_iteration_plan",
    "engine",
    "choose_character_action",
    "choose_character_lod",
    "choose_dialogue_act",
    "compute_provider",
    "cloth_authoring_schema",
    "cloth_diagnostics",
    "cloth_export_contract",
    "configure_cloth_quality",
    "configure_cloth_collision_layers",
    "create_cloth_seams",
    "enable_dihedral_bending",
    "create_exotic_simulation",
    "create_ocean_surface",
    "compute_provider_statuses",
    "create_default_graph_operation_registry",
    "evaluate_behavior_graph",
    "exotic_authoring_schema",
    "exotic_simulation_preset_names",
    "discover_compute_providers",
    "execute_character_action",
    "execute_gameplay_experience_command",
    "execute_gpu_compute",
    "execute_graph_manifest",
    "execute_world_intelligence_command",
    "find_navigation_path",
    "gpu_backend_support",
    "gpu_particle_view",
    "build_simulation_render_stream",
    "qualify_simulation_render_stream",
    "compile_multiphysics_coupling",
    "impact_data_channel",
    "live_game_sessions",
    "publish_tcscene_save",
    "partition_procedural_result",
    "native_backend_support",
    "native_particle_view",
    "register_compute_provider",
    "register_live_game_session",
    "runtime_goal_options",
    "runtime_target_options",
    "sense_stimuli",
    "select_narrative_beat",
    "simulation_diagnostics",
    "qualify_runtime_determinism",
    "simulate_group_tick",
    "solve_crowd_steering",
    "solve_two_bone_ik",
    "schedule_procedural_runtime",
    "synchronize_native_particles",
    "synchronize_native_sparse_volumes",
    "synchronize_gpu_sparse_volumes",
    "unregister_live_game_session",
]
