"""Public game-runtime API while legacy DCC import paths remain compatible."""

from tech_connector.game_engine.runtime.engine_runtime_experience_service import (
    build_engine_runtime_experience_plan,
    runtime_goal_options,
    runtime_target_options,
)
from tech_connector.game_engine.runtime.tc_engine_api import ConfiguredRuntime, TCEngineAPI, engine
from tech_connector.game_engine.runtime.tc_live_game_sync_service import (
    build_playtest_iteration_plan,
    live_game_sessions,
    publish_tcscene_save,
    register_live_game_session,
    unregister_live_game_session,
)
from tech_connector.game_engine.runtime.tc_simulation_runtime_service import (
    RuntimeFramePacket,
    SimulationRuntimeInstance,
)
from tech_connector.game_engine.runtime.tc_fx_data_channel_service import (
    FxChannelField,
    FxDataChannel,
    FxDataChannelBinding,
    FxDataChannelConsumer,
    FxDataChannelSchema,
    FxGraphConnection,
    FxGraphNode,
    FxGraphPort,
    FxSubgraphDefinition,
    impact_data_channel,
)
from tech_connector.game_engine.runtime.procedural_runtime_service import (
    ProceduralGenerationSource,
    ProceduralRuntimeProfile,
    partition_procedural_result,
    schedule_procedural_runtime,
)
from tech_connector.game_engine.runtime.character_brain_service import (
    CharacterAction,
    CharacterDecisionReceipt,
    CharacterLODDecision,
    ModelActionProposal,
    apply_narrative_beat,
    choose_character_action,
    choose_character_lod,
    execute_character_action,
    select_narrative_beat,
)
from tech_connector.game_engine.runtime.world_intelligence_runtime_service import (
    AuthorityReceipt,
    BehaviorDecisionReceipt,
    CrowdAgentIntent,
    CrowdSteeringReceipt,
    DialogueDecisionReceipt,
    NavigationReceipt,
    PerceivedStimulus,
    PerceptionReceipt,
    SmartObjectReservation,
    SmartObjectReservationManager,
    apply_perception_receipt,
    authorize_world_mutation,
    choose_dialogue_act,
    evaluate_behavior_graph,
    find_navigation_path,
    sense_stimuli,
    simulate_group_tick,
    solve_crowd_steering,
)
from tech_connector.game_engine.runtime.world_intelligence_command_service import (
    WorldIntelligenceRuntimeState,
    execute_gameplay_experience_command,
    execute_world_intelligence_command,
)
from tech_connector.game_engine.runtime.graph_execution_service import (
    GraphExecutionContext,
    GraphExecutionError,
    GraphExecutionLimits,
    GraphExecutionReceipt,
    GraphNodeTrace,
    GraphOperationRegistry,
    create_default_graph_operation_registry,
    execute_graph_manifest,
)
from tech_connector.game_engine.runtime.graph_instance_service import (
    GraphRuntimeInstance,
    GraphTickReceipt,
)

__all__ = [
    "CharacterAction",
    "CharacterDecisionReceipt",
    "CharacterLODDecision",
    "ConfiguredRuntime",
    "GraphExecutionContext",
    "GraphExecutionError",
    "GraphExecutionLimits",
    "GraphExecutionReceipt",
    "GraphNodeTrace",
    "GraphOperationRegistry",
    "GraphRuntimeInstance",
    "GraphTickReceipt",
    "RuntimeFramePacket",
    "SimulationRuntimeInstance",
    "FxChannelField",
    "FxDataChannel",
    "FxDataChannelBinding",
    "FxDataChannelConsumer",
    "FxDataChannelSchema",
    "FxGraphConnection",
    "FxGraphNode",
    "FxGraphPort",
    "FxSubgraphDefinition",
    "ProceduralGenerationSource",
    "ProceduralRuntimeProfile",
    "ModelActionProposal",
    "AuthorityReceipt",
    "BehaviorDecisionReceipt",
    "CrowdAgentIntent",
    "CrowdSteeringReceipt",
    "DialogueDecisionReceipt",
    "NavigationReceipt",
    "PerceivedStimulus",
    "PerceptionReceipt",
    "SmartObjectReservation",
    "SmartObjectReservationManager",
    "WorldIntelligenceRuntimeState",
    "TCEngineAPI",
    "build_engine_runtime_experience_plan",
    "apply_narrative_beat",
    "apply_perception_receipt",
    "authorize_world_mutation",
    "build_playtest_iteration_plan",
    "engine",
    "choose_character_action",
    "choose_character_lod",
    "choose_dialogue_act",
    "create_default_graph_operation_registry",
    "evaluate_behavior_graph",
    "execute_character_action",
    "execute_gameplay_experience_command",
    "execute_graph_manifest",
    "execute_world_intelligence_command",
    "find_navigation_path",
    "impact_data_channel",
    "live_game_sessions",
    "publish_tcscene_save",
    "partition_procedural_result",
    "register_live_game_session",
    "runtime_goal_options",
    "runtime_target_options",
    "sense_stimuli",
    "select_narrative_beat",
    "simulate_group_tick",
    "solve_crowd_steering",
    "schedule_procedural_runtime",
    "unregister_live_game_session",
]

