"""Generate reflected C++ bridge wrappers callable from Unreal Python."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from pathlib import Path
from typing import Any


PLUGIN_NAME = "AIStudioBridge"
MODULE_NAME = "AIStudioBridge"
LIBRARY_CLASS = "UAIStudioBridgeLibrary"


@dataclass
class WrapperPlan:
    ok: bool
    message: str
    project_root: str
    plugin_root: str
    capability: str
    function_name: str
    python_call: str
    files: list[dict[str, str]]
    next_steps: list[str]
    warnings: list[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "message": self.message,
            "project_root": self.project_root,
            "plugin_root": self.plugin_root,
            "capability": self.capability,
            "function_name": self.function_name,
            "python_call": self.python_call,
            "files": self.files,
            "next_steps": self.next_steps,
            "warnings": self.warnings,
        }


def _slug(text: str, fallback: str = "unreal_capability") -> str:
    text = re.sub(r"[^A-Za-z0-9]+", "_", text or "").strip("_").lower()
    return text or fallback


def _pascal(text: str, fallback: str = "UnrealCapability") -> str:
    words = re.findall(r"[A-Za-z0-9]+", text or "")
    if not words:
        words = re.findall(r"[A-Za-z0-9]+", fallback)
    return "".join(word[:1].upper() + word[1:] for word in words)


def _find_project_root(path: str | Path) -> Path:
    root = Path(path or "").expanduser()
    if root.is_file() and root.suffix.lower() == ".uproject":
        return root.parent.resolve()
    for candidate in [root, *root.parents]:
        if any(candidate.glob("*.uproject")):
            return candidate.resolve()
    return root.resolve()


def _infer_capability(text: str) -> dict[str, str]:
    q = (text or "").lower()
    if any(term in q for term in ("animgraph", "anim graph", "animation graph", "anim blueprint")):
        return {
            "capability": "inspect_anim_blueprint_graph",
            "label": "Inspect Anim Blueprint Graph",
            "function": "InspectAnimBlueprintGraph",
            "category": "Tech Connector|Animation",
            "argument_type": "UAnimBlueprint*",
            "argument_name": "AnimBlueprint",
            "python_argument_hint": "anim_bp",
            "summary": "Inspect Animation Blueprint graph containers, graph names, node classes, pins, and links.",
        }
    return {
        "capability": _slug(text),
        "label": _pascal(text),
        "function": _pascal(text),
        "category": "Tech Connector|Editor",
        "argument_type": "UObject*",
        "argument_name": "Target",
        "python_argument_hint": "target",
        "summary": "Bridge a missing Unreal editor capability into Python through reflected C++.",
    }


def _uplugin_text() -> str:
    data = {
        "FileVersion": 3,
        "Version": 1,
        "VersionName": "0.1.0",
        "FriendlyName": "Tech Connector Bridge",
        "Description": "Reflected C++ bridge functions generated by The Entire World Tech Connector.",
        "Category": "Editor",
        "CreatedBy": "The Entire World Tech Connector",
        "EnabledByDefault": True,
        "CanContainContent": False,
        "Modules": [
            {
                "Name": MODULE_NAME,
                "Type": "Editor",
                "LoadingPhase": "Default",
            }
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def _build_cs_text() -> str:
    return """using UnrealBuildTool;

public class AIStudioBridge : ModuleRules
{
    public AIStudioBridge(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        PublicDependencyModuleNames.AddRange(new string[]
        {
            "Core",
            "CoreUObject",
            "Engine"
        });

        PrivateDependencyModuleNames.AddRange(new string[]
        {
            "UnrealEd",
            "BlueprintGraph",
            "AnimGraph",
            "AnimGraphRuntime",
            "Json"
        });
    }
}
"""


def _module_header_text() -> str:
    return """#pragma once

#include "Modules/ModuleManager.h"

class FAIStudioBridgeModule : public IModuleInterface
{
public:
    virtual void StartupModule() override;
    virtual void ShutdownModule() override;
};
"""


def _module_cpp_text() -> str:
    return """#include "AIStudioBridge.h"

#define LOCTEXT_NAMESPACE "FAIStudioBridgeModule"

void FAIStudioBridgeModule::StartupModule()
{
}

void FAIStudioBridgeModule::ShutdownModule()
{
}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FAIStudioBridgeModule, AIStudioBridge)
"""


def _library_header_text() -> str:
    return """#pragma once

#include "Kismet/BlueprintFunctionLibrary.h"
#include "Animation/AnimBlueprint.h"
#include "AIStudioBridgeLibrary.generated.h"

UCLASS()
class AISTUDIOBRIDGE_API UAIStudioBridgeLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:
    UFUNCTION(BlueprintCallable, CallInEditor, Category="Tech Connector|Animation")
    static FString InspectAnimBlueprintGraph(UAnimBlueprint* AnimBlueprint);
};
"""


def _library_cpp_text() -> str:
    return """#include "AIStudioBridgeLibrary.h"

#if WITH_EDITOR
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "Dom/JsonObject.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#endif

static FString AIStudioJsonString(const TSharedRef<FJsonObject>& Object)
{
    FString Output;
    const TSharedRef<TJsonWriter<>> Writer = TJsonWriterFactory<>::Create(&Output);
    FJsonSerializer::Serialize(Object, Writer);
    return Output;
}

FString UAIStudioBridgeLibrary::InspectAnimBlueprintGraph(UAnimBlueprint* AnimBlueprint)
{
    const TSharedRef<FJsonObject> Root = MakeShared<FJsonObject>();
    Root->SetStringField(TEXT("capability"), TEXT("inspect_anim_blueprint_graph"));
    Root->SetBoolField(TEXT("ok"), false);

#if WITH_EDITOR
    if (!AnimBlueprint)
    {
        Root->SetStringField(TEXT("error"), TEXT("AnimBlueprint was null."));
        return AIStudioJsonString(Root);
    }

    Root->SetBoolField(TEXT("ok"), true);
    Root->SetStringField(TEXT("asset_name"), AnimBlueprint->GetName());
    Root->SetStringField(TEXT("asset_path"), AnimBlueprint->GetPathName());

    TArray<UEdGraph*> Graphs;
    Graphs.Append(AnimBlueprint->UbergraphPages);
    Graphs.Append(AnimBlueprint->FunctionGraphs);
    Graphs.Append(AnimBlueprint->MacroGraphs);
    Graphs.Append(AnimBlueprint->DelegateSignatureGraphs);

    TArray<TSharedPtr<FJsonValue>> GraphValues;
    for (UEdGraph* Graph : Graphs)
    {
        if (!Graph)
        {
            continue;
        }

        const TSharedRef<FJsonObject> GraphObject = MakeShared<FJsonObject>();
        GraphObject->SetStringField(TEXT("name"), Graph->GetName());
        GraphObject->SetStringField(TEXT("class"), Graph->GetClass()->GetName());

        TArray<TSharedPtr<FJsonValue>> NodeValues;
        for (UEdGraphNode* Node : Graph->Nodes)
        {
            if (!Node)
            {
                continue;
            }

            const TSharedRef<FJsonObject> NodeObject = MakeShared<FJsonObject>();
            NodeObject->SetStringField(TEXT("name"), Node->GetName());
            NodeObject->SetStringField(TEXT("title"), Node->GetNodeTitle(ENodeTitleType::ListView).ToString());
            NodeObject->SetStringField(TEXT("class"), Node->GetClass()->GetName());
            NodeObject->SetNumberField(TEXT("pin_count"), Node->Pins.Num());

            TArray<TSharedPtr<FJsonValue>> PinValues;
            for (UEdGraphPin* Pin : Node->Pins)
            {
                if (!Pin)
                {
                    continue;
                }
                const TSharedRef<FJsonObject> PinObject = MakeShared<FJsonObject>();
                PinObject->SetStringField(TEXT("name"), Pin->PinName.ToString());
                PinObject->SetStringField(TEXT("direction"), Pin->Direction == EGPD_Input ? TEXT("input") : TEXT("output"));
                PinObject->SetStringField(TEXT("category"), Pin->PinType.PinCategory.ToString());
                PinObject->SetNumberField(TEXT("linked_to_count"), Pin->LinkedTo.Num());
                PinValues.Add(MakeShared<FJsonValueObject>(PinObject));
            }
            NodeObject->SetArrayField(TEXT("pins"), PinValues);
            NodeValues.Add(MakeShared<FJsonValueObject>(NodeObject));
        }

        GraphObject->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());
        GraphObject->SetArrayField(TEXT("nodes"), NodeValues);
        GraphValues.Add(MakeShared<FJsonValueObject>(GraphObject));
    }

    Root->SetArrayField(TEXT("graphs"), GraphValues);
    Root->SetStringField(TEXT("python_call"), TEXT("unreal.AIStudioBridgeLibrary.inspect_anim_blueprint_graph(anim_bp)"));
#else
    Root->SetStringField(TEXT("error"), TEXT("Tech Connector bridge wrappers are editor-only."));
#endif

    return AIStudioJsonString(Root);
}
"""


def _manifest_text(spec: dict[str, str], python_call: str) -> str:
    data = {
        "plugin": PLUGIN_NAME,
        "module": MODULE_NAME,
        "library_class": "AIStudioBridgeLibrary",
        "capabilities": [
            {
                "name": spec["capability"],
                "label": spec["label"],
                "function": spec["function"],
                "python_call": python_call,
                "summary": spec["summary"],
            }
        ],
    }
    return json.dumps(data, indent=2) + "\n"


def create_unreal_cpp_wrapper_plan(
    project_root: str | Path,
    request_text: str,
    apply: bool = False,
) -> WrapperPlan:
    root = _find_project_root(project_root)
    spec = _infer_capability(request_text)
    plugin_root = root / "Plugins" / PLUGIN_NAME
    source_root = plugin_root / "Source" / MODULE_NAME
    public_root = source_root / "Public"
    private_root = source_root / "Private"
    python_call = f"unreal.AIStudioBridgeLibrary.{_python_method_name(spec['function'])}({spec['python_argument_hint']})"

    file_map = {
        plugin_root / f"{PLUGIN_NAME}.uplugin": _uplugin_text(),
        source_root / f"{MODULE_NAME}.Build.cs": _build_cs_text(),
        public_root / f"{MODULE_NAME}.h": _module_header_text(),
        private_root / f"{MODULE_NAME}.cpp": _module_cpp_text(),
        public_root / "AIStudioBridgeLibrary.h": _library_header_text(),
        private_root / "AIStudioBridgeLibrary.cpp": _library_cpp_text(),
        plugin_root / "AIStudioBridgeCapabilities.json": _manifest_text(spec, python_call),
    }

    files = [{"path": str(path), "action": "write" if apply else "preview"} for path in file_map]
    warnings: list[str] = []
    if not root.exists():
        warnings.append(f"Project root does not exist yet: {root}")
    if not any(root.glob("*.uproject")):
        warnings.append("No .uproject file found at project root; select the Unreal project folder before applying.")

    if apply:
        for path, content in file_map.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists() and path.read_text(encoding="utf-8", errors="replace") == content:
                continue
            path.write_text(content, encoding="utf-8")

    return WrapperPlan(
        ok=not warnings or apply,
        message=(
            "Generated Unreal reflected C++ bridge wrapper files."
            if apply
            else "Prepared Unreal reflected C++ bridge wrapper plan."
        ),
        project_root=str(root),
        plugin_root=str(plugin_root),
        capability=spec["capability"],
        function_name=spec["function"],
        python_call=python_call,
        files=files,
        next_steps=[
            "Enable/keep enabled the AIStudioBridge plugin in Unreal.",
            "Compile the project or use Live Coding from Unreal.",
            "Restart the editor if Unreal requests it.",
            f"Validate from Python: {python_call}",
            "Register the capability so future prompts call the wrapper directly.",
        ],
        warnings=warnings,
    )


def _python_method_name(cpp_name: str) -> str:
    chars: list[str] = []
    for i, ch in enumerate(cpp_name):
        if ch.isupper() and i > 0:
            chars.append("_")
        chars.append(ch.lower())
    return "".join(chars)

