SCALE = 1.0
SCALE_PIVOT = [0.0, 0.0, 0.0]
ORIENT_X = [0.0, 90.0, 0.0]
ORIENT_Y = [0.0, 0.0, 0.0]
ORIENT_Z = [90.0, 0.0, 0.0]

TRANSLATE_FACTOR = [0.0, 0.0, 2.0]

HEAD_NAMESPACE = "DHIhead"
BODY_NAMESPACE = "DHIbody"

MESH_NAMES = [
    "head_lod0_mesh",
    "teeth_lod0_mesh",
    "saliva_lod0_mesh",
    "eyeLeft_lod0_mesh",
    "eyeRight_lod0_mesh",
    "eyeshell_lod0_mesh",
    "eyelashes_lod0_mesh",
    "eyelashesShadow_lod0_mesh",
    "eyeEdge_lod0_mesh",
    "cartilage_lod0_mesh",
    "head_lod1_mesh",
    "teeth_lod1_mesh",
    "saliva_lod1_mesh",
    "eyeLeft_lod1_mesh",
    "eyeRight_lod1_mesh",
    "eyeshell_lod1_mesh",
    "eyelashes_lod1_mesh",
    "eyelashesShadow_lod1_mesh",
    "eyeEdge_lod1_mesh",
    "cartilage_lod1_mesh",
    "head_lod2_mesh",
    "teeth_lod2_mesh",
    "saliva_lod2_mesh",
    "eyeLeft_lod2_mesh",
    "eyeRight_lod2_mesh",
    "eyeshell_lod2_mesh",
    "eyelashes_lod2_mesh",
    "eyeEdge_lod2_mesh",
    "lashesMHC_lod2_mesh",
    "head_lod3_mesh",
    "teeth_lod3_mesh",
    "eyeLeft_lod3_mesh",
    "eyeRight_lod3_mesh",
    "eyeshell_lod3_mesh",
    "eyelashes_lod3_mesh",
    "eyeEdge_lod3_mesh",
    "lashesMHC_lod3_mesh",
    "head_lod4_mesh",
    "teeth_lod4_mesh",
    "eyeLeft_lod4_mesh",
    "eyeRight_lod4_mesh",
    "eyeshell_lod4_mesh",
    "head_lod5_mesh",
    "teeth_lod5_mesh",
    "eyeLeft_lod5_mesh",
    "eyeRight_lod5_mesh",
    "head_lod6_mesh",
    "teeth_lod6_mesh",
    "eyeLeft_lod6_mesh",
    "eyeRight_lod6_mesh",
    "head_lod7_mesh",
    "teeth_lod7_mesh",
    "eyeLeft_lod7_mesh",
    "eyeRight_lod7_mesh",
]

GUI_TRANSLATIONS = {
    "f_med": None,
    "f_srt": [-9.98377799988e-07, -7.43420410156, -8.58306884766e-06],
    "f_tal": [0.0, 8.09687805176, 0.0],
    "m_med": [-1.98682149066e-08, -3.53102281359, 0.262324757046],
    "m_srt": [-6.02503617603e-06, -11.7652910021, 0.262353367276],
    "m_tal": [-1.98682149066e-08, 3.62467787001, 0.26234096951],
}

GUI_SCALES = {
    "f_med": 1,
    "f_srt": 1,
    "f_tal": 1,
    "m_med": 1.11111111111,
    "m_srt": 1.11111111111,
    "m_tal": 1.11111111111,
}

COMMON_MAP_INFOS = [
    ("dx11_diffuseIrradiance", 1),
    ("dx11_jitter", 1),
    ("dx11_skinLUT", 1),
    ("dx11_specularIrradiance", 1),
]

COMMON_MAP_INFOS_BODY = [
    ("dx11_diffuseIrradiance_b", 1),
    ("dx11_jitter_b", 1),
    ("dx11_skinLUT_b", 1),
    ("dx11_specularIrradiance_b", 1),
]

MAP_INFOS = [
    ("head_color", 1),
    ("head_cm1_color", 0),
    ("head_cm2_color", 0),
    ("head_cm3_color", 0),
    ("head_normal", 1),
    ("head_wm1_normal", 0),
    ("head_wm2_normal", 0),
    ("head_wm3_normal", 0),
    ("head_specular", 1),
    ("head_specular_16Bits", 1),
    ("head_occlusion", 1),
    ("head_occlusion_16Bits", 1),
    ("head_cavity", 1),
    ("head_cavity_16Bits", 1),
    ("head_transmission", 1),
    ("head_transmission_16Bits", 1),
    ("head_curvature", 1),
    ("head_curvature_16Bits", 1),
    ("head_position", 1),
    ("head_position_16Bits", 1),
    ("head_worldspace", 1),
    ("head_worldspace_16Bits", 1),
    ("head_bentNormal", 1),
    ("head_bentNormal_16Bits", 1),
    ("teeth_color", 1),
    ("teeth_normal", 1),
    ("eyes_color", 1),
    ("eyeLeft_color", 1),
    ("eyeRight_color", 1),
    ("eyeLeft_normal", 1),
    ("eyeRight_normal", 1),
    ("eyes_color_16Bits", 1),
    ("eyes_normal", 1),
    ("eyes_normal_16Bits", 1),
    ("eyelashes_color", 1),
]

BODY_MAP_INFOS = [("body_color", 1), ("body_normal", 1), ("body_cavity", 1)]

MASKS = [
    "head_wm1_blink_L",
    "head_wm1_blink_R",
    "head_wm1_browsRaiseInner_L",
    "head_wm1_browsRaiseInner_R",
    "head_wm1_browsRaiseOuter_L",
    "head_wm1_browsRaiseOuter_R",
    "head_wm1_chinRaise_L",
    "head_wm1_chinRaise_R",
    "head_wm1_jawOpen",
    "head_wm1_purse_DL",
    "head_wm1_purse_DR",
    "head_wm1_purse_UL",
    "head_wm1_purse_UR",
    "head_wm1_squintInner_L",
    "head_wm1_squintInner_R",
    "head_wm2_browsDown_L",
    "head_wm2_browsDown_R",
    "head_wm2_browsLateral_L",
    "head_wm2_browsLateral_R",
    "head_wm2_mouthStretch_L",
    "head_wm2_mouthStretch_R",
    "head_wm2_neckStretch_L",
    "head_wm2_neckStretch_R",
    "head_wm2_noseWrinkler_L",
    "head_wm2_noseWrinkler_R",
    "head_wm3_cheekRaiseInner_L",
    "head_wm3_cheekRaiseInner_R",
    "head_wm3_cheekRaiseOuter_L",
    "head_wm3_cheekRaiseOuter_R",
    "head_wm3_cheekRaiseUpper_L",
    "head_wm3_cheekRaiseUpper_R",
    "head_wm3_smile_L",
    "head_wm3_smile_R",
    "head_wm13_lips_DL",
    "head_wm13_lips_DR",
    "head_wm13_lips_UL",
    "head_wm13_lips_UR",
]

MESH_SHADER_MAPPING = {
    "head_lod": "head_shader",
    "teeth_lod": "teeth_shader",
    "saliva_lod": "saliva_shader",
    "eyeLeft_lod": "eyeLeft_shader",
    "eyeRight_lod": "eyeRight_shader",
    "eyeshell_lod": "eyeshell_shader",
    "eyelashes_lod": "eyelashes_shader",
    "eyelashesShadow_lod": "eyelashesShadow_shader",
    "eyeEdge_lod": "eyeEdge_shader",
    "cartilage_lod": "eyeEdge_shader",
}

SHADERS = ["head_shader", "teeth_shader", "eyeLeft_shader", "eyeRight_shader"]
BODY_SHADERS = ["body_shader"]

FLIP_FLOP_SHADERS = [("flipflops_baseColor", 1), ("flipflops_normalMap", 1)]

SHADER_ATTRIBUTES_MAPPING = {
    "FRM_WMmultipliers.head_cm2_color_head_wm2_browsDown_L": "shader_head_shader.maskWeight_00",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_browsDown_L": "shader_head_shader.maskWeight_01",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_browsDown_R": "shader_head_shader.maskWeight_02",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_browsDown_R": "shader_head_shader.maskWeight_03",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_browsLateral_L": "shader_head_shader.maskWeight_04",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_browsLateral_L": "shader_head_shader.maskWeight_05",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_browsLateral_R": "shader_head_shader.maskWeight_06",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_browsLateral_R": "shader_head_shader.maskWeight_07",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_browsRaiseInner_L": "shader_head_shader.maskWeight_08",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_browsRaiseInner_L": "shader_head_shader.maskWeight_09",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_browsRaiseInner_R": "shader_head_shader.maskWeight_10",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_browsRaiseInner_R": "shader_head_shader.maskWeight_11",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_browsRaiseOuter_L": "shader_head_shader.maskWeight_12",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_browsRaiseOuter_L": "shader_head_shader.maskWeight_13",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_browsRaiseOuter_R": "shader_head_shader.maskWeight_14",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_browsRaiseOuter_R": "shader_head_shader.maskWeight_15",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_blink_L": "shader_head_shader.maskWeight_16",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_squintInner_L": "shader_head_shader.maskWeight_17",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_blink_L": "shader_head_shader.maskWeight_18",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_squintInner_L": "shader_head_shader.maskWeight_19",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_blink_R": "shader_head_shader.maskWeight_20",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_squintInner_R": "shader_head_shader.maskWeight_21",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_blink_R": "shader_head_shader.maskWeight_22",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_squintInner_R": "shader_head_shader.maskWeight_23",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_cheekRaiseInner_L": "shader_head_shader.maskWeight_24",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_cheekRaiseOuter_L": "shader_head_shader.maskWeight_25",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_cheekRaiseUpper_L": "shader_head_shader.maskWeight_26",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_cheekRaiseInner_L": "shader_head_shader.maskWeight_27",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_cheekRaiseOuter_L": "shader_head_shader.maskWeight_28",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_cheekRaiseUpper_L": "shader_head_shader.maskWeight_29",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_cheekRaiseInner_R": "shader_head_shader.maskWeight_30",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_cheekRaiseOuter_R": "shader_head_shader.maskWeight_31",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_cheekRaiseUpper_R": "shader_head_shader.maskWeight_32",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_cheekRaiseInner_R": "shader_head_shader.maskWeight_33",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_cheekRaiseOuter_R": "shader_head_shader.maskWeight_34",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_cheekRaiseUpper_R": "shader_head_shader.maskWeight_35",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_noseWrinkler_L": "shader_head_shader.maskWeight_36",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_noseWrinkler_L": "shader_head_shader.maskWeight_37",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_noseWrinkler_R": "shader_head_shader.maskWeight_38",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_noseWrinkler_R": "shader_head_shader.maskWeight_39",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_smile_L": "shader_head_shader.maskWeight_40",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_smile_L": "shader_head_shader.maskWeight_41",
    "FRM_WMmultipliers.head_cm1_color_head_wm13_lips_UL": "shader_head_shader.maskWeight_42",
    "FRM_WMmultipliers.head_cm1_color_head_wm13_lips_UR": "shader_head_shader.maskWeight_43",
    "FRM_WMmultipliers.head_cm1_color_head_wm13_lips_DL": "shader_head_shader.maskWeight_44",
    "FRM_WMmultipliers.head_cm1_color_head_wm13_lips_DR": "shader_head_shader.maskWeight_45",
    "FRM_WMmultipliers.head_wm1_normal_head_wm13_lips_UL": "shader_head_shader.maskWeight_46",
    "FRM_WMmultipliers.head_wm1_normal_head_wm13_lips_UR": "shader_head_shader.maskWeight_47",
    "FRM_WMmultipliers.head_wm1_normal_head_wm13_lips_DL": "shader_head_shader.maskWeight_48",
    "FRM_WMmultipliers.head_wm1_normal_head_wm13_lips_DR": "shader_head_shader.maskWeight_49",
    "FRM_WMmultipliers.head_cm3_color_head_wm3_smile_R": "shader_head_shader.maskWeight_50",
    "FRM_WMmultipliers.head_wm3_normal_head_wm3_smile_R": "shader_head_shader.maskWeight_51",
    "FRM_WMmultipliers.head_cm3_color_head_wm13_lips_UL": "shader_head_shader.maskWeight_52",
    "FRM_WMmultipliers.head_cm3_color_head_wm13_lips_DL": "shader_head_shader.maskWeight_53",
    "FRM_WMmultipliers.head_wm3_normal_head_wm13_lips_UL": "shader_head_shader.maskWeight_54",
    "FRM_WMmultipliers.head_wm3_normal_head_wm13_lips_DL": "shader_head_shader.maskWeight_55",
    "FRM_WMmultipliers.head_cm3_color_head_wm13_lips_UR": "shader_head_shader.maskWeight_56",
    "FRM_WMmultipliers.head_cm3_color_head_wm13_lips_DR": "shader_head_shader.maskWeight_57",
    "FRM_WMmultipliers.head_wm3_normal_head_wm13_lips_UR": "shader_head_shader.maskWeight_58",
    "FRM_WMmultipliers.head_wm3_normal_head_wm13_lips_DR": "shader_head_shader.maskWeight_59",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_mouthStretch_L": "shader_head_shader.maskWeight_60",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_mouthStretch_L": "shader_head_shader.maskWeight_61",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_mouthStretch_R": "shader_head_shader.maskWeight_62",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_mouthStretch_R": "shader_head_shader.maskWeight_63",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_purse_UL": "shader_head_shader.maskWeight_64",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_purse_UL": "shader_head_shader.maskWeight_65",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_purse_UR": "shader_head_shader.maskWeight_66",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_purse_UR": "shader_head_shader.maskWeight_67",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_purse_DL": "shader_head_shader.maskWeight_68",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_purse_DL": "shader_head_shader.maskWeight_69",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_purse_DR": "shader_head_shader.maskWeight_70",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_purse_DR": "shader_head_shader.maskWeight_71",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_chinRaise_L": "shader_head_shader.maskWeight_72",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_chinRaise_L": "shader_head_shader.maskWeight_73",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_chinRaise_R": "shader_head_shader.maskWeight_74",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_chinRaise_R": "shader_head_shader.maskWeight_75",
    "FRM_WMmultipliers.head_cm1_color_head_wm1_jawOpen": "shader_head_shader.maskWeight_76",
    "FRM_WMmultipliers.head_wm1_normal_head_wm1_jawOpen": "shader_head_shader.maskWeight_77",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_neckStretch_L": "shader_head_shader.maskWeight_78",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_neckStretch_L": "shader_head_shader.maskWeight_79",
    "FRM_WMmultipliers.head_cm2_color_head_wm2_neckStretch_R": "shader_head_shader.maskWeight_80",
    "FRM_WMmultipliers.head_wm2_normal_head_wm2_neckStretch_R": "shader_head_shader.maskWeight_81",
}
