"""The Entire World scene authoring and game-runtime package.

This package is intentionally independent from ``tech_connector.engine``, which
owns AI request reasoning. Qt windows consume these headless systems but do not
live here, so the same scene can run in the desktop DCC, tools, tests, or a game.
Game-engine editor surfaces live in ``tech_connector.ui.game_engine`` and the
connected scene viewer lives in ``tech_connector.ui.dcc_viewer``.
"""

from tech_connector.game_engine import authoring, deformation, integration, runtime, scene
from tech_connector.game_engine.deformation import (
    DeformationWeightMap,
    DeformationStackRuntime,
    DeformationStackTelemetry,
    DeformationLodController,
    FleshDeformerSettings,
    FleshRuntimeState,
    GpuSecondaryMotionState,
    MuscleDeformerSettings,
    MuscleRuntimeState,
    PoseSpaceTissueDriver,
    JiggleDeformerSettings,
    JiggleRuntimeState,
    SECONDARY_MOTION_PRESETS,
    SecondaryMotionPreset,
    SimulationMeshBinding,
    SimulationMeshBindingEntry,
    attach_deformation_map,
    attach_flesh_deformer,
    attach_jiggle_deformer,
    attach_muscle_deformer,
    attach_secondary_motion_preset,
    blend_deformation,
    evaluate_jiggle,
    evaluate_flesh,
    evaluate_gpu_deformation_stack,
    evaluate_muscle,
    flesh_export_contract,
    secondary_motion_export_contract,
    secondary_motion_preset,
    muscle_export_contract,
    set_muscle_activation,
    sample_simulation_mesh,
    DeformationTransferArtifact,
    build_deformation_transfer_plan,
    qualify_deformation_point_cache,
    BlendShapeCorrectiveDriver,
    BlendShapeFrame,
    BlendShapeTarget,
    BlendShapeTelemetry,
    attach_blend_shape_deformer,
    blend_shape_export_contract,
    blend_shape_payload,
    blend_shape_target_from_positions,
    blend_shape_target_from_dict,
    blend_shape_targets_from_payload,
    build_blend_shape_destination_manifest,
    blend_shape_targets_from_destination_manifest,
    evaluate_blend_shape,
    set_blend_shape_weights,
)

__all__ = [
    "DeformationWeightMap",
    "DeformationStackRuntime",
    "DeformationStackTelemetry",
    "DeformationLodController",
    "FleshDeformerSettings",
    "FleshRuntimeState",
    "GpuSecondaryMotionState",
    "MuscleDeformerSettings",
    "MuscleRuntimeState",
    "PoseSpaceTissueDriver",
    "JiggleDeformerSettings",
    "JiggleRuntimeState",
    "SECONDARY_MOTION_PRESETS",
    "SecondaryMotionPreset",
    "SimulationMeshBinding",
    "SimulationMeshBindingEntry",
    "attach_deformation_map",
    "attach_flesh_deformer",
    "attach_jiggle_deformer",
    "attach_muscle_deformer",
    "attach_secondary_motion_preset",
    "authoring",
    "blend_deformation",
    "deformation",
    "evaluate_jiggle",
    "evaluate_flesh",
    "evaluate_gpu_deformation_stack",
    "evaluate_muscle",
    "flesh_export_contract",
    "secondary_motion_export_contract",
    "secondary_motion_preset",
    "muscle_export_contract",
    "set_muscle_activation",
    "integration",
    "runtime",
    "sample_simulation_mesh",
    "scene",
    "DeformationTransferArtifact",
    "build_deformation_transfer_plan",
    "qualify_deformation_point_cache",
    "BlendShapeCorrectiveDriver",
    "BlendShapeFrame",
    "BlendShapeTarget",
    "BlendShapeTelemetry",
    "attach_blend_shape_deformer",
    "blend_shape_export_contract",
    "blend_shape_payload",
    "blend_shape_target_from_positions",
    "blend_shape_target_from_dict",
    "blend_shape_targets_from_payload",
    "build_blend_shape_destination_manifest",
    "blend_shape_targets_from_destination_manifest",
    "evaluate_blend_shape",
    "set_blend_shape_weights",
]
