"""Replaceable boundaries used by the Tech Connector licensing client."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Mapping, Protocol

from .domain import ProjectIdentity


class AuthenticationProvider(Protocol):
    def begin_login(self, device_id_hash: str, project_id: str = "") -> Mapping[str, Any]: ...
    def poll_login(self, login_attempt_id: str) -> Mapping[str, Any]: ...
    def refresh_session(self, refresh_credential: str) -> Mapping[str, Any]: ...
    def logout(self, access_token: str) -> None: ...


class LicensingGateway(Protocol):
    def register_project(self, access_token: str, project_id: str, license_id: str) -> Mapping[str, Any]: ...
    def activate_device(self, access_token: str, license_id: str, device_id_hash: str) -> Mapping[str, Any]: ...
    def deactivate_device(self, access_token: str, activation_id: str) -> None: ...
    def refresh_entitlement(self, access_token: str) -> str: ...


class EntitlementStore(Protocol):
    def load_token(self) -> str: ...
    def save_token(self, token: str) -> None: ...
    def clear(self) -> None: ...


class CredentialStore(Protocol):
    def load(self, key: str) -> str: ...
    def save(self, key: str, value: str) -> None: ...
    def delete(self, key: str) -> None: ...


class ProjectIdentityStore(Protocol):
    def load(self, project_root: str) -> ProjectIdentity | None: ...
    def ensure(self, project_root: str) -> ProjectIdentity: ...


class DeviceIdentityProvider(Protocol):
    def device_id_hash(self) -> str: ...


class AuditSink(Protocol):
    def record(self, event: str, metadata: Mapping[str, Any]) -> None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
