"""Persistent asset indexing, dependency, cache, and hot-reload services."""

from .asset_database_service import (
    AssetChange,
    AssetDatabase,
    AssetRecord,
    AssetWatchService,
    DerivedArtifact,
)
from .asset_metadata_service import (
    ASSET_METADATA_SCHEMA,
    asset_metadata_path,
    ensure_asset_metadata,
    new_asset_id,
    read_asset_metadata,
    write_asset_metadata,
)
from .asset_schema_service import (
    AssetPropertyDescriptor,
    asset_property_schema,
    default_import_settings,
    default_asset_properties,
    merge_asset_properties,
    merge_import_settings,
)
from .asset_graph_compile_service import (
    COMPILED_ASSET_IR_SCHEMA,
    GRAPH_ASSET_TYPES,
    AssetCompileDiagnostic,
    AssetCompileReceipt,
    AssetGraphCompileService,
)
from .asset_production_service import (
    AssetAuditReport,
    AssetCookReceipt,
    AssetProductionService,
)
from .prefab_service import (
    PREFAB_RUNTIME_SCHEMA, PREFAB_SCHEMA, PrefabInstance, PrefabIssue,
    PrefabResolution, PrefabService, compile_prefab_payload,
)
from .material_asset_service import (
    COLOR_TEXTURE_SLOTS, DATA_TEXTURE_SLOTS, MATERIAL_BLEND_MODES, MATERIAL_DOMAINS,
    MATERIAL_RUNTIME_SCHEMA, MATERIAL_SCHEMA, MATERIAL_SHADING_MODELS, MaterialIssue,
    MaterialResolution, MaterialService, analyze_material_graph, compile_material_payload,
    material_preset, shader_backend_capabilities,
)
from .asset_operations_service import (
    AssetDeleteReceipt,
    AssetInUseError,
    AssetOperationReceipt,
    AssetOperationsService,
    AssetReferenceFixupReceipt,
    AssetValidationIssue,
    AssetValidationReport,
)
from .asset_export_service import AssetExportReceipt, AssetExportService, EXPORT_TARGETS
from .asset_type_registry import (
    AssetTypeDescriptor,
    AssetTypeRegistry,
    BUILTIN_ASSET_TYPES,
    BUILTIN_ASSET_TYPE_REGISTRY,
    builtin_asset_type_registry,
)
from .input_map_service import InputMapAudit, InputMapDiagnostic, audit_input_map
from .build_profile_service import (
    BuildProfileDiagnostic, BuildProfilePlan, SUPPORTED_BUILD_CONFIGURATIONS,
    SUPPORTED_BUILD_PLATFORMS, plan_build_profile,
)
from .cloth_asset_service import (
    CLOTH_MAPS, FABRIC_PRESETS, ClothAuthoringIssue, ClothAutoSetupReceipt,
    automatic_cloth_maps, compile_cloth_payload, fabric_preset, validate_cloth_properties,
)
from .animation_asset_service import (
    ANIMATION_CLIP_SCHEMA, ANIMATION_CONTROLLER_SCHEMA, ANIMATION_INTERCHANGE_SCHEMA,
    ANIMATION_MASK_SCHEMA, ANIMATION_RUNTIME_SCHEMA, BLEND_SPACE_SCHEMA,
    AnimationAssetService, AnimationConversionReceipt, AnimationIssue,
    animation_clip_defaults, animation_controller_defaults, animation_mask_defaults,
    blend_space_defaults, evaluate_blend_space, validate_animation_clip,
    validate_animation_controller, validate_animation_mask, validate_blend_space,
    compile_animation_payload,
)
from .effect_asset_service import (
    EFFECT_PHASES, EFFECT_RUNTIME_SCHEMA, EFFECT_SYSTEM_SCHEMA, MODULE_LIBRARY,
    RENDERER_TYPES, SIMULATION_TARGETS, EffectAssetService, EffectCostEstimate, EffectConversionReceipt,
    EffectIssue, compile_effect_payload, effect_system_defaults, estimate_effect_cost,
    normalize_effect_properties, validate_effect_properties,
)
from .audio_asset_service import (
    ATTENUATION_SCHEMA, AUDIO_ASSET_TYPES, AUDIO_MIXER_SCHEMA, AUDIO_RUNTIME_SCHEMA,
    CUE_NODE_TYPES, DSP_EFFECTS, REVERB_SCHEMA, SOUND_CUE_SCHEMA, VOICE_RESOLUTIONS,
    AudioAssetService, AudioConversionReceipt, AudioIssue, attenuation_defaults,
    audio_clip_defaults, audio_mixer_defaults, compile_audio_clip_payload,
    compile_audio_payload, reverb_defaults, sound_cue_defaults, validate_audio_asset,
)
from .sequence_asset_service import (
    RENDER_FORMATS, SEQUENCE_RUNTIME_SCHEMA, SEQUENCE_SCHEMA, TRACK_DEFINITIONS, TRACK_TYPES,
    SequenceAssetService, SequenceIssue, add_channel_key, build_render_jobs,
    compile_sequence_payload, evaluate_channel, evaluate_sequence, new_binding,
    new_level_blend_section, new_section, new_track, native_to_unity_timeline, native_to_unreal_level_sequence,
    sequence_defaults, track_preset, unity_timeline_to_native, unreal_level_sequence_to_native,
    validate_sequence,
)
from .gameplay_foundation_service import (
    COMPONENT_TYPES, FIELD_TYPES, GAMEPLAY_FOUNDATION_RUNTIME_SCHEMA, GAMEPLAY_FOUNDATION_SCHEMA,
    GAMEPLAY_FOUNDATION_TYPES, GameplayFoundationIssue, GameplayFoundationService,
    character_definition_defaults, component_archetype_defaults, data_asset_defaults,
    data_schema_defaults, data_table_defaults, defaults_for, enum_defaults,
    project_settings_defaults, validate_foundation_asset,
)
from .gameplay_class_service import (
    GAMEPLAY_CLASS_KINDS, GAMEPLAY_CLASS_RUNTIME_SCHEMA, GAMEPLAY_CLASS_SCHEMA,
    REPLICATION_MODES, GameplayClassIssue, GameplayClassService,
    gameplay_class_defaults, graph_program_from_class, validate_gameplay_class,
)
from .world_asset_service import (
    WORLD_ASSET_SCHEMA, WORLD_ASSET_TYPES, WORLD_RUNTIME_SCHEMA, WorldAssetIssue,
    WorldAssetService, biome_defaults, compile_world_payload, data_layer_defaults,
    defaults_for_world_asset, foliage_type_defaults, hlod_layer_defaults,
    lighting_scenario_defaults, navigation_mesh_defaults, terrain_defaults,
    validate_world_asset, world_partition_defaults, apply_foliage_brush, apply_terrain_brush,
    build_hlod_preview, build_lighting_preview, build_navigation_preview,
    build_partition_preview, build_terrain_preview,
)
from .world_build_service import WORLD_BUILD_SCHEMA, WorldBuildReceipt, WorldBuildService
from .procedural_graph_asset_service import (
    PROCEDURAL_ASSET_SCHEMA, PROCEDURAL_RUNTIME_SCHEMA, ProceduralGraphAssetService,
    ProceduralGraphIssue, procedural_graph_defaults,
)
from .editor_python_api import TCEditorAPI, open_editor_api
from .physics_asset_service import (
    PHYSICS_BODY_SHAPES, RAGDOLL_PRESETS, PhysicsAuthoringIssue,
    PhysicsAssetAutoSetupReceipt, automatic_physics_asset, compile_constraint_payload,
    compile_physics_asset_payload, constraint_from_preset, ragdoll_preset,
    validate_constraint_properties, validate_physics_asset_properties,
)
from .character_asset_service import (
    CHARACTER_PERFORMANCE_PROFILES, CharacterAssetIssue, character_performance_profile,
    compile_skeletal_mesh_plan, compile_skin_binding_payload, generate_bone_lods,
    recommended_mesh_lods, validate_character_lods, validate_skin_binding_properties,
)
from .rig_asset_service import (
    CONTROL_RIG_NODE_TYPES, IK_SOLVERS, RigAssetIssue, automatic_chain_mapping,
    automatic_ik_chains, compile_rig_asset_payload, validate_control_rig_properties,
    validate_ik_retargeter_properties, validate_ik_rig_properties,
)
from .mesh_lod_generation_service import (
    CharacterMeshLodLevel, CharacterMeshLodRequest, generate_character_mesh_lods,
)
from .geometry_optimization_service import (
    GEOMETRY_COMPONENTS, GEOMETRY_EXECUTION_MODES, GEOMETRY_OPTIMIZATION_PRESETS, GEOMETRY_PROCESSORS, MATERIAL_CASTERS,
    GeometryOptimizationIssue, compile_geometry_optimization_payload, geometry_optimization_preset,
    plan_geometry_optimization, validate_geometry_optimization_profile,
)
from .groom_asset_service import (
    GROOM_GROUP_PRESETS, HAIR_BINDING_TYPES, HAIR_GEOMETRY_TYPES, HAIR_MATERIAL_PRESETS, HAIR_SOLVERS,
    GroomIssue, automatic_groom_lods, compile_groom_binding_payload, compile_groom_payload,
    compile_hair_material_payload, groom_group_preset, hair_material_preset, project_groom_roots,
    validate_groom_binding_properties, validate_groom_properties, validate_hair_material_properties,
)
from .locomotion_service import (
    LOCOMOTION_CONTROLLER_SCHEMA, LocomotionIssue, compile_locomotion_payload,
    locomotion_preset, validate_locomotion_controller,
)
from .starter_character_service import (
    STARTER_CHARACTER_SCHEMA, STARTER_SKIN_RUNTIME_ID, StarterCharacterGeometry,
    StarterCharacterReceipt, StarterCharacterService, generate_starter_mannequin_geometry,
)

__all__ = [
    "ASSET_METADATA_SCHEMA",
    "ANIMATION_CLIP_SCHEMA",
    "ANIMATION_CONTROLLER_SCHEMA",
    "ANIMATION_INTERCHANGE_SCHEMA",
    "ANIMATION_MASK_SCHEMA",
    "ANIMATION_RUNTIME_SCHEMA",
    "BLEND_SPACE_SCHEMA",
    "AnimationAssetService",
    "AnimationConversionReceipt",
    "AnimationIssue",
    "EFFECT_PHASES",
    "EFFECT_RUNTIME_SCHEMA",
    "EFFECT_SYSTEM_SCHEMA",
    "MODULE_LIBRARY",
    "RENDERER_TYPES",
    "SIMULATION_TARGETS",
    "EffectAssetService",
    "EffectCostEstimate",
    "EffectConversionReceipt",
    "EffectIssue",
    "ATTENUATION_SCHEMA",
    "AUDIO_ASSET_TYPES",
    "AUDIO_MIXER_SCHEMA",
    "AUDIO_RUNTIME_SCHEMA",
    "CUE_NODE_TYPES",
    "DSP_EFFECTS",
    "REVERB_SCHEMA",
    "SOUND_CUE_SCHEMA",
    "VOICE_RESOLUTIONS",
    "AudioAssetService",
    "AudioConversionReceipt",
    "AudioIssue",
    "COMPONENT_TYPES",
    "FIELD_TYPES",
    "GAMEPLAY_FOUNDATION_RUNTIME_SCHEMA",
    "GAMEPLAY_FOUNDATION_SCHEMA",
    "GAMEPLAY_FOUNDATION_TYPES",
    "GameplayFoundationIssue",
    "GameplayFoundationService",
    "GAMEPLAY_CLASS_KINDS",
    "GAMEPLAY_CLASS_RUNTIME_SCHEMA",
    "GAMEPLAY_CLASS_SCHEMA",
    "REPLICATION_MODES",
    "GameplayClassIssue",
    "GameplayClassService",
    "WORLD_ASSET_SCHEMA",
    "WORLD_ASSET_TYPES",
    "WORLD_RUNTIME_SCHEMA",
    "WorldAssetIssue",
    "WorldAssetService",
    "PROCEDURAL_ASSET_SCHEMA",
    "PROCEDURAL_RUNTIME_SCHEMA",
    "ProceduralGraphAssetService",
    "ProceduralGraphIssue",
    "procedural_graph_defaults",
    "AssetChange",
    "AssetCompileDiagnostic",
    "AssetCompileReceipt",
    "AssetCookReceipt",
    "AssetDatabase",
    "AssetDeleteReceipt",
    "AssetExportReceipt",
    "AssetExportService",
    "AssetInUseError",
    "AssetGraphCompileService",
    "AssetOperationReceipt",
    "AssetOperationsService",
    "AssetProductionService",
    "AssetPropertyDescriptor",
    "AssetRecord",
    "AssetAuditReport",
    "AssetReferenceFixupReceipt",
    "AssetTypeDescriptor",
    "AssetTypeRegistry",
    "AssetValidationIssue",
    "AssetValidationReport",
    "AssetWatchService",
    "BuildProfileDiagnostic",
    "BuildProfilePlan",
    "BUILTIN_ASSET_TYPES",
    "BUILTIN_ASSET_TYPE_REGISTRY",
    "COMPILED_ASSET_IR_SCHEMA",
    "CONTROL_RIG_NODE_TYPES",
    "CLOTH_MAPS",
    "CHARACTER_PERFORMANCE_PROFILES",
    "FABRIC_PRESETS",
    "ClothAuthoringIssue",
    "ClothAutoSetupReceipt",
    "CharacterAssetIssue",
    "CharacterMeshLodLevel",
    "CharacterMeshLodRequest",
    "DerivedArtifact",
    "EXPORT_TARGETS",
    "GRAPH_ASSET_TYPES",
    "GROOM_GROUP_PRESETS",
    "GEOMETRY_COMPONENTS",
    "GEOMETRY_EXECUTION_MODES",
    "GEOMETRY_OPTIMIZATION_PRESETS",
    "GEOMETRY_PROCESSORS",
    "InputMapAudit",
    "InputMapDiagnostic",
    "IK_SOLVERS",
    "HAIR_BINDING_TYPES",
    "HAIR_GEOMETRY_TYPES",
    "HAIR_MATERIAL_PRESETS",
    "HAIR_SOLVERS",
    "MATERIAL_CASTERS",
    "LOCOMOTION_CONTROLLER_SCHEMA",
    "LocomotionIssue",
    "MATERIAL_BLEND_MODES",
    "MATERIAL_DOMAINS",
    "MATERIAL_RUNTIME_SCHEMA",
    "MATERIAL_SCHEMA",
    "MATERIAL_SHADING_MODELS",
    "MaterialIssue",
    "MaterialResolution",
    "MaterialService",
    "PREFAB_SCHEMA",
    "PREFAB_RUNTIME_SCHEMA",
    "PHYSICS_BODY_SHAPES",
    "RAGDOLL_PRESETS",
    "RigAssetIssue",
    "GeometryOptimizationIssue",
    "GroomIssue",
    "PhysicsAuthoringIssue",
    "PhysicsAssetAutoSetupReceipt",
    "SUPPORTED_BUILD_CONFIGURATIONS",
    "SUPPORTED_BUILD_PLATFORMS",
    "STARTER_CHARACTER_SCHEMA",
    "STARTER_SKIN_RUNTIME_ID",
    "StarterCharacterGeometry",
    "StarterCharacterReceipt",
    "StarterCharacterService",
    "PrefabInstance",
    "PrefabIssue",
    "PrefabResolution",
    "PrefabService",
    "TCEditorAPI",
    "asset_metadata_path",
    "animation_clip_defaults",
    "animation_controller_defaults",
    "animation_mask_defaults",
    "audit_input_map",
    "asset_property_schema",
    "automatic_cloth_maps",
    "automatic_physics_asset",
    "automatic_chain_mapping",
    "automatic_groom_lods",
    "automatic_ik_chains",
    "blend_space_defaults",
    "builtin_asset_type_registry",
    "compile_cloth_payload",
    "compile_animation_payload",
    "compile_effect_payload",
    "compile_audio_clip_payload",
    "compile_audio_payload",
    "compile_constraint_payload",
    "compile_physics_asset_payload",
    "compile_skeletal_mesh_plan",
    "compile_skin_binding_payload",
    "compile_rig_asset_payload",
    "compile_geometry_optimization_payload",
    "compile_groom_binding_payload",
    "compile_groom_payload",
    "compile_hair_material_payload",
    "compile_locomotion_payload",
    "compile_material_payload",
    "compile_prefab_payload",
    "constraint_from_preset",
    "character_performance_profile",
    "ensure_asset_metadata",
    "evaluate_blend_space",
    "effect_system_defaults",
    "attenuation_defaults",
    "audio_clip_defaults",
    "audio_mixer_defaults",
    "character_definition_defaults",
    "component_archetype_defaults",
    "data_asset_defaults",
    "data_schema_defaults",
    "data_table_defaults",
    "defaults_for",
    "enum_defaults",
    "estimate_effect_cost",
    "default_asset_properties",
    "default_import_settings",
    "merge_import_settings",
    "merge_asset_properties",
    "project_settings_defaults",
    "gameplay_class_defaults",
    "graph_program_from_class",
    "validate_gameplay_class",
    "validate_foundation_asset",
    "fabric_preset",
    "generate_bone_lods",
    "generate_character_mesh_lods",
    "generate_starter_mannequin_geometry",
    "geometry_optimization_preset",
    "groom_group_preset",
    "locomotion_preset",
    "material_preset",
    "shader_backend_capabilities",
    "analyze_material_graph",
    "hair_material_preset",
    "ragdoll_preset",
    "recommended_mesh_lods",
    "new_asset_id",
    "plan_build_profile",
    "plan_geometry_optimization",
    "project_groom_roots",
    "open_editor_api",
    "read_asset_metadata",
    "write_asset_metadata",
    "validate_cloth_properties",
    "validate_constraint_properties",
    "validate_character_lods",
    "validate_physics_asset_properties",
    "validate_skin_binding_properties",
    "validate_control_rig_properties",
    "validate_ik_retargeter_properties",
    "validate_ik_rig_properties",
    "validate_geometry_optimization_profile",
    "validate_groom_binding_properties",
    "validate_groom_properties",
    "validate_hair_material_properties",
    "validate_locomotion_controller",
    "validate_animation_clip",
    "validate_animation_controller",
    "validate_animation_mask",
    "validate_blend_space",
    "normalize_effect_properties",
    "reverb_defaults",
    "sound_cue_defaults",
    "validate_audio_asset",
    "validate_effect_properties",
]
