"""Typed defaults and approachable property descriptions for engine-authored assets."""

from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class AssetPropertyDescriptor:
    key: str
    display_name: str
    default: Any
    tooltip: str
    advanced: bool = False


_SCHEMAS: dict[str, tuple[AssetPropertyDescriptor, ...]] = {
    "tc.procedural_graph": (
        AssetPropertyDescriptor("graph", "Procedural Graph", {}, "Non-destructive point, instance, mesh, terrain, and shape-grammar node graph."),
        AssetPropertyDescriptor("exposed_parameters", "Exposed Parameters", [], "Typed graph inputs shown on graph instances and tools."),
        AssetPropertyDescriptor("node_groups", "Node Groups", [], "Reusable graph groups with typed interfaces and exposed parameters."),
        AssetPropertyDescriptor("task_graph", "Task Graph", {}, "Parallel work-item graph for wedges, partitions, and build-farm scheduling."),
        AssetPropertyDescriptor("simulation", "Simulation", {}, "Persistent preview state, fixed timestep, substeps, gravity, and damping."),
        AssetPropertyDescriptor("execution", "Execution", {}, "Editor/runtime mode, partition grid, cache, backend, and frame budget."),
        AssetPropertyDescriptor("outputs", "Outputs", {}, "Geometry, instances, collision, and navigation products."),
        AssetPropertyDescriptor("interchange", "Interchange", {}, "Native graph preservation and baked fallback policy."),
    ),
    "tc.terrain": (
        AssetPropertyDescriptor("source", "Height Source", "procedural", "Procedural, imported, or painted heightfield source."),
        AssetPropertyDescriptor("resolution", "Resolution", [129, 129], "Power-of-two-plus-one vertex dimensions."),
        AssetPropertyDescriptor("cell_size", "Cell Size", 100.0, "World-space distance between height samples."),
        AssetPropertyDescriptor("height_scale", "Height Scale", 2000.0, "Maximum procedural height range."),
        AssetPropertyDescriptor("seed", "Seed", 1337, "Stable procedural generation seed."),
        AssetPropertyDescriptor("noise", "Noise", {}, "Frequency, octaves, lacunarity, and gain."),
        AssetPropertyDescriptor("erosion", "Erosion", {}, "Thermal or hydraulic erosion build settings."),
        AssetPropertyDescriptor("heightmap_asset_id", "Heightmap", "", "Optional imported height texture."),
        AssetPropertyDescriptor("layers", "Paint Layers", [], "Material layers and editable weight maps."),
        AssetPropertyDescriptor("lod", "Terrain LOD", {}, "Patch count, error, and crack-prevention settings."),
        AssetPropertyDescriptor("collision", "Collision", {}, "Collision generation and resolution."),
        AssetPropertyDescriptor("navigation", "Navigation", {}, "Navigation contribution settings."),
    ),
    "tc.foliage_type": (
        AssetPropertyDescriptor("mesh_asset_id", "Mesh", "", "Instanced static mesh."),
        AssetPropertyDescriptor("density", "Density", 1.0, "Instance density multiplier."),
        AssetPropertyDescriptor("scale_range", "Scale Range", [0.85, 1.2], "Random uniform scale limits."),
        AssetPropertyDescriptor("minimum_spacing", "Minimum Spacing", 100.0, "Minimum separation between instances."),
        AssetPropertyDescriptor("slope_range", "Slope Range", [0.0, 50.0], "Accepted terrain slope in degrees."),
        AssetPropertyDescriptor("elevation_range", "Elevation Range", [-100000.0, 100000.0], "Accepted world elevation."),
        AssetPropertyDescriptor("moisture_range", "Moisture Range", [0.0, 1.0], "Accepted procedural moisture."),
        AssetPropertyDescriptor("temperature_range", "Temperature Range", [0.0, 1.0], "Accepted procedural temperature."),
        AssetPropertyDescriptor("cull_distance", "Cull Distance", [5000.0, 30000.0], "Fade and final cull distances."),
        AssetPropertyDescriptor("collision", "Collision", "none", "None, query, or full collision."),
        AssetPropertyDescriptor("wind", "Wind", {}, "Per-instance wind response."),
    ),
    "tc.biome": (
        AssetPropertyDescriptor("terrain_asset_id", "Terrain", "", "Terrain used for ecological placement."),
        AssetPropertyDescriptor("seed", "Seed", 1337, "Stable placement seed."),
        AssetPropertyDescriptor("density", "Density", 0.55, "Global accepted-sample density."),
        AssetPropertyDescriptor("samples_per_cell", "Samples Per Cell", 1, "Placement attempts per terrain cell."),
        AssetPropertyDescriptor("species", "Species", [], "Weighted Foliage Types used by the biome."),
        AssetPropertyDescriptor("exclusion_masks", "Exclusion Masks", [], "Painted, spline, volume, and tag exclusions."),
        AssetPropertyDescriptor("partition_cell_size", "Generation Cell Size", 6400.0, "Deterministic regeneration cell size."),
    ),
    "tc.navigation_mesh": (
        AssetPropertyDescriptor("source_level_ids", "Source Levels", [], "Levels included in the navigation build."),
        AssetPropertyDescriptor("terrain_asset_ids", "Terrain Sources", [], "Terrains rasterized into walkable navigation polygons."),
        AssetPropertyDescriptor("bounds", "Nav Bounds", [], "Volumes limiting navigation generation."),
        AssetPropertyDescriptor("agents", "Agent Profiles", [], "Radius, height, step, and slope per agent."),
        AssetPropertyDescriptor("voxel_size", "Voxel Size", 10.0, "Rasterization precision."),
        AssetPropertyDescriptor("tile_size", "Tile Size", 1024.0, "Independent streaming tile size."),
        AssetPropertyDescriptor("areas", "Areas and Costs", [], "Walkable area types and traversal costs."),
        AssetPropertyDescriptor("off_mesh_links", "Off-Mesh Links", [], "Jumps, doors, ladders, and authored connections."),
        AssetPropertyDescriptor("runtime_generation", "Runtime Generation", "dynamic_modifiers", "Static, dynamic modifiers, or fully dynamic rebuilds."),
    ),
    "tc.lighting_scenario": (
        AssetPropertyDescriptor("mode", "Lighting Mode", "hybrid", "Baked, dynamic, or hybrid lighting."),
        AssetPropertyDescriptor("source_level_ids", "Source Levels", [], "Levels included in this lighting scenario."),
        AssetPropertyDescriptor("terrain_asset_ids", "Terrain Sources", [], "Terrains included in the reference lightmap bake."),
        AssetPropertyDescriptor("global_illumination", "Global Illumination", "dynamic", "GI method and fallback."),
        AssetPropertyDescriptor("lightmap_resolution", "Lightmap Resolution", 64, "Default baked lightmap resolution."),
        AssetPropertyDescriptor("texel_density", "Texel Density", 10.24, "World-space lightmap texel density."),
        AssetPropertyDescriptor("indirect_bounces", "Indirect Bounces", 3, "Number of indirect bake bounces."),
        AssetPropertyDescriptor("quality", "Bake Quality", "production", "Preview, medium, high, or production."),
        AssetPropertyDescriptor("environment", "Environment", {}, "Sky, intensity, and rotation."),
        AssetPropertyDescriptor("reflection_captures", "Reflection Captures", [], "Box, sphere, and planar captures."),
    ),
    "tc.data_layer": (
        AssetPropertyDescriptor("kind", "Layer Kind", "runtime", "Runtime-streamed or editor-only layer."),
        AssetPropertyDescriptor("parent_layer_id", "Parent Layer", "", "Optional nested Data Layer."),
        AssetPropertyDescriptor("initial_state", "Initial State", "loaded", "Unloaded, loaded, or activated."),
        AssetPropertyDescriptor("asset_ids", "Assets", [], "Assets owned by this layer."),
        AssetPropertyDescriptor("actor_paths", "Actors", [], "Level actors assigned to this layer."),
        AssetPropertyDescriptor("runtime_rules", "Runtime Rules", {}, "Priority and distance activation rules."),
        AssetPropertyDescriptor("color", "Editor Color", "#50a8ff", "Outliner and viewport visualization color."),
    ),
    "tc.hlod_layer": (
        AssetPropertyDescriptor("method", "Generation Method", "merged_mesh", "Instancing, merge, simplify, or impostor."),
        AssetPropertyDescriptor("source_data_layer_ids", "Source Data Layers", [], "Data Layers clustered by this HLOD layer."),
        AssetPropertyDescriptor("transition_distance", "Transition Distance", 50000.0, "Distance at which the proxy replaces source actors."),
        AssetPropertyDescriptor("cell_size", "Cluster Cell Size", 25600.0, "World-space clustering grid size."),
        AssetPropertyDescriptor("reduction_ratio", "Reduction Ratio", 0.25, "Target proxy triangle ratio."),
        AssetPropertyDescriptor("merge_materials", "Bake Materials", True, "Bake source materials into proxy atlases."),
        AssetPropertyDescriptor("material_texture_size", "Material Texture Size", 1024, "Proxy material atlas size."),
    ),
    "tc.world_partition": (
        AssetPropertyDescriptor("source_level_id", "Source Level", "", "Persistent Level managed by the partition."),
        AssetPropertyDescriptor("cell_size", "Cell Size", 12800.0, "Runtime streaming grid cell size."),
        AssetPropertyDescriptor("loading_range", "Loading Range", 76800.0, "Default streaming-source loading radius."),
        AssetPropertyDescriptor("data_layer_ids", "Data Layers", [], "Runtime and editor Data Layers."),
        AssetPropertyDescriptor("hlod_layer_ids", "HLOD Layers", [], "Hierarchical proxy generation layers."),
        AssetPropertyDescriptor("streaming_sources", "Streaming Sources", [], "Player, camera, teleport, and cinematic sources."),
        AssetPropertyDescriptor("budgets", "Streaming Budgets", {}, "Loaded cells, memory, IO, and request limits."),
        AssetPropertyDescriptor("always_loaded_asset_ids", "Always Loaded Assets", [], "Assets pinned independent of streaming sources."),
    ),
    "tc.level_sequence": (
        AssetPropertyDescriptor("sequence_version", "Sequence Version", 1, "Versioned cinematic sequence contract."),
        AssetPropertyDescriptor("display_rate", "Display Rate", {"numerator": 30, "denominator": 1}, "Editorial frame rate displayed in the timeline."),
        AssetPropertyDescriptor("tick_resolution", "Tick Resolution", 24000, "Internal sub-frame timing resolution."),
        AssetPropertyDescriptor("playback_range", "Playback Range", {"start": 0, "end": 300}, "Inclusive start and exclusive end used by playback and cooking."),
        AssetPropertyDescriptor("view_range", "View Range", {"start": 0, "end": 300}, "Timeline range currently framed in the editor."),
        AssetPropertyDescriptor("working_range", "Working Range", {"start": 0, "end": 300}, "Editorial range available without changing playback bounds."),
        AssetPropertyDescriptor("evaluation", "Evaluation", "frame_locked", "Frame-locked or sub-frame evaluation policy."),
        AssetPropertyDescriptor("playback_mode", "Playback Mode", "loop", "Loop, once, or ping-pong preview playback."),
        AssetPropertyDescriptor("bindings", "Object Bindings", [], "Possessable and spawnable objects targeted by tracks."),
        AssetPropertyDescriptor("tracks", "Tracks", [], "Hierarchical camera, animation, audio, event, property, effect, and sub-sequence tracks."),
        AssetPropertyDescriptor("folders", "Track Folders", [], "Editorial organization for tracks and bindings."),
        AssetPropertyDescriptor("markers", "Markers", [], "Named editorial, review, and synchronization markers."),
        AssetPropertyDescriptor("render_settings", "Render Settings", {"resolution": [1920, 1080], "format": "png", "output_directory": "Renders", "use_camera_cuts": True, "frame_handles": 0, "temporal_samples": 1, "spatial_samples": 1, "motion_blur": True, "include_audio": True, "burn_in": False, "overwrite_existing": False}, "Validated render-queue defaults shared by preview and final output."),
        AssetPropertyDescriptor("source_extensions", "Source Extensions", [], "Lossless Unreal or Unity constructs awaiting native replacement."),
    ),
    "tc.material": (
        AssetPropertyDescriptor("material_version", "Material Version", 2, "Versioned material authoring schema."),
        AssetPropertyDescriptor("preset", "Preset", "default_lit", "Editable starting point; presets never lock authored values."),
        AssetPropertyDescriptor("domain", "Material Domain", "surface", "Surface, decal, post-process, UI, or volume evaluation domain."),
        AssetPropertyDescriptor("shading_model", "Shading Model", "pbr", "Lighting model used by the material."),
        AssetPropertyDescriptor("blend_mode", "Blend Mode", "opaque", "Opaque, masked, translucent, additive, or modulate blending."),
        AssetPropertyDescriptor("two_sided", "Two Sided", False, "Render and shade both sides of the surface."),
        AssetPropertyDescriptor("base_color", "Base Color", "#ffffff", "Default surface color or texture reference."),
        AssetPropertyDescriptor("roughness", "Roughness", 0.5, "0 is mirror-smooth; 1 is fully rough."),
        AssetPropertyDescriptor("metalness", "Metalness", 0.0, "0 for dielectric surfaces; 1 for metals."),
        AssetPropertyDescriptor("specular", "Specular", 0.5, "Dielectric reflectance level."),
        AssetPropertyDescriptor("normal_strength", "Normal Strength", 1.0, "Scale applied to tangent-space normal detail."),
        AssetPropertyDescriptor("emissive_color", "Emissive Color", "#000000", "Light emitted by the material before intensity scaling."),
        AssetPropertyDescriptor("emissive_intensity", "Emissive Intensity", 0.0, "HDR multiplier for emissive color."),
        AssetPropertyDescriptor("opacity", "Opacity", 1.0, "Surface opacity for translucent domains."),
        AssetPropertyDescriptor("opacity_mask_clip", "Opacity Mask Clip", 0.333, "Masked pixels below this threshold are discarded."),
        AssetPropertyDescriptor("clear_coat", "Clear Coat", 0.0, "Secondary dielectric coating weight."),
        AssetPropertyDescriptor("clear_coat_roughness", "Clear Coat Roughness", 0.1, "Microsurface roughness of the coating."),
        AssetPropertyDescriptor("subsurface_color", "Subsurface Color", "#ffffff", "Color transmitted through subsurface materials."),
        AssetPropertyDescriptor("transmission", "Transmission", 0.0, "Fraction of light transmitted through the surface."),
        AssetPropertyDescriptor("ior", "Index of Refraction", 1.5, "Optical index used by transmissive materials."),
        AssetPropertyDescriptor("sheen", "Sheen", 0.0, "Grazing-angle cloth/fiber response."),
        AssetPropertyDescriptor("parameters", "Parameters", {}, "Typed scalar, vector, texture, and boolean values exposed to instances."),
        AssetPropertyDescriptor("parameter_groups", "Parameter Groups", {}, "Editor grouping, order, descriptions, and ranges for exposed parameters."),
        AssetPropertyDescriptor("texture_bindings", "Texture Bindings", {}, "Texture assets with channels, samplers, UV sets, and color-space intent."),
        AssetPropertyDescriptor("static_switches", "Static Switches", {}, "Compile-time choices that create shader permutations."),
        AssetPropertyDescriptor("graph", "Material Graph", {"nodes": [], "connections": []}, "Typed surface evaluation graph."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Per-platform quality, feature, and parameter overrides."),
        AssetPropertyDescriptor("preview_mesh", "Preview Mesh", "Sphere", "Mesh used by the live material preview."),
        AssetPropertyDescriptor("preview_environment", "Preview Environment", "Studio", "Lighting environment used by the preview."),
        AssetPropertyDescriptor("preview_exposure", "Preview Exposure", 0.0, "Preview-only exposure compensation."),
    ),
    "tc.material_instance": (
        AssetPropertyDescriptor("material_version", "Material Version", 2, "Versioned material-instance authoring schema."),
        AssetPropertyDescriptor("parent_material_id", "Parent Material", "", "Material or Material Instance inherited by this instance."),
        AssetPropertyDescriptor("overrides", "Overrides", {}, "Only values differing from the parent."),
        AssetPropertyDescriptor("static_switch_overrides", "Static Switch Overrides", {}, "Compile-time switches differing from the parent."),
        AssetPropertyDescriptor("parameter_groups", "Parameter Groups", {}, "Optional instance-specific grouping and descriptions."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Per-platform instance values and quality settings."),
    ),
    "tc.shader_graph": (
        AssetPropertyDescriptor("shader_version", "Shader Version", 2, "Versioned shader graph schema."),
        AssetPropertyDescriptor("stage", "Shader Stage", "surface", "Surface, vertex, fragment, compute, or post-process stage."),
        AssetPropertyDescriptor("language", "Target Language", "portable", "Portable IR, HLSL, GLSL, Metal, or SPIR-V target."),
        AssetPropertyDescriptor("graph", "Shader Graph", {"nodes": [], "connections": []}, "Typed shader operations and pin connections."),
        AssetPropertyDescriptor("defines", "Compile Defines", {}, "Named static compilation defines."),
        AssetPropertyDescriptor("include_asset_ids", "Includes / Functions", [], "Reusable shader graph and material-function dependencies."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Per-platform features, defines, and precision policies."),
    ),
    "tc.procedural_animation_profile": (
        AssetPropertyDescriptor("limbs", "Grounded Limbs", [], "Two-bone IK limb definitions with root, joint, end, pole, and ground-probe settings."),
        AssetPropertyDescriptor("pelvis_smoothing", "Pelvis Smoothing", 14.0, "Response speed for pelvis compensation."),
        AssetPropertyDescriptor("maximum_pelvis_drop", "Maximum Pelvis Drop", 0.45, "Maximum downward pelvis correction in world units."),
        AssetPropertyDescriptor("global_weight", "Global Weight", 1.0, "Blend weight applied after authored animation."),
        AssetPropertyDescriptor("evaluation_phase", "Evaluation Phase", "post_animation", "Runtime phase used for procedural animation evaluation."),
    ),
    "tc.animation_clip": (
        AssetPropertyDescriptor("animation_version", "Animation Version", 2, "Versioned editable animation-clip contract."),
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton whose joints are animated by this clip."),
        AssetPropertyDescriptor("duration_seconds", "Duration", 1.0, "Clip duration in seconds."),
        AssetPropertyDescriptor("sample_rate", "Sample Rate", 30.0, "Authored samples per second."),
        AssetPropertyDescriptor("loop", "Loop", True, "Repeat the clip during playback."),
        AssetPropertyDescriptor("root_motion", "Root Motion", "preserve", "Preserve, extract, consume, or ignore root motion."),
        AssetPropertyDescriptor("curves", "Animation Curves", [], "Joint, morph, and attribute animation curves."),
        AssetPropertyDescriptor("events", "Animation Events", [], "Timed gameplay, audio, and effects events."),
        AssetPropertyDescriptor("sync_markers", "Sync Markers", [], "Named gait, contact, and phase markers used when synchronizing clips."),
        AssetPropertyDescriptor("additive", "Additive Settings", {}, "Base pose, reference clip, and local or mesh-space additive policy."),
        AssetPropertyDescriptor("compression", "Compression", {}, "Error threshold and rotation/translation compression policy."),
    ),
    "tc.blend_space": (
        AssetPropertyDescriptor("blend_space_version", "Blend Space Version", 1, "Versioned one- or two-dimensional motion blending contract."),
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton shared by every animation sample."),
        AssetPropertyDescriptor("dimensions", "Dimensions", 2, "One dimension for a scalar blend or two for a planar blend."),
        AssetPropertyDescriptor("axes", "Axes", [], "Parameter, range, grid, wrapping, and input smoothing for each axis."),
        AssetPropertyDescriptor("samples", "Samples", [], "Animation clips positioned in blend space with rate, mirroring, and synchronization settings."),
        AssetPropertyDescriptor("interpolation", "Interpolation", {}, "Triangulation, weighting, smoothing, and numerical tolerance."),
        AssetPropertyDescriptor("sync", "Synchronization", {}, "Marker sync group and leader-selection policy."),
        AssetPropertyDescriptor("preview", "Preview Input", {}, "Live editor parameter position."),
    ),
    "tc.animation_mask": (
        AssetPropertyDescriptor("mask_version", "Mask Version", 1, "Versioned per-bone blend-mask contract."),
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton whose bones are weighted by this mask."),
        AssetPropertyDescriptor("weights", "Bone Weights", {}, "Editable zero-to-one blend weight for each bone."),
        AssetPropertyDescriptor("include_children", "Include Children", True, "Propagate authored weights through child bones."),
        AssetPropertyDescriptor("feather_depth", "Feather Depth", 0, "Number of hierarchy levels over which mask boundaries are softened."),
    ),
    "tc.animation_controller": (
        AssetPropertyDescriptor("schema", "Controller Schema", "", "Versioned controller contract."),
        AssetPropertyDescriptor("preset", "Locomotion Preset", "third_person", "Third-person, first-person, side-scroller, or fighting defaults."),
        AssetPropertyDescriptor("movement", "Character Movement", {}, "Speed, acceleration, air control, jumping, slopes, steps, and plane constraints."),
        AssetPropertyDescriptor("camera", "Camera Follow", {}, "Camera mode, offset, target height, and smoothing."),
        AssetPropertyDescriptor("parameters", "Parameters", {}, "Typed state-machine inputs exposed to gameplay and Python."),
        AssetPropertyDescriptor("animation_slots", "Animation Slots", {}, "Replaceable idle, walk, run, strafe, jump, and landing clips."),
        AssetPropertyDescriptor("blend_spaces", "Blend Spaces", [], "Speed and direction samples used for continuous grounded locomotion."),
        AssetPropertyDescriptor("state_machine", "State Machine", {}, "Grounded, jumping, airborne, and landing states and transitions."),
        AssetPropertyDescriptor("root_motion", "Root Motion", {}, "In-place or root-motion extraction and consumption policy."),
        AssetPropertyDescriptor("procedural", "Procedural Adjustments", {}, "Foot placement, pelvis compensation, and stride warping."),
        AssetPropertyDescriptor("graph", "Animation Graph", {"nodes": [], "connections": []}, "Editable animation evaluation graph."),
        AssetPropertyDescriptor("layers", "Animation Layers", [], "Layered state machines with override/additive blending and optional bone masks."),
        AssetPropertyDescriptor("pose_graph", "Pose Graph", {"nodes": [], "connections": []}, "Final pose evaluation graph after state-machine motion selection."),
        AssetPropertyDescriptor("slots", "Slots", [], "Named insertion points for montages, actions, and gameplay overrides."),
        AssetPropertyDescriptor("sync_groups", "Sync Groups", [], "Marker-based synchronization groups for related motions."),
        AssetPropertyDescriptor("performance", "Performance", {}, "Pose cache, threading, update-rate, active-pose, and LOD policies."),
        AssetPropertyDescriptor("source_extensions", "Source Extensions", [], "Lossless Unreal or Unity constructs awaiting a native replacement."),
    ),
    "tc.control_rig": (
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton whose pose this graph reads and writes."),
        AssetPropertyDescriptor("graph", "Rig Graph", {"nodes": [], "connections": []}, "Ordered controls, solvers, constraints, math, and output-pose nodes."),
        AssetPropertyDescriptor("controls", "Controls", [], "Viewport controls with shapes, colors, spaces, limits, and exposed channels."),
        AssetPropertyDescriptor("variables", "Variables", {}, "Public and internal typed rig variables."),
        AssetPropertyDescriptor("lod_policy", "Rig LOD Policy", {"minimum_lod": 0, "disabled_nodes": {}}, "Nodes disabled or simplified at distant character LODs."),
    ),
    "tc.ik_rig": (
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton whose bone chains are solved."),
        AssetPropertyDescriptor("retarget_root", "Retarget Root", "", "Root used for proportional motion and root translation."),
        AssetPropertyDescriptor("chains", "IK Chains", [], "Named start/end bone chains with solver, goal, pole, precision, and stretch settings."),
        AssetPropertyDescriptor("goals", "Goals", [], "Reusable IK goal definitions and preview transforms."),
        AssetPropertyDescriptor("excluded_bones", "Excluded Bones", [], "Bones ignored by full-body solvers and retargeting."),
    ),
    "tc.ik_retargeter": (
        AssetPropertyDescriptor("source_ik_rig_id", "Source IK Rig", "", "IK Rig describing the animated source character."),
        AssetPropertyDescriptor("target_ik_rig_id", "Target IK Rig", "", "IK Rig receiving the retargeted pose."),
        AssetPropertyDescriptor("chain_mapping", "Chain Mapping", [], "Source-to-target chain mapping with translation, rotation, and weight settings."),
        AssetPropertyDescriptor("source_retarget_pose", "Source Retarget Pose", {}, "Source pose offsets used to align character proportions."),
        AssetPropertyDescriptor("target_retarget_pose", "Target Retarget Pose", {}, "Target pose offsets used to align character proportions."),
        AssetPropertyDescriptor("root_settings", "Root Settings", {"scale": 1.0, "translation_mode": "scaled", "rotation_mode": "copy"}, "Root-motion scale, translation, rotation, and vertical offset policy."),
    ),
    "tc.skeleton": (
        AssetPropertyDescriptor("bones", "Bones", [], "Stable hierarchy with parent, reference pose, semantic role, and LOD importance."),
        AssetPropertyDescriptor("sockets", "Sockets", [], "Named attachment transforms parented to bones."),
        AssetPropertyDescriptor("retarget_pose", "Retarget Pose", {}, "Reference pose used when transferring animation between compatible skeletons."),
        AssetPropertyDescriptor("preserve_bones", "Always Evaluate Bones", [], "Bones retained in every Bone LOD for gameplay, attachments, IK, or physics."),
    ),
    "tc.skeletal_mesh": (
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton supplying the reference hierarchy and animation pose."),
        AssetPropertyDescriptor("skin_binding_id", "Skin Binding", "", "Portable DCC-authored weights compiled into platform GPU buffers."),
        AssetPropertyDescriptor("sections", "Sections", [], "Material sections with per-section bone palettes and visibility."),
        AssetPropertyDescriptor("lods", "Mesh LODs", [], "Geometry reduction, screen-size, influence, and Bone LOD targets."),
        AssetPropertyDescriptor("bone_lods", "Bone LODs", [], "Retained bones, parent remaps, and evaluation-rate reductions per LOD."),
        AssetPropertyDescriptor("morph_targets", "Morph Targets", [], "Sparse morph targets and their per-LOD availability."),
        AssetPropertyDescriptor("performance_profile", "Performance Profile", "balanced", "Mobile, balanced, high, hero, or cinematic runtime defaults."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Per-platform performance-profile selection and minimum LOD."),
        AssetPropertyDescriptor("bounds", "Animated Bounds", {}, "Predictable animation, cloth, and ragdoll bounds used for visibility culling."),
        AssetPropertyDescriptor("lod_artifacts", "LOD Geometry", [], "Generated or imported LOD mesh files with preservation receipts."),
        AssetPropertyDescriptor("lod_generation_receipt", "LOD Generation Receipt", {}, "Triangle, UV, material, skinning, skeleton, time, and source-fingerprint diagnostics."),
        AssetPropertyDescriptor("optimization_profile_id", "Optimization Profile", "", "Reusable reduction, remeshing, aggregation, baking, culling, or impostor pipeline."),
    ),
    "tc.geometry_optimization_profile": (
        AssetPropertyDescriptor("preset", "Preset", "character_balanced", "Reusable character, HLOD, impostor, or occluder starting point."),
        AssetPropertyDescriptor("source_asset_ids", "Source Assets", [], "Meshes or scene assets processed by this pipeline."),
        AssetPropertyDescriptor("stages", "Processor Stages", [], "Ordered reduction, quad reduction, remeshing, aggregation, impostor, or occlusion stages."),
        AssetPropertyDescriptor("components", "Components", {}, "Material baking, skinning, visibility, and geometry-culling settings."),
        AssetPropertyDescriptor("selection_sets", "Selection Sets", [], "Named process, clipping, visibility, and preservation selections."),
        AssetPropertyDescriptor("execution", "Execution", {"mode": "isolated_process", "workers": 1, "cache": True, "retry_limit": 2, "progress_events": True}, "In-process, isolated, or distributed batch policy with worker, retry, cache, and progress behavior."),
        AssetPropertyDescriptor("reports", "Reports", {}, "Geometry, material, deviation, skinning, timing, and output reports."),
    ),
    "tc.skin_binding": (
        AssetPropertyDescriptor("mesh_id", "Mesh Asset", "", "Stable skeletal-mesh asset ID receiving this binding."),
        AssetPropertyDescriptor("skeleton_id", "Skeleton Asset", "", "Stable skeleton asset ID providing influences."),
        AssetPropertyDescriptor("influences", "Influences", [], "Portable joint influence definitions."),
        AssetPropertyDescriptor("vertex_weights", "Vertex Weights", [], "Sparse normalized per-vertex influence weights."),
        AssetPropertyDescriptor("max_influences", "Maximum Influences", 4, "Maximum joint influences retained per vertex."),
        AssetPropertyDescriptor("normalize", "Normalize Weights", True, "Keep every non-empty vertex weight sum at one."),
        AssetPropertyDescriptor("topology", "Topology Identity", {}, "Vertex count and fingerprint used for safe reimport and transfer."),
        AssetPropertyDescriptor("performance_profile", "Performance Profile", "balanced", "Default platform skinning budget without changing source weights."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Per-platform skin-weight profile selection."),
        AssetPropertyDescriptor("weight_profiles", "Skin Weight Profiles", {}, "Optional per-LOD or fallback weight sets."),
    ),
    "tc.cloth": (
        AssetPropertyDescriptor("source_mesh_id", "Source Skeletal Mesh", "", "Skinned garment mesh. Imported bone weights remain authoritative."),
        AssetPropertyDescriptor("skin_binding_id", "Skin Binding", "", "Existing imported skin binding used as the animated simulation target."),
        AssetPropertyDescriptor("fabric_material_id", "Fabric Material", "", "Reusable physical fabric preset assigned to the garment."),
        AssetPropertyDescriptor("quality_profile", "Quality Profile", "realtime", "Preview, realtime, hero, cinematic, or custom solver quality."),
        AssetPropertyDescriptor("property_maps", "Cloth Paint Maps", {}, "Independent skin-to-simulation, animation-drive, distance, stiffness, collision, and aerodynamic maps."),
        AssetPropertyDescriptor("seams", "Seams", [], "Editable sewn or tearable vertex-pair constraints."),
        AssetPropertyDescriptor("collision_layers", "Collision Layers", [], "Per-vertex layered garment collision assignments."),
        AssetPropertyDescriptor("lods", "Simulation LODs", [], "Simulation meshes, map remapping, budgets, and automatic LOD transitions."),
        AssetPropertyDescriptor("bake_policy", "Bake Policy", "automatic", "Automatic, live runtime, simulation cache, geometry cache, or vertex animation texture."),
        AssetPropertyDescriptor("preserve_imported_skinning", "Preserve Imported Skinning", True, "Never replace imported bone weights while painting cloth behavior."),
    ),
    "tc.groom": (
        AssetPropertyDescriptor("source", "Source", {"mode": "alembic", "path": "", "coordinate_system": "auto", "scale": 1.0}, "Alembic curves, procedural generator, or custom curve provider."),
        AssetPropertyDescriptor("groups", "Hair Groups", [], "Scalp, beard, brows, lashes, fur, or custom groups with guides, rendering, and simulation settings."),
        AssetPropertyDescriptor("lod_mode", "LOD Mode", "auto", "Automatic continuous reduction or explicit manual strand, card, and mesh levels."),
        AssetPropertyDescriptor("lods", "LODs", [], "Screen-size, curve/point reduction, representation, binding, thickness, and simulation policy."),
        AssetPropertyDescriptor("cards", "Hair Cards", {"entries": [], "texture_layout": "compact", "bake_maps": ["depth", "coverage", "tangent", "attributes", "color_roughness"]}, "Imported or generated card geometry and baked texture layouts."),
        AssetPropertyDescriptor("meshes", "Hair Meshes", {"entries": []}, "Hair helmet or other mesh representations for distant LODs."),
        AssetPropertyDescriptor("material_ids", "Hair Materials", [], "Reusable Hair Material assignments for groom groups and representations."),
        AssetPropertyDescriptor("physics_asset_id", "Physics Asset", "", "Collision bodies used by guide simulation."),
        AssetPropertyDescriptor("interpolation", "Interpolation", {"quality": "high", "randomize_guides": True, "rbf": True}, "Guide-to-render-strand interpolation and deformation settings."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Minimum LOD, forced cards/mesh, simulation, shadows, and strand budgets per platform."),
        AssetPropertyDescriptor("diagnostics", "Diagnostics", {}, "Curve, guide, cluster, simulation, rendering, memory, and fallback reports."),
    ),
    "tc.groom_binding": (
        AssetPropertyDescriptor("groom_id", "Groom", "", "Groom whose roots are projected onto the target surface."),
        AssetPropertyDescriptor("target_skeletal_mesh_id", "Target Skeletal Mesh", "", "Skinned surface driving groom root deformation."),
        AssetPropertyDescriptor("source_skeletal_mesh_id", "Source Skeletal Mesh", "", "Optional source topology used for transferable bindings."),
        AssetPropertyDescriptor("root_count", "Root Count", 0, "Expected number of render-strand roots."),
        AssetPropertyDescriptor("root_projections", "Cached Root Projections", [], "Triangle, barycentric coordinate, surface position, and distance per root."),
        AssetPropertyDescriptor("maximum_projection_distance", "Maximum Projection Distance", 0.05, "Warn when roots are farther from the target surface."),
        AssetPropertyDescriptor("binding_mode", "Binding Mode", "skinning", "Skinning, rigid attachment, or RBF deformation."),
    ),
    "tc.hair_material": (
        AssetPropertyDescriptor("preset", "Preset", "brown_hair", "Physical starting point for human hair, fur, or a custom fiber."),
        AssetPropertyDescriptor("base_color", "Base Color", [0.08, 0.03, 0.012], "Fiber absorption color used when melanin controls are overridden."),
        AssetPropertyDescriptor("melanin", "Melanin", 0.75, "Amount of eumelanin-like absorption."),
        AssetPropertyDescriptor("melanin_redness", "Melanin Redness", 0.35, "Pheomelanin-like red response."),
        AssetPropertyDescriptor("roughness", "Longitudinal Roughness", 0.34, "Highlight spread along the fiber."),
        AssetPropertyDescriptor("radial_roughness", "Radial Roughness", 0.44, "Highlight spread around the fiber."),
        AssetPropertyDescriptor("scatter", "Multiple Scattering", 0.2, "Light transport through dense fibers."),
        AssetPropertyDescriptor("specular", "Specular", 0.5, "Fiber surface reflection strength."),
        AssetPropertyDescriptor("root_color", "Root Color", [1.0, 1.0, 1.0], "Root tint multiplied over the physical color."),
        AssetPropertyDescriptor("tip_color", "Tip Color", [1.0, 1.0, 1.0], "Tip tint and dye variation."),
        AssetPropertyDescriptor("random_hue", "Random Hue", 0.02, "Seed-driven per-strand hue variation."),
    ),
    "tc.fabric_material": (
        AssetPropertyDescriptor("preset", "Fabric Preset", "cotton", "Cotton, silk, denim, wool, leather, rubber, nylon, canvas, burlap, chainmail, or custom."),
        AssetPropertyDescriptor("density", "Surface Density", 0.2, "Fabric surface density in kilograms per square meter."),
        AssetPropertyDescriptor("damping", "Damping", 0.025, "Energy loss controlling how quickly fabric motion settles."),
        AssetPropertyDescriptor("friction", "Friction", 0.45, "Contact friction against the body and other colliders."),
        AssetPropertyDescriptor("warp_stiffness", "Warp Stiffness", 0.8, "Resistance along the fabric warp direction."),
        AssetPropertyDescriptor("weft_stiffness", "Weft Stiffness", 0.65, "Resistance along the fabric weft direction."),
        AssetPropertyDescriptor("shear_stiffness", "Shear Stiffness", 0.35, "Resistance to diagonal deformation."),
        AssetPropertyDescriptor("bend_stiffness", "Bend Stiffness", 0.4, "Resistance to folding and wrinkling."),
        AssetPropertyDescriptor("thickness", "Thickness", 0.0006, "Physical fabric thickness in meters."),
        AssetPropertyDescriptor("drag", "Aerodynamic Drag", 0.035, "Air resistance applied to moving fabric."),
        AssetPropertyDescriptor("lift", "Aerodynamic Lift", 0.0, "Lift generated by airflow over the fabric."),
    ),
    "tc.physics_asset": (
        AssetPropertyDescriptor("skeletal_mesh_id", "Skeletal Mesh", "", "Optional preview mesh using this character Physics Asset."),
        AssetPropertyDescriptor("skeleton_id", "Skeleton", "", "Skeleton whose bones own the generated collision bodies."),
        AssetPropertyDescriptor("preset", "Ragdoll Preset", "balanced", "Balanced, light, heavy, passive, or custom starting behavior."),
        AssetPropertyDescriptor("bodies", "Physics Bodies", [], "Editable per-bone rigid bodies and collision shapes."),
        AssetPropertyDescriptor("constraints", "Constraints", [], "Editable limits, drives, damping, and break thresholds between bodies."),
        AssetPropertyDescriptor("collision_pairs", "Collision Pairs", [], "Explicit enabled or disabled collision pairs within the ragdoll."),
        AssetPropertyDescriptor("physical_animation", "Physical Animation", {"enabled": True, "blend": 0.0, "recovery_seconds": 0.35}, "Animation-drive, muscle, blending, and recovery defaults."),
        AssetPropertyDescriptor("solver", "Solver", {"iterations": 8, "substeps": 2}, "Per-asset solver accuracy and stability overrides."),
    ),
    "tc.physics_constraint": (
        AssetPropertyDescriptor("constraint_id", "Constraint Name", "Constraint", "Stable runtime name for this reusable constraint."),
        AssetPropertyDescriptor("first_body", "Body A", "", "First body connected by the constraint."),
        AssetPropertyDescriptor("second_body", "Body B", "", "Second body connected by the constraint."),
        AssetPropertyDescriptor("preset", "Preset", "weld", "Weld, door hinge, ragdoll, piston, suspension, or tether starting values."),
        AssetPropertyDescriptor("joint", "Joint Settings", {}, "Type, anchors, limits, drives, damping, collision, and break thresholds."),
    ),
    "tc.effect_system": (
        AssetPropertyDescriptor("effect_version", "Effect Version", 2, "Versioned real-time VFX authoring contract."),
        AssetPropertyDescriptor("preset", "Effect Preset", "custom", "Editable starting point; applying a preset never locks authored values."),
        AssetPropertyDescriptor("emitters", "Emitters", [], "Ordered reusable emitter definitions."),
        AssetPropertyDescriptor("duration", "Duration", 5.0, "Preview and runtime duration in seconds."),
        AssetPropertyDescriptor("loop", "Loop", True, "Restart the effect after its duration."),
        AssetPropertyDescriptor("scalability", "Scalability", "auto", "Automatic or authored quality policy."),
        AssetPropertyDescriptor("warmup", "Warmup", {}, "Pre-simulation duration and step size for stable looping effects."),
        AssetPropertyDescriptor("fixed_bounds", "Fixed Bounds", {}, "Optional authored bounds for predictable culling and GPU simulation."),
        AssetPropertyDescriptor("parameters", "User Parameters", {}, "Typed values exposed to gameplay, prefabs, timelines, and Python."),
        AssetPropertyDescriptor("event_bindings", "Event Bindings", [], "Spawn, death, collision, and custom cross-emitter reactions."),
        AssetPropertyDescriptor("data_channels", "Data Channels", {}, "Structured data shared between gameplay and effect systems."),
        AssetPropertyDescriptor("data_channel_bindings", "Data Channel Bindings", [], "Publisher and consumer routing for structured VFX data."),
        AssetPropertyDescriptor("subgraphs", "Module Subgraphs", {}, "Reusable and versioned module graphs."),
        AssetPropertyDescriptor("quality_overrides", "Quality Overrides", {}, "Per-quality spawn, capacity, renderer, and emitter reductions."),
        AssetPropertyDescriptor("simulation", "Simulation", {}, "Backend, deterministic seed, fixed step, and substep policy."),
        AssetPropertyDescriptor("pooling", "Pooling", {}, "Instance prewarm, reuse, capacity, and reclaim policy."),
        AssetPropertyDescriptor("source_extensions", "Source Extensions", [], "Preserved engine-specific constructs awaiting a native replacement."),
    ),
    "tc.sound_cue": (
        AssetPropertyDescriptor("audio_version", "Audio Version", 1, "Versioned procedural sound-object contract."),
        AssetPropertyDescriptor("graph", "Sound Graph", {"nodes": [], "connections": []}, "Runtime-evaluated clips, randomization, sequencing, parameters, DSP, and output routing."),
        AssetPropertyDescriptor("parameters", "Parameters", {}, "Typed gameplay and automation inputs."),
        AssetPropertyDescriptor("volume", "Volume", 1.0, "Linear source gain."),
        AssetPropertyDescriptor("pitch", "Pitch", 1.0, "Playback-rate multiplier."),
        AssetPropertyDescriptor("priority", "Priority", 1.0, "Voice-stealing priority."),
        AssetPropertyDescriptor("attenuation_asset_id", "Attenuation", "", "Reusable spatial attenuation and occlusion profile."),
        AssetPropertyDescriptor("mixer_group_id", "Mixer Group", "master", "Primary mixer destination."),
        AssetPropertyDescriptor("submix_sends", "Mixer Sends", [], "Additional manual or distance-driven mixer/reverb sends."),
        AssetPropertyDescriptor("concurrency", "Concurrency", {}, "Voice limit, retrigger, virtualization, and resolution policy."),
        AssetPropertyDescriptor("spatialization", "Spatialization", {}, "Built-in or plugin spatial rendering policy."),
        AssetPropertyDescriptor("source_effects", "Source Effects", [], "Per-voice DSP chain before mixer routing."),
    ),
    "tc.audio_mixer": (
        AssetPropertyDescriptor("audio_version", "Audio Version", 1, "Versioned hierarchical mixer and DSP contract."),
        AssetPropertyDescriptor("groups", "Mixer Groups", [], "Master, music, SFX, dialogue, UI, and custom routing groups."),
        AssetPropertyDescriptor("snapshots", "Snapshots", [], "Interpolated runtime mix states."),
        AssetPropertyDescriptor("parameters", "Exposed Parameters", {}, "Runtime-controllable DSP and routing values."),
        AssetPropertyDescriptor("output", "Output", {}, "Speaker/device format and master headroom."),
    ),
    "tc.audio_attenuation": (
        AssetPropertyDescriptor("spatial_blend", "Spatial Blend", 1.0, "Blend from 2D to fully spatialized 3D audio."),
        AssetPropertyDescriptor("distance_model", "Distance Model", "inverse", "Linear, inverse, logarithmic, or authored curve attenuation."),
        AssetPropertyDescriptor("minimum_distance", "Minimum Distance", 1.0, "Distance before attenuation begins."),
        AssetPropertyDescriptor("maximum_distance", "Maximum Distance", 50.0, "Distance at which the source becomes inaudible."),
        AssetPropertyDescriptor("volume_curve", "Volume Curve", [], "Authored gain over listener distance."),
        AssetPropertyDescriptor("doppler_scale", "Doppler Scale", 1.0, "Relative-velocity pitch response."),
        AssetPropertyDescriptor("spread_degrees", "Spread", 0.0, "Source width in speaker space."),
        AssetPropertyDescriptor("occlusion", "Occlusion", {}, "Trace, volume, filtering, and interpolation settings."),
        AssetPropertyDescriptor("reverb_send", "Reverb Send", {}, "Distance-driven environmental reverb send."),
        AssetPropertyDescriptor("focus", "Listener Focus", {}, "Orientation-driven volume and priority response."),
        AssetPropertyDescriptor("shape", "Attenuation Shape", {}, "Sphere, capsule, box, or cone source region."),
    ),
    "tc.audio_reverb": (
        AssetPropertyDescriptor("preset", "Preset", "room", "Editable room, hall, cave, outdoors, or underwater starting point."),
        AssetPropertyDescriptor("algorithm", "Algorithm", "algorithmic", "Algorithmic or convolution reverb."),
        AssetPropertyDescriptor("impulse_response_asset_id", "Impulse Response", "", "Audio Clip used by convolution reverb."),
        AssetPropertyDescriptor("decay_seconds", "Decay", 1.1, "Mid-frequency reverberation decay time."),
        AssetPropertyDescriptor("pre_delay_ms", "Pre-delay", 8.0, "Delay before early reflections."),
        AssetPropertyDescriptor("wet_db", "Wet Level", -8.0, "Reverberated signal level."),
        AssetPropertyDescriptor("dry_db", "Dry Level", 0.0, "Unprocessed signal level."),
        AssetPropertyDescriptor("diffusion", "Diffusion", 0.8, "Reflection scattering."),
        AssetPropertyDescriptor("density", "Density", 0.85, "Late reflection density."),
        AssetPropertyDescriptor("high_cut_hz", "High Cut", 12000.0, "High-frequency damping cutoff."),
        AssetPropertyDescriptor("low_cut_hz", "Low Cut", 40.0, "Low-frequency filtering cutoff."),
    ),
    "tc.simulation_profile": (
        AssetPropertyDescriptor("solver", "Solver", "particles", "Fluid, volume, cloth, soft-body, or particle solver."),
        AssetPropertyDescriptor("time_step", "Time Step", 0.0166667, "Fixed simulation step in seconds.", True),
        AssetPropertyDescriptor("substeps", "Substeps", 2, "Extra accuracy for fast or stiff motion."),
        AssetPropertyDescriptor("cache_policy", "Cache Policy", "live", "Live, record, or baked playback."),
    ),
    "tc.physical_material": (
        AssetPropertyDescriptor("friction", "Friction", 0.5, "Resistance to tangential sliding."),
        AssetPropertyDescriptor("restitution", "Restitution", 0.1, "Bounciness after collision."),
        AssetPropertyDescriptor("density", "Density", 1000.0, "Mass per cubic meter."),
        AssetPropertyDescriptor("surface_type", "Surface Type", "default", "Gameplay/audio surface classification."),
    ),
    "tc.physics_scene": (
        AssetPropertyDescriptor("gravity", "Gravity", [0.0, -9.81, 0.0], "World gravity vector."),
        AssetPropertyDescriptor("fixed_time_step", "Fixed Time Step", 0.0166667, "Physics update interval.", True),
        AssetPropertyDescriptor("solver_iterations", "Solver Iterations", 8, "Constraint accuracy and cost.", True),
        AssetPropertyDescriptor("collision_layers", "Collision Layers", {}, "Named collision response matrix."),
    ),
    "tc.vehicle_rig": (
        AssetPropertyDescriptor("mass", "Mass", 1350.0, "Vehicle chassis mass in kilograms."),
        AssetPropertyDescriptor("center_of_mass_offset", "Center of Mass Offset", [0.0, -0.35, 0.0], "Local chassis center-of-mass adjustment."),
        AssetPropertyDescriptor("maximum_steer_angle", "Maximum Steer Angle", 32.0, "Maximum front-wheel steering angle in degrees."),
        AssetPropertyDescriptor("engine_force", "Engine Force", 8500.0, "Peak longitudinal drive force."),
        AssetPropertyDescriptor("aerodynamic_drag", "Aerodynamic Drag", 0.34, "Quadratic high-speed drag coefficient."),
        AssetPropertyDescriptor("rolling_resistance", "Rolling Resistance", 0.015, "Low-speed tire and bearing resistance."),
        AssetPropertyDescriptor("anti_roll_stiffness", "Anti-roll Stiffness", 7500.0, "Axle force opposing left/right suspension imbalance."),
        AssetPropertyDescriptor("wheels", "Wheels", [], "Wheel mounts, radii, suspension, steering, drive, brake, and axle settings."),
    ),
    "tc.gameplay_graph": (
        AssetPropertyDescriptor("components", "Components", [], "Reusable component configuration."),
        AssetPropertyDescriptor("variables", "Variables", {}, "Editable exposed gameplay values."),
        AssetPropertyDescriptor("events", "Events", [], "Event graph entry points."),
    ),
    "tc.gameplay_class": (
        AssetPropertyDescriptor("class_version", "Class Version", 1, "Versioned Gameplay Class authoring contract."),
        AssetPropertyDescriptor("class_kind", "Class Kind", "actor", "Actor, Pawn, Character, Controller, Component, Object, or Game Instance."),
        AssetPropertyDescriptor("parent_class_id", "Parent Class", "", "Optional Gameplay Class inherited by this class."),
        AssetPropertyDescriptor("abstract", "Abstract", False, "Prevent direct spawning while allowing inheritance."),
        AssetPropertyDescriptor("interfaces", "Interfaces", [], "Named gameplay contracts implemented by this class."),
        AssetPropertyDescriptor("components", "Components", [{"id": "root", "name": "Root", "type": "transform", "parent_id": "", "enabled": True, "properties": {}}], "Inherited component hierarchy and defaults."),
        AssetPropertyDescriptor("variables", "Variables", [], "Typed editable, instance, save-game, and replicated variables."),
        AssetPropertyDescriptor("functions", "Functions", [], "Callable functions with typed inputs, outputs, purity, and authority policy."),
        AssetPropertyDescriptor("events", "Events", ["On Begin Play"], "Event entry points implemented by this class."),
        AssetPropertyDescriptor("event_graph", "Event Graph", {"entry_event": "On Begin Play", "nodes": [], "connections": []}, "Executable gameplay event graph."),
        AssetPropertyDescriptor("defaults", "Class Defaults", {}, "Default values applied to new instances."),
        AssetPropertyDescriptor("replication", "Replication", {"mode": "local", "replicate_movement": False, "network_frequency": 30.0, "dormancy": "awake"}, "Class replication, movement, frequency, and dormancy settings."),
        AssetPropertyDescriptor("tags", "Tags", [], "Gameplay classification tags."),
    ),
    "tc.project_settings": (
        AssetPropertyDescriptor("project", "Project Identity", {"display_name": "Game", "company": "", "version": "0.1.0", "description": ""}, "Product name, company, version, and description."),
        AssetPropertyDescriptor("startup", "Startup", {"default_level_asset_id": "", "loading_level_asset_id": ""}, "Default and loading levels."),
        AssetPropertyDescriptor("gameplay", "Gameplay Defaults", {"ruleset_asset_id": "", "default_character_asset_id": "", "input_map_asset_id": "", "game_instance_asset_id": ""}, "Ruleset, player character, input, and persistent game instance."),
        AssetPropertyDescriptor("rendering", "Rendering", {"quality_profile": "high", "frame_rate_limit": 0, "hdr": True}, "Default presentation and frame pacing."),
        AssetPropertyDescriptor("physics", "Physics", {"physics_scene_asset_id": "", "fixed_time_step": 0.0166667}, "Global physics scene and fixed step."),
        AssetPropertyDescriptor("audio", "Audio", {"mixer_asset_id": "", "master_volume": 1.0}, "Default mixer and master level."),
        AssetPropertyDescriptor("build", "Build", {"default_build_profile_asset_id": ""}, "Default packaging profile."),
        AssetPropertyDescriptor("platform_overrides", "Platform Overrides", {}, "Settings overridden for individual target platforms.", True),
    ),
    "tc.data_schema": (
        AssetPropertyDescriptor("parent_schema_id", "Parent Schema", "", "Optional inherited schema."),
        AssetPropertyDescriptor("fields", "Fields", [], "Named typed fields, defaults, constraints, descriptions, and references."),
        AssetPropertyDescriptor("tags", "Tags", [], "Search and classification tags."),
        AssetPropertyDescriptor("documentation", "Documentation", "", "Schema usage guidance."),
    ),
    "tc.struct": (
        AssetPropertyDescriptor("parent_schema_id", "Parent Struct", "", "Optional inherited struct."),
        AssetPropertyDescriptor("fields", "Fields", [], "Named typed members."),
        AssetPropertyDescriptor("tags", "Tags", [], "Search and classification tags."),
        AssetPropertyDescriptor("documentation", "Documentation", "", "Struct usage guidance."),
    ),
    "tc.enum": (
        AssetPropertyDescriptor("flags", "Flags Enum", False, "Allow bitwise combinations of entries."),
        AssetPropertyDescriptor("entries", "Entries", [{"name": "Default", "value": 0, "description": ""}], "Stable names, numeric values, and descriptions."),
    ),
    "tc.input_map": (
        AssetPropertyDescriptor("contexts", "Contexts", ["Gameplay"], "Input contexts and their priority."),
        AssetPropertyDescriptor("actions", "Actions", {}, "Named actions with keyboard, mouse, and controller bindings."),
    ),
    "tc.data": (
        AssetPropertyDescriptor("schema_asset_id", "Schema", "", "Data Schema defining accepted fields."),
        AssetPropertyDescriptor("values", "Values", {}, "Serializable project data."),
        AssetPropertyDescriptor("primary_asset", "Primary Asset", False, "Addressable identity and explicit load policy."),
        AssetPropertyDescriptor("bundle_labels", "Bundle Labels", [], "Content bundle or delivery labels."),
        AssetPropertyDescriptor("tags", "Tags", [], "Search and gameplay tags."),
    ),
    "tc.data_table": (
        AssetPropertyDescriptor("row_schema_id", "Row Schema", "", "Schema or Struct shared by every row."),
        AssetPropertyDescriptor("key_field", "Key Field", "id", "Unique field used to identify rows."),
        AssetPropertyDescriptor("rows", "Rows", [], "Typed tabular records."),
        AssetPropertyDescriptor("source_csv", "Source CSV", "", "Optional round-trip source path."),
        AssetPropertyDescriptor("tags", "Tags", [], "Search and gameplay tags."),
    ),
    "tc.component_archetype": (
        AssetPropertyDescriptor("parent_archetype_id", "Parent Archetype", "", "Optional inherited component hierarchy."),
        AssetPropertyDescriptor("components", "Components", [{"id": "root", "name": "Root", "type": "transform", "parent_id": "", "enabled": True, "properties": {}}], "Ordered component hierarchy and defaults."),
        AssetPropertyDescriptor("exposed_properties", "Exposed Properties", [], "Properties editable by instances."),
        AssetPropertyDescriptor("replication", "Replication", "inherit", "Inherit, local, replicated, or server-only policy."),
        AssetPropertyDescriptor("tags", "Tags", [], "Component classification tags."),
    ),
    "tc.character_definition": (
        AssetPropertyDescriptor("archetype_asset_id", "Component Archetype", "", "Reusable component hierarchy."),
        AssetPropertyDescriptor("skeletal_mesh_asset_id", "Skeletal Mesh", "", "Character render mesh."),
        AssetPropertyDescriptor("skeleton_asset_id", "Skeleton", "", "Animation skeleton."),
        AssetPropertyDescriptor("skin_binding_asset_id", "Skin Binding", "", "Mesh-to-skeleton weights."),
        AssetPropertyDescriptor("animation_controller_asset_id", "Animation Controller", "", "Locomotion and action state machine."),
        AssetPropertyDescriptor("input_map_asset_id", "Input Map", "", "Default player input mapping."),
        AssetPropertyDescriptor("camera_archetype_asset_id", "Camera Archetype", "", "Camera and boom component setup."),
        AssetPropertyDescriptor("physics_asset_id", "Physics Asset", "", "Ragdoll and collision setup."),
        AssetPropertyDescriptor("movement", "Movement", {"mode": "walking", "maximum_speed": 6.0, "acceleration": 24.0, "deceleration": 30.0, "jump_height": 1.2, "air_control": 0.35, "rotation_mode": "orient_to_movement"}, "Movement tuning and orientation policy."),
        AssetPropertyDescriptor("abilities", "Abilities", [], "Ability asset references and initial grants."),
        AssetPropertyDescriptor("attributes", "Attributes", {}, "Initial typed gameplay attributes."),
        AssetPropertyDescriptor("network", "Network", {"replicated": True, "prediction": True}, "Replication and prediction intent."),
        AssetPropertyDescriptor("tags", "Tags", ["character.player"], "Gameplay classification tags."),
    ),
    "tc.game_ruleset": (
        AssetPropertyDescriptor("default_level", "Default Level", "", "Level loaded when the game starts."),
        AssetPropertyDescriptor("default_player", "Default Player", "", "Player prefab or gameplay class."),
        AssetPropertyDescriptor("input_map", "Input Map", "", "Input mapping used for gameplay."),
        AssetPropertyDescriptor("physics_scene", "Physics Scene", "", "Global physics configuration."),
        AssetPropertyDescriptor("default_locomotion", "Default Locomotion", "", "Character movement, camera, and animation controller."),
        AssetPropertyDescriptor("default_skeleton", "Default Skeleton", "", "Biped skeleton used by the starter player."),
        AssetPropertyDescriptor("default_skeletal_mesh", "Default Skeletal Mesh", "", "Skinned starter-character mesh used by the player."),
        AssetPropertyDescriptor("default_skin_binding", "Default Skin Binding", "", "Skin weights connecting the starter mesh to its skeleton."),
        AssetPropertyDescriptor("default_character_material", "Default Character Material", "", "Editable material assigned to the starter character."),
        AssetPropertyDescriptor("default_character_texture", "Default Character Texture", "", "Imported starter surface texture used by the character material."),
        AssetPropertyDescriptor("default_ik_rig", "Default IK Rig", "", "IK chains and goals used for retargeting and procedural placement."),
        AssetPropertyDescriptor("default_control_rig", "Default Control Rig", "", "Editable body, hand, foot, look-at, and facial controls."),
        AssetPropertyDescriptor("default_character_physics", "Default Character Physics", "", "Ragdoll bodies and constraints generated for the starter character."),
    ),
    "tc.build_profile": (
        AssetPropertyDescriptor("platform", "Platform", "windows", "Target runtime platform."),
        AssetPropertyDescriptor("configuration", "Configuration", "development", "Development, test, or shipping build."),
        AssetPropertyDescriptor("entry_level", "Entry Level", "", "First packaged level."),
        AssetPropertyDescriptor("quality_profile", "Quality Profile", "high", "Default rendering and simulation quality."),
        AssetPropertyDescriptor("included_levels", "Included Levels", [], "Additional level asset IDs included in the package."),
        AssetPropertyDescriptor("incremental", "Incremental Build", True, "Reuse unchanged cooked artifacts."),
        AssetPropertyDescriptor("output_directory", "Output Directory", "Build", "Project-relative package output directory."),
        AssetPropertyDescriptor("include_debug_symbols", "Debug Symbols", True, "Include symbols for crash diagnosis."),
    ),
    "tc.prefab": (
        AssetPropertyDescriptor("prefab_version", "Prefab Version", 2, "Serialized Prefab authoring format version."),
        AssetPropertyDescriptor("entities", "Entities", [], "Nested entity and component templates."),
        AssetPropertyDescriptor("exposed_properties", "Exposed Properties", {}, "Values instances may override."),
        AssetPropertyDescriptor("base_prefab_id", "Parent Prefab", "", "Optional parent used by a Prefab Variant."),
        AssetPropertyDescriptor("variant_overrides", "Variant Overrides", {}, "Property-path overrides inherited from the parent Prefab."),
        AssetPropertyDescriptor("removed_entity_ids", "Removed Entities", [], "Inherited entity IDs hidden by this variant."),
        AssetPropertyDescriptor("added_entities", "Added Entities", [], "Entities owned only by this variant."),
    ),
}


def asset_property_schema(type_id: str) -> tuple[AssetPropertyDescriptor, ...]:
    return _SCHEMAS.get(str(type_id).casefold(), ())


def default_asset_properties(type_id: str) -> dict[str, Any]:
    return {item.key: deepcopy(item.default) for item in asset_property_schema(type_id)}


def merge_asset_properties(type_id: str, values: dict[str, Any] | None) -> dict[str, Any]:
    result = default_asset_properties(type_id)
    result.update(deepcopy(dict(values or {})))
    return result


_IMPORT_DEFAULTS: dict[str, dict[str, Any]] = {
    "tc.texture": {"color_space": "srgb", "generate_mips": True, "compression": "auto", "max_size": 0},
    "tc.static_mesh": {"scale": 1.0, "normals": "import", "tangents": "generate", "generate_collision": True},
    "tc.skeletal_mesh": {"scale": 1.0, "import_skin": True, "import_morph_targets": True},
    "tc.animation_clip": {"sample_rate": 0, "root_motion": "preserve", "compression": "auto"},
    "tc.audio_clip": {"stream": False, "normalize": False, "compression": "auto"},
    "tc.video": {"proxy": "auto", "color_space": "srgb", "loop_preview": True},
    "tc.font": {"hinting": "auto", "atlas_size": 2048, "fallback": True},
}


def default_import_settings(type_id: str) -> dict[str, Any]:
    return deepcopy(_IMPORT_DEFAULTS.get(str(type_id).casefold(), {}))


def merge_import_settings(type_id: str, values: dict[str, Any] | None) -> dict[str, Any]:
    result = default_import_settings(type_id)
    result.update(deepcopy(dict(values or {})))
    return result
