# index_worker.py - Incremental indexing and embedding for Unreal assets
"""Index worker for Unreal Blueprint assets.

This database is Unreal asset intelligence for the Copilot/daemon context path.
It is deliberately separate from the canonical Python project-search index at
``knowledge/index/knowledge_index_v2.sqlite``. Do not use this DB for facts like
Python imports, unused files, unresolved imports, or call sites; those belong to
``knowledge/build_knowledge_index_v2.py`` and ``knowledge/search.py``.

The worker reads exported Blueprint markdown (generated by
`bridges/unreal/blueprint_exporter.py`), computes a dense embedding using a
lightweight Sentence‑Transformers model, and stores the data in a SQLite
database used by the AI‑Studio "copilot" layer.

Key responsibilities:
  * Load or create the SQLite DB with versioning metadata.
  * Export a Blueprint asset to markdown (cached on disk).
  * Invalidate the cache when the underlying `.uasset` file changes.
  * Compute an embedding on demand – the model is downloaded the first time
    it is needed and cached under `<project_root>/data/model_cache/`.
  * Upsert rows in the `assets`, `embeddings` and `dependencies` tables.

The implementation is deliberately defensive: all heavy imports are wrapped
in `try/except` blocks so the package works even when optional deps are not
installed.  The UI can invoke :func:`index_asset` or :func:`reindex_all` via
the daemon's HTTP API.
"""
import json
import pathlib
import sqlite3
import hashlib
import time
from typing import Dict, List, Optional, Tuple

APP_ROOT = pathlib.Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# Configuration – defaults (overridden by settings.json)
# ---------------------------------------------------------------------------
DEFAULT_DB_PATH = APP_ROOT / "data" / "ai_intel.db"
DEFAULT_MODEL_NAME = "all-MiniLM-L6-v2"
DEFAULT_MODEL_CACHE = APP_ROOT / "data" / "model_cache"

def _get_settings() -> dict:
    try:
        from tech_connector.services.settings_service import load_settings
        return load_settings()
    except Exception:
        return {}

def _get_db_path() -> pathlib.Path:
    settings = _get_settings()
    path_str = settings.get("db_path")
    if path_str:
        return pathlib.Path(path_str)
    return DEFAULT_DB_PATH

def _get_model_name() -> str:
    settings = _get_settings()
    return settings.get("embedding_model") or DEFAULT_MODEL_NAME

def _get_model_cache() -> pathlib.Path:
    settings = _get_settings()
    path_str = settings.get("model_cache_dir")
    if path_str:
        return pathlib.Path(path_str)
    return DEFAULT_MODEL_CACHE

def _get_cache_dir() -> pathlib.Path:
    settings = _get_settings()
    path_str = settings.get("index_cache_dir")
    if path_str:
        return pathlib.Path(path_str)
    return APP_ROOT / "data" / "blueprint_cache"

# ---------------------------------------------------------------------------
# Helper: lazy import of sentence‑transformers
# ---------------------------------------------------------------------------
def _load_embedding_model() -> "Any":
    """Load the Sentence‑Transformers model, downloading it on first use.

    The function returns a model object with a ``encode`` method that accepts a
    list of strings and returns a list of vectors (list[float]).  If the package
    is unavailable, a clear RuntimeError is raised – the daemon can catch this
    and report the problem to the UI.
    """
    try:
        from sentence_transformers import SentenceTransformer  # type: ignore
    except Exception as e:
        raise RuntimeError(
            "sentence_transformers not installed; install it to enable embedding"
        ) from e

    cache_dir = _get_model_cache()
    cache_dir.mkdir(parents=True, exist_ok=True)
    model_path = cache_dir / _get_model_name()
    # SentenceTransformer will download the model into the directory if missing.
    return SentenceTransformer(str(model_path))

# Global placeholder – instantiated on first call.
_MODEL = None  # type: ignore

def _get_model():
    global _MODEL
    if _MODEL is None:
        _MODEL = _load_embedding_model()
    return _MODEL

# ---------------------------------------------------------------------------
# SQLite schema & connection helper
# ---------------------------------------------------------------------------
_SCHEMA = """
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,          -- e.g. "Blueprint"
    content TEXT,                -- exported markdown
    mtime REAL,                  -- last‑modified timestamp (unix epoch)
    version INTEGER DEFAULT 1   -- schema version for this row
);

CREATE TABLE IF NOT EXISTS embeddings (
    asset_id INTEGER PRIMARY KEY,
    vector BLOB NOT NULL,
    FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dependencies (
    asset_id INTEGER,
    depends_on INTEGER,
    PRIMARY KEY(asset_id, depends_on),
    FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE CASCADE,
    FOREIGN KEY(depends_on) REFERENCES assets(id) ON DELETE CASCADE
);
"""

def _connect(db_path: Optional[pathlib.Path] = None) -> sqlite3.Connection:
    if db_path is None:
        db_path = _get_db_path()
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path))
    conn.executescript(_SCHEMA)
    # Store schema version if not present
    cur = conn.execute("SELECT value FROM meta WHERE key='schema_version'")
    row = cur.fetchone()
    if not row:
        conn.execute(
            "INSERT INTO meta (key, value) VALUES ('schema_version', '1')"
        )
        conn.commit()
    return conn

# ---------------------------------------------------------------------------
# Blueprint export & cache handling
# ---------------------------------------------------------------------------
def _cache_path_for_asset(asset_path: pathlib.Path) -> pathlib.Path:
    cache_dir = _get_cache_dir()
    cache_dir.mkdir(parents=True, exist_ok=True)
    # Use a stable hash of the absolute path to avoid filesystem limits.
    h = hashlib.sha256(str(asset_path).encode()).hexdigest()[:12]
    return cache_dir / f"{h}.md"

def export_blueprint(asset_path: pathlib.Path) -> str:
    """Export a Blueprint to markdown, using the cached file when possible.

    The cache is considered stale when the file's modification time differs
    from the stored ``mtime`` column.
    """
    # Import the exporter lazily – it may rely on the Unreal Python API.
    try:
        from tech_connector.bridges.unreal.blueprint_exporter import export_blueprint_to_text as export_blueprint_to_markdown
    except Exception as e:
        raise RuntimeError(
            "Failed to import blueprint_exporter – ensure the 'unreal' Python package is available"
        ) from e

    cache_file = _cache_path_for_asset(asset_path)
    asset_mtime = asset_path.stat().st_mtime
    # If cache exists and is up‑to‑date, read it.
    if cache_file.is_file():
        # Retrieve stored mtime from DB if present.
        conn = _connect()
        cur = conn.execute(
            "SELECT mtime FROM assets WHERE path=?", (str(asset_path),)
        )
        row = cur.fetchone()
        if row and row[0] == asset_mtime:
            # Cache is fresh.
            conn.close()
            return cache_file.read_text(encoding="utf-8")
        conn.close()
    # Cache miss or stale – re‑export.
    markdown = export_blueprint_to_markdown(str(asset_path))
    cache_file.write_text(markdown, encoding="utf-8")
    return markdown

# ---------------------------------------------------------------------------
# Indexing functions
# ---------------------------------------------------------------------------
def index_asset(asset_path: str) -> Tuple[int, bool]:
    """Index a single asset.

    Returns a tuple ``(asset_id, updated)`` where ``updated`` is ``True`` when
    the row or its embedding changed.
    """
    path = pathlib.Path(asset_path).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"Asset not found: {asset_path}")

    content = export_blueprint(path)
    mtime = path.stat().st_mtime
    conn = _connect()
    cur = conn.execute("SELECT id, mtime FROM assets WHERE path=?", (str(path),))
    row = cur.fetchone()
    if row:
        asset_id, stored_mtime = row
        if stored_mtime == mtime:
            # No change – nothing to do.
            conn.close()
            return asset_id, False
        # Update content and mtime.
        conn.execute(
            "UPDATE assets SET content=?, mtime=? WHERE id=?",
            (content, mtime, asset_id),
        )
    else:
        # Insert new asset.
        conn.execute(
            "INSERT INTO assets (path, type, content, mtime) VALUES (?,?,?,?)",
            (str(path), "Blueprint", content, mtime),
        )
        asset_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

    # Compute embedding.
    model = _get_model()
    vector = model.encode([content])[0]  # returns list[float]
    # Store as binary (float32 little‑endian).
    import array
    arr = array.array('f', vector)
    blob = arr.tobytes()
    conn.execute(
        "INSERT OR REPLACE INTO embeddings (asset_id, vector) VALUES (?,?)",
        (asset_id, blob),
    )
    conn.commit()
    conn.close()
    return asset_id, True

def reindex_all(project_root: Optional[str] = None) -> int:
    """Walk the project and (re)index every ``.uasset`` file.

    Returns the number of assets processed.
    """
    root = pathlib.Path(project_root) if project_root else pathlib.Path.cwd()
    count = 0
    for uasset in root.rglob("*.uasset"):
        try:
            index_asset(str(uasset))
            count += 1
        except Exception:
            # Silently skip problematic assets – they will be logged later.
            continue
    return count

# ---------------------------------------------------------------------------
# Simple similarity search (used by the daemon's HTTP API)
# ---------------------------------------------------------------------------
def _vector_to_array(blob: bytes) -> List[float]:
    import array
    arr = array.array('f')
    arr.frombytes(blob)
    return list(arr)

def search_similar(query: str, top_k: int = 10) -> List[Dict[str, any]]:
    """Return the *top_k* most similar assets to *query*.

    The function computes an embedding for the query string and performs a
    cosine‑similarity scan over all stored vectors.  For modest data sizes this
    linear scan is acceptable; a future optimisation could use FAISS.
    """
    model = _get_model()
    q_vec = model.encode([query])[0]
    import numpy as np
    q_arr = np.array(q_vec, dtype=np.float32)

    conn = _connect()
    cur = conn.execute("SELECT a.id, a.path, e.vector FROM assets a JOIN embeddings e ON a.id=e.asset_id")
    results = []
    for asset_id, path, vec_blob in cur:
        vec = np.array(_vector_to_array(vec_blob), dtype=np.float32)
        # Cosine similarity
        sim = float(np.dot(q_arr, vec) / (np.linalg.norm(q_arr) * np.linalg.norm(vec) + 1e-9))
        results.append({"id": asset_id, "path": path, "score": sim})
    conn.close()
    results.sort(key=lambda x: x["score"], reverse=True)
    return results[:top_k]

# ---------------------------------------------------------------------------
# Entry‑point for debugging (not used by the daemon)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse, sys
    parser = argparse.ArgumentParser(description="Reindex Unreal assets")
    parser.add_argument("root", nargs="?", default=".")
    args = parser.parse_args()
    n = reindex_all(args.root)
    print(f"Indexed {n} assets")
