"""Install the Blender Tech Connector bridge into Blender's user script folder."""

import argparse
import os
import shutil
import sys
from pathlib import Path


ADDON_SOURCE = Path(__file__).with_name("blender_ai_studio_bridge_addon.py")
ADDON_MODULE = "the_entire_world_ai_studio_bridge"
ADDON_FILENAME = ADDON_MODULE + ".py"
STARTUP_FILENAME = "the_entire_world_ai_studio_bridge_startup.py"


def blender_user_root(appdata=None):
    base = Path(appdata or os.environ.get("APPDATA", ""))
    if not base:
        raise RuntimeError("APPDATA is not set; cannot find Blender user scripts.")
    return base / "Blender Foundation" / "Blender"


def discover_versions(root):
    if not root.exists():
        return []
    versions = []
    for child in root.iterdir():
        if child.is_dir() and child.name[0:1].isdigit():
            versions.append(child.name)
    return sorted(versions, key=_version_key)


def _version_key(value):
    parts = []
    for part in value.split("."):
        try:
            parts.append(int(part))
        except ValueError:
            parts.append(0)
    return parts


def select_versions(root, requested=None, all_versions=False):
    versions = discover_versions(root)
    if requested:
        return [requested]
    if all_versions:
        return versions
    if versions:
        return [versions[-1]]
    return []


def install_to_version(version_root, dry_run=False):
    addon_dir = version_root / "scripts" / "addons"
    startup_dir = version_root / "scripts" / "startup"
    addon_target = addon_dir / ADDON_FILENAME
    startup_target = startup_dir / STARTUP_FILENAME

    startup_code = startup_code_for(addon_dir)

    if not dry_run:
        addon_dir.mkdir(parents=True, exist_ok=True)
        startup_dir.mkdir(parents=True, exist_ok=True)
        try:
            shutil.copy2(ADDON_SOURCE, addon_target)
        except PermissionError:
            if not addon_target.exists():
                raise
        try:
            startup_target.write_text(startup_code, encoding="utf-8")
        except PermissionError:
            if not startup_target.exists():
                raise

    return addon_target, startup_target


def startup_code_for(addon_dir):
    return f"""# Auto-generated by The Entire World Tech Connector.
import importlib
import sys

addon_dir = r"{addon_dir}"
if addon_dir not in sys.path:
    sys.path.append(addon_dir)

module = importlib.import_module("{ADDON_MODULE}")
if hasattr(module, "register"):
    module.register()
"""


def version_needs_install(version_root):
    addon_dir = version_root / "scripts" / "addons"
    addon_target = addon_dir / ADDON_FILENAME
    startup_target = version_root / "scripts" / "startup" / STARTUP_FILENAME

    if not addon_target.exists() or not startup_target.exists():
        return True

    try:
        source = ADDON_SOURCE.read_text(encoding="utf-8")
        installed = addon_target.read_text(encoding="utf-8")
        startup = startup_target.read_text(encoding="utf-8")
    except Exception:
        return True

    return installed != source or startup != startup_code_for(addon_dir)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", help="Install to a specific Blender version, for example 4.3.")
    parser.add_argument("--all", action="store_true", help="Install to every discovered Blender version.")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be written without copying files.")
    args = parser.parse_args(argv)

    if not ADDON_SOURCE.exists():
        print("Missing %s" % ADDON_SOURCE)
        return 1

    root = blender_user_root()
    versions = select_versions(root, requested=args.version, all_versions=args.all)
    if not versions:
        print("No Blender user versions found under: %s" % root)
        print("Open Blender once, then run this installer again.")
        return 1

    for version in versions:
        addon_target, startup_target = install_to_version(root / version, dry_run=args.dry_run)
        action = "Would install" if args.dry_run else "Installed"
        print("%s Blender bridge for %s" % (action, version))
        print("  Add-on:  %s" % addon_target)
        print("  Startup: %s" % startup_target)

    if not args.dry_run:
        print("")
        print("Done. Restart Blender, then use Tools > Blender in Tech Connector.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
